### ISSUE TITLE
Should we add auto merging for minor and patch dependabot?

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1013]
I just found this action:
https://github.com/nextcloud/.github/blob/master/workflow-templates/dependabot-approve-merge.properties.json

Do we want to enable that or is that no good idea?

I am asking for your opinions @seyfeb @MarcelRobitaille and all other potential contributors.

**Comment by TheMBeat** [comment]
What are the advantages of Automerge and what are the possible dangers?

In itself, I find any form of automation helpful.

**Comment by MarcelRobitaille** [comment]
I don't think I'm familiar enough with dependabot to give a firm answer. I could see this being very useful if it works and disastrous if it breaks.

**Comment by christianlupus** [comment]
Currently, all dependeabot changes are merged manually. For composer dependency this is not much as we have not committed the `composer.lock` but only the `composer.json`. So only big updates will be shown. For NPM all patch and minor updates need manual confirmation.

The thing is that we have no test suite for the Frontend in place. So, there will be no stopping to break the Frontend in case anything introduces a regression. This is the major danger involved in doing such automatic merges.

Normally, I check if the PR is something related to the toolchain or the real Frontend. When only the toolchain is affected one will see it directly in the GH action-based tests. If it is something more _critical_ I normally do a quick test myself.

**Comment by seyfeb** [comment]
@christianlupus Since you are the one doing the work here, I would leave the decision mostly to you. Patches should be save to apply in any way, but also minor commits (in a perfect world) should not break anything..
