### ISSUE TITLE
I translated cookbook into Vietnamese - please include it in the next release

### ISSUE THREAD

**Issue by Kuphi** [nextcloud/cookbook#1027]
All 104 phrases were translated into Vietnamese and checked for mistakes by a Vietnamese native speaker.
https://www.transifex.com/nextcloud/nextcloud/translate/#vi/cookbook_flutter/

Can you include Vietnamese in the next release or does it require anything else?

Thanks!

**Comment by Kuphi** [comment]
Oh, it was just the flutter app. Will also do the browser client next: https://www.transifex.com/nextcloud/nextcloud/translate/#vi/cookbook/320360216?q=reviewed:no
I think there's no general Vietnamese user interface for Nextcloud yet.

How to use the Cookbook browser interface in a yet unsupported nextcloud language?

**Comment by Kuphi** [comment]
All 157 cookbook phrases are translated into Vietnamese now as well: https://www.transifex.com/nextcloud/nextcloud/translate/#vi/cookbook

**Comment by christianlupus** [comment]
Thank you for translating this. The changes were automatically imported from transifex into the codebase. See [this commit](https://github.com/nextcloud/cookbook/commit/4f3b4bbca1a5643187877e9b396c86473b55d84e).

This will be in the next release for sure. I'm thus closing this issue as it is in the `master` branch and will be part of any upcoming release.
