### ISSUE TITLE
Make recipeYield optional

### ISSUE THREAD

**Issue by DeaeLunae** [nextcloud/cookbook#1042]
**Is your feature request related to a problem? Please describe.**
Not all recipes have a serving size, as they are components and not final dish. "Apple pie" make have 8 servings, but "Custom pie crust" used in "apple pie" doesn't mesh.

**Describe the solution you'd like**
Ability to not show Servings on a recipe page

**Describe alternatives you've considered**
I also don't like the date created/modified tags and found I could just remove them from the json to have them not show up. Not the case for "servings" however. It just sits there mocking me.

**Comment by christianlupus** [comment]
I am trying to implement the backend part of this issue in a current update of the php code case.

If you would help with the design and the frontend, @TheMBeat or others, that would be very useful.

**Comment by TheMBeat** [comment]
I could try to implement the UI, maybe a simple Checkbox to set the value to null.

**Comment by christianlupus** [comment]
Let me finish my current work related to the upgrade of recipe parsing and filtering. Once this is prepared, we can make the frontend compatible (again).
