### ISSUE TITLE
Cannot import recipes by rescanning

### ISSUE THREAD

**Issue by wildernessfamily** [nextcloud/cookbook#1058]
**Description**
I set up a NextCloud instance for my family and extended family. Installed Cookbook extension. I was testing it out and it was working great! Decided to open it up for my entire family to use. In the admin section, I created a new group folder for my "Family" group called "/My Family Recipes" with full permissions. I copied all the recipes from the /Recipes folder into the group folder. I then went into the Recipes settings and changed the folder to the "/My Family Recipes" and refreshed. Nothing showed up. I rescanned the library. Still nothing. I then copied all the files from the "/My Family Recipes" back to the "/Recipes" folder. I went back into the Cookbook settings and changed the folder back to "/Recipes" folder.  I refreshed the browser and no recipes. I clicked "Rescan" and now I just received a blue screen that says Error "Bad Signature". 

**What I Tried**
Disabling/Enabling Cookbook Extension
Uninstalled/Reinstall Cookbook Extension

**Screenshot**
![Screen Shot 2022-06-25 at 12 57 41](https://user-images.githubusercontent.com/84930441/175787089-b80fa3e8-2a68-42dd-b428-1281df4dc479.jpg)

**Browser**
Firefox 101.0.1 | I also tried on Safari

**Versions**
Nextcloud server version: 23.02
Cookbook version: 0.9.12
Database system: MySQL

**Comment by wildernessfamily** [comment]
I was able to fix the error. I rename the folder Recipes temporarily to something different. As soon as I did that I was able to get into the Cookbook. I changed the Folder again to "/My Family Recipes" but no recipes are showing up, even after a rescan.

**Comment by wildernessfamily** [comment]
I've tried to change it back and to a new folder. Each time it states "failed to fetch categories"

**Comment by christianlupus** [comment]
Hello @wildernessfamily. I have not heard of such a problem so, we need more information to tackle this.

You copied (or moved) your recipe files back and forth. Where are your recipes now stored just in `/My Family Recipes` or in `/Recipes` (or something like that) **or both**?

Are the folders containing the recipes (JSON files)? How many (approx)?

Open the developer tools (F12 in most browsers) and navigate to the Network tab. Go to the cookbook app or reload if you are there already.
- Are there any requests with status 4xx or 5xx (first column)?
- There should be a request for `/app/cookbook/categories` (you can filter with the text above). What is its status? What is it's content (click on the request and on the right side you can navigate to _Answer_)?

Is there anything logged in `nextcloud.log` when you see the `Bad Signatue` issue? Or is this no longer shown?

Can you please temporarily enable debug mode by adding `"debug' => true,` to your `config.php`?
Did you modify anything in the database or the file system of the Nextcloud server or the cookbook app manually?

**Comment by iluvatyr** [comment]
The Nextcloud integrity check gives me following also now:

My cookbook was working and is working still for already a long time. Didnt change anything.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- cookbook
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [cookbook] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

**Comment by wildernessfamily** [comment]
Hi @christianlupus 

- Right now, I have the recipes in the '/My Family Recipes' which is a shared folder for the group 'Family'. The group has full permissions for the folder.

![Screen Shot 2022-06-29 at 10 12 27](https://user-images.githubusercontent.com/84930441/176487733-1f4c4a36-ed95-4d1f-b508-6a6ee8341952.jpg)

![Screen Shot 2022-06-29 at 10 14 16](https://user-images.githubusercontent.com/84930441/176487926-c2e768dd-a057-4b34-be32-1d61b2bff013.jpg)

- There are only four recipes. I was just testing and found it to be an awesome plugin. Thank you for your time in creating such an awesome plugin.

![Screen Shot 2022-06-29 at 10 15 27](https://user-images.githubusercontent.com/84930441/176488070-bab226f6-394e-4c34-9c29-bf938d58d266.jpg)

- Yes, each folder has a recipe.json file. I opened each .json file it does contain the correct info and is formatted correctly. Each folder has a single .json.

![Screen Shot 2022-06-29 at 10 17 02](https://user-images.githubusercontent.com/84930441/176488232-1dd968d5-c488-441b-ad55-286e9fc9d886.jpg)

![Screen Shot 2022-06-29 at 10 17 26](https://user-images.githubusercontent.com/84930441/176488797-d0e9515f-9265-4c26-9b59-f5363313e644.jpg)

- I use Firefox. All requests have a 200.
- categories also have a 200

![Screen Shot 2022-06-29 at 10 24 32](https://user-images.githubusercontent.com/84930441/176488551-3b212ffc-7501-47a6-9918-f377c610e165.jpg)

- For the next question, I'm not quite sure what you are asking for regarding 'Answer'. In the API call are you asking what the response is? If yes, it shows the category count as 0.

![Screen Shot 2022-06-29 at 10 35 55](https://user-images.githubusercontent.com/84930441/176489853-4f951e40-9d52-4431-b456-1b561837285b.jpg)


- I enabled Debug but got nothing.
- Unfortunately, 'Bad Signature' is no longer showing and there is no log entry.
- I did not modify anything in the database or file system of the NextCloud server or the cookbook app manually.

***Notes:**
- Couple of things I did try. I've been programming in Python KIVY a lot lately. However, I had a quick project and used PythonSimpleGUI and found that it doesn't like emojis. I did try removing the emoji from the folder name 'Mom's Apple Crisp' but that did not work.
- When I click 'Rescan library' a small popup is shown that states 'Failed To Fetch Categories' but if you blink you will not see it. It's that fast.

Thank you for your time and your time in helping solve the problem and of course the great extension to NextCloud :)

**Comment by christianlupus** [comment]
@iluvatyr your system is running again, right? So, you cannot provide more details. If that happens again (_Bad Signature_ error message), please report back immediately. We might be able to track down the problem eventually. I would be interested in the root cause of the message.

**Comment by iluvatyr** [comment]
> @iluvatyr your system is running again, right? So, you cannot provide more details. If that happens again (_Bad Signature_ error message), please report back immediately. We might be able to track down the problem eventually. I would be interested in the root cause of the message.

Yes, I updaded nextcloud and the issue was gone again. Will report if it ever comes again. My cookbook was accessible despite it showing the signature error within the nextcloud tab,

**Comment by wildernessfamily** [comment]
Hi @christianlupus 
First, please do not apologize for the inconvenience. This is an open-source extension. I code many open-source extensions as a hobby and so many people criticize if you don't respond immediately or if something goes wrong; Forgetting that it's free and they are not paying for it. You have put in a lot of time and work and I just appreciate having such a fantastic extension in the open-source community. Thank you for that!

It was the database. As soon as I cleared the categories table it all started working. :)

I've created multiple recipes with no problems. I created a test account to make sure the folder is accessible to all in the group and had no problems.

Thank you again for your time on helping me with this. And again, thank you for an awesome extension! :)
