### ISSUE TITLE
Create an app configuration

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1067]
Currently, our app is configured in a small overlay in the lower-left corner of the screen.

As more and more requests related to configurable enhancements are on the bug tracker, it might be a considerable approach to put the settings into a full-frame page. This can be done in different ways:
- the per-user configuration and register with the NC core
- a custom setting page (overlay or similar) that can be made visible

In this issue, the usage of mobile devices should be made as an additional request: Any changes to the settings should be easily achievable also on a mobile screen with touch control.

**Comment by MarcelRobitaille** [comment]
To be clear, the current objective is to replace the settings overleay in the bottom left corner of the app with a modal similar to the Nextcloud Talk app? Can the same button that currently toggles the overleay be use to bring up the modal?

Here is a screenshot of that app's settings modal. Also visible is the "Talk settings" button that brings up this modal.

![image](https://user-images.githubusercontent.com/8503756/195821242-11acb099-6321-4c6e-a367-1e47376dd1f8.png)

**Comment by christianlupus** [comment]
Exactly, that was the idea behind it, @MarcelRobitaille.
