### ISSUE TITLE
Too long title caused internal server error (SQL-error)

### ISSUE THREAD

**Issue by Basta911** [nextcloud/cookbook#1069]
Hi fellows,

**Setup:**
- Nextcloud 21.0.9 running on a RaspberryPi 4
- "Cookbook" App v.0.9.12
- "Nextcloud Cookbook" (by @Teifun2 ) Android App

**Issue:**
One of my users added some recipes with the "download from url" feature to his cookbook instance via the Android App (A-App) by "taifun2". At some point, he received an error message in the A-App. We tried to disconnect and reconnect, but the A-App did not connect any more. Also accessing the recipes with the Nextcloud-App (NC-App) was leading to an "internal server error" message.
The app still worked smooth for other users (both in NC-App and Android).

**Temporary Solution:**
We checked the Nextcloud error log and found the following error message:
`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column`
Quickly, @christianlupus indicated that a recipe title should be too long.

Therefore, I accessed the "recipe" folder with the NC-Files app and had a look at all the recipes.
I was able to identify the troublemaker - a folder with a veeery long name (thank you, chefkoch.de).
So I changed the title in the .json file (using the Nextcloud text editor), as solely renaming the folder had no effect.
This fortunately solved the problem immediately and the user was able to use his Cookbook again on NC-App and Android!

Therefor, dear users - always be careful with Importing recipes and tidy-up the tile.
Very big thanks to @christianlupus  and @Teifun2 for their great and helpful assistance!

**Comment by christianlupus** [comment]
Hello @Basta911. I just stumbled upon this issue. I guess it is solved in the meantime as there is a check on the size of the recipe length and an upper boundary of 256 chars should prevent this sort of problem.

Do you by chance still know the recipe URL, so I can try and see if the problem persists?

I will close it here but if it reappears or we can still confirm it, it can obviously be reopened.
