### ISSUE TITLE
Extract event bus in separate module

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1079]
We are using currently the `$root` Vue component as an event bus.

We should create a new module in the app to abstract this behavior. In Vue 3 no event bus is possible anymore and an external library is suggested. This abstraction will make the migration much smoother.

**Comment by christianlupus** [comment]
This one will get more important soon, of the Vue version 3 is installed. This will potentially invalidate the Vue2-based buses and thus a son solution is needed.

**Comment by christianlupus** [comment]
See also https://v3-migration.vuejs.org/breaking-changes/events-api.html

**Comment by seyfeb** [comment]
I started this on a to-be-uploaded branch
