### ISSUE TITLE
A directory is not created for a recipe with quotation marks in title

### ISSUE THREAD

**Issue by markus-lorenz** [nextcloud/cookbook#1090]
**Description**
After saving a new recipe with quotation marks ("") in title, no folder will be created.

**Reproduction**
1. Make a new recipe, call it <My "test" recipe> (without <>)
2. save it
3. check if a folder is created; should not
4. Edit the title and delete the quotation marks
5. check again; a folder should be created

**Expected behavior**
A folder to the new recipe should always be created - even with quotation marks.

**Actual behavior**
The folder is not created nor is there any error-message stating this.

**Comment by christianlupus** [comment]
I just tested with the most recent version on my dev environment and with v0.9.13. Both versions can save a test recipe without any problem.

Unfortunately, you removed some information from the template. What versions are you running? What OS are you using?

What happens, when you save a badly formatted recipe? Are there any error messages reported back?
Please open the web developer tools (F12 in most browsers) before you try to reproduce the problem. In the web developer tools, go to the _Network_ tab. There, every connection is visible. Trigger the problem by saving the offending recipe. Keep an eye for requests that perform with a status (first column) 400 or larger. They represent errors. Please report back (screenshot of the dev tools might be helpful for communication).
If there is such an error, you can open the details by clicking on the request. Have a look at the response tab. Is there an error message visible?

**Comment by markus-lorenz** [comment]
I´m really sorry - had to laugh about myself.
I was looking instantly after creating the recipe

**Comment by christianlupus** [comment]
All right. Nice to hear we did not mess up everything 😄.

**Comment by markus-lorenz** [comment]
What is admin saying?
The problem often sits in front of,…? 😅

And btw you do a great job.
We use the cookbook a lot and are very happy about every little step it takes! Wish I could do programming to support and participate.
But I hope to do it in my way by reporting such quality issues like this one 😵‍💫.
