### ISSUE TITLE
Feature wanted: Shopping list

### ISSUE THREAD

**Issue by jgrete** [nextcloud/cookbook#11]
... just as a small addendum: Just let me print/mail/copy to "notes" a shopping list
Regards

**Comment by oligneisti** [comment]
My preffered version would be if Cookbook could export to Tasks.

**Comment by tobiasKaminsky** [comment]
I found https://github.com/woefe/ShoppingList.
My big idea is to use this and add NC support via Notes API.
So in this case it would be great to have copied then ingredients to a note.

**Comment by duesseldorferjung** [comment]
+1

**Comment by duesseldorferjung** [comment]
Exporting to tasks within nextcloud would be awesome. How can I support on this idea?

**Comment by mrzapp** [comment]
@jgrete @oligneisti @tobiasKaminsky @duesseldorferjung

This is my suggested approach:

Step 1: Create a shopping list as per @jgrete's suggestion  
Step 2: Add the option to save it as a note as per @tobiasKaminsky's suggestion
Step 3: Add the option to save it as a calendar task as per @oligneisti's suggestion

Is anyone here up for the development task? If so, please clone the latest `master` branch and have at it :)

If not, this request will probably remain on the back burner, as it's not much of a priority for most users.

**Comment by tobiasKaminsky** [comment]
While thinking about, and trying to extends an existing Android shopping app, I came to the conclusion to try to create a standalone shopping "server" app, so it is based on php.

Once I am at a good state, it will of course integrate cookbook :)

**Comment by soxhi8** [comment]
Is this actually Done? Can't find the function and later issues on the same topic are still open.

**Comment by seyfeb** [comment]
No, I don’t think so. afaik there is no such feature currently available. I suggest to discuss details in #460 to prevent duplicate discussion since this issue is still open.
