### ISSUE TITLE
Sorting toggles under titlebar if no keywords assigned

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/cookbook#1100]
**Description**
In the index of the app, without the keywords component (no recipes have any keywords), the small "ABC" and "V" buttons to change how items are ordered are partially hidden under the title bar.

**Reproduction**
1. Make sure no recipes have any keywords
2. Go to the main page of the app

**Expected behavior**
The buttons should be fully visible with some small margin from the top bar

**Actual behavior**
The buttons are partially hidden by the top bar

**Screenshots**
![image](https://user-images.githubusercontent.com/8503756/180595003-30a7b008-d080-422b-8114-e7ce3450bb7b.png)

If any recipes have a keyword, this is fixed:
![image](https://user-images.githubusercontent.com/8503756/180595022-afb1dff7-319b-4114-9165-7b56888feac9.png)

**Browser**
Reproduced in Firefox and Chromium

**Versions**
Nextcloud server version: 25.0.0 dev
Cookbook version: master branch (f299ecc6d48f109bfe4214e8fac5877d97afadfc)

**Comment by MarcelRobitaille** [comment]
The culprit seems to be absolute positioning. These buttons are inside `.kw-container` and positioned absolutely. Thus, the `.kw-container` can collapse below the height of these buttons. We should consider using flexbox

```css
.settings-buttons[data-v-5248f968] {
  position: absolute;
  right: 10px;
  bottom: -8px;
}
```

**Comment by christianlupus** [comment]
Why not hide the buttons when no keywords are present? As soon as keywords are imported/added/deteced Vue would show them again.

**Comment by christianlupus** [comment]
Uups, I oversaw the PR!
