### ISSUE TITLE
Split JS build artifacts into smaller sized chunks

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1109]
Currently, we have a big single chunk of 2MB or more. This should be broken into more using dynamic imports in order to speed up loading.

**Comment by MarcelRobitaille** [comment]
Is this a duplicate of #455 by any chance?

**Comment by christianlupus** [comment]
> Is this a duplicate of #455 by any chance?

Yes, you are right. I am not on my best ATM. I am cloning this one in favor of #455.
