### ISSUE TITLE
l10n: Understanding issue with "recipeYield"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/cookbook#1111]
Actually there are four strings at Transifex using the word `yield`.

> Using heuristics to parse the recipeYield field of recipe {name}.

> Using the highest number found in recipeYield string. Totally found: {num}

> Could not parse recipeYield field. Falling back to 1.

> Toggle if recipe yield field is present

What is recipe yield? What does it means?

**Comment by christianlupus** [comment]
Hello @rakekniven,
well, that would be roughly the number of servings. The messages you are referring to are from error logs if the parsing fails or behaves unintended.

The thing is the schema.org standard is not very clear, what exactly is to be saved here: https://schema.org/recipeYield

The last string, I would maybe replace with `number of servings`. Would that be fine?

Should I put quotes around the other terms to make sure it is the `recipeYield` field in the data structure I am referring to?

**Comment by christianlupus** [comment]
I pushed some changes in #1112. Are these texts better? (Please ignore the CSS updates.)
