### ISSUE TITLE
Categories wont load/Error displayed. All Recipes category works.

### ISSUE THREAD

**Issue by djcath** [nextcloud/cookbook#1183]
**Description**
Since latest update 0.9.14, Categories will not load shows error "Failed to load category Sweets recipes"
Recipes can still be accessed through the "All recipes" category.
Have attempted to change the category within recipe to try and re-create a new category, this also fails.
Recipe folder is shared with one other user, other user also experiences the same issue.
Recipe folder has been created by a Nextcloud Admin

**Reproduction**
1. Go to cookbook
2. Click on a category
3. See error

**Expected behavior**
Click on category and recipe's for that category should show without error.

**Actual behavior**
Click on category, nextcloud shows error and wont load recipes in that category

**Screenshots**
![image](https://user-images.githubusercontent.com/30638812/187565620-949bebd5-d25a-4c2c-9bce-75c851dff402.png)

**Browser**
All

**Versions**
Nextcloud server version: 23.0.3
Cookbook version: 0.9.14
Database system: PostgreSQL

**Comment by christianlupus** [comment]
I just checked and I cannot reproduce this on my dev machine.

---

Can you please help us to debug this?
1. Navigate to the main cookbook page (all recipes).
2. Open the browser logs (press `F12`). Then go to the network tab. Keep it open.
3. Open a category as described by you.

In the network tab, a request should be present that failed (returning in a status code >=400). If you click on it, you can see the details of the request. Can you please share the relevant information with us? That is the status code (I suspect 500) and the answer (in a subtab). Maybe we can track this problem down like this.

**Comment by JMGaljaard** [comment]
Currently, I am experiencing the same. The content of the response for me contains (status code 500):


```
"An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"r.date_created\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT \"r\".\"recipe_id\", \"r\".\"name\", \"r\".\"date_created\", \"r\"....\n                                            ^"
```

In addition, when using the `search` functionality under `domain.tld/settings/apps`, I get informed that `An error occurred while searching for Recipes.`. This happens regardless of the query/input I use.

![image](https://user-images.githubusercontent.com/9016618/187713572-a2b9c745-8941-4601-bd64-1656518c20da.png)


Looking at the logs, the following trace is displayed within the corresponding error.

**Comment by JoshuaPettus** [comment]
I have PostgreSQL as well and am experiencing the same issue.  Could that be it?

**Comment by meichthys** [comment]
Also on Postgres 🤷‍♂️
```
[no app in context] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "r.date_created" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "r"."recipe_id", "r"."name", "r"."date_created", "r"....
                                            ^ at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1780
    Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert()
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1719
    Doctrine\DBAL\Connection->handleDriverException()
 2. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1067
    Doctrine\DBAL\Connection->convertExceptionDuringQuery()
 3. /var/www/nextcloud/lib/private/DB/Connection.php line 261
    Doctrine\DBAL\Connection->executeQuery()
 4. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 345
    OC\DB\Connection->executeQuery()
 5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 281
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/nextcloud/apps/cookbook/lib/Db/RecipeDb.php line 373
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php line 706
    OCA\Cookbook\Db\RecipeDb->findRecipes()
 8. /var/www/nextcloud/apps/cookbook/lib/Search/Provider.php line 57
    OCA\Cookbook\Service\RecipeService->findRecipesInSearchIndex()
 9. /var/www/nextcloud/lib/private/Search/SearchComposer.php line 160
    OCA\Cookbook\Search\Provider->search()
10. /var/www/nextcloud/core/Controller/UnifiedSearchController.php line 115
    OC\Search\SearchComposer->search()
11. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OC\Core\Controller\UnifiedSearchController->search()
12. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
13. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
14. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
15. /var/www/nextcloud/ocs/v1.php line 62
    OC\Route\Router->match()
16. /var/www/nextcloud/ocs/v2.php line 23
    require_once("/var/www/nextcloud/ocs/v1.php")

GET /ocs/v2.php/search/providers/cookbook/search?term=.nome&from=%2Fapps%2Ffiles%2F%3Fdir%3D%2F%26view%3Drecent
from ip_address by user at 2022-08-31T15:52:43-04:00
```

**Comment by djcath** [comment]
> I just checked and I cannot reproduce this on my dev machine.
> 
> Can you please help us to debug this?
> 
> 1. Navigate to the main cookbook page (all recipes).
> 2. Open the browser logs (press `F12`). Then go to the network tab. Keep it open.
> 3. Open a category as described by you.
> 
> In the network tab, a request should be present that failed (returning in a status code >=400). If you click on it, you can see the details of the request. Can you please share the relevant information with us? That is the status code (I suspect 500) and the answer (in a subtab). Maybe we can track this problem down like this.

as requested,  status is 500 and preview tab shows the following as per other peoples logs above: 
"An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"r.date_created\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT \"r\".\"recipe_id\", \"r\".\"name\", \"r\".\"date_created\", \"r\"....\n

**Comment by christianlupus** [comment]
Thank you all. This is obviously an error with the backend. 

I will have to evaluate the reason this was not found by am automated test. The fix should be simple. But without the tests, i have no verification that the issue was really solved.

**Comment by Racailloux** [comment]
I got the same issue, but with a different database type : MySQL
In case of.

Same error : 500
"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'xxx-xxxxx-xxxxx.r.date_created' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

**Versions**
Nextcloud server version: 24.0.2
Cookbook version: 0.9.14
Database system: MySQL

**Comment by meichthys** [comment]
> I got the same issue, but with a different database type : MySQL
> 
> In case of.
> 
> 
> 
> Same error : 500
> 
> "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'xxx-xxxxx-xxxxx.r.date_created' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"
> 
> 
> 
> **Versions**
> 
> Nextcloud server version: 24.0.2
> 
> Cookbook version: 0.9.14
> 
> Database system: MySQL

This looks like a different error. You may want to file a new issue unless you are seeing "grouping error" in the log.

**Comment by Racailloux** [comment]
> 

Thanks for noticing this to me. I removed the option 'ONLY_FULL_GROUP_BY' from my MySQL configuration and this works back.

**Comment by christianlupus** [comment]
These two issues seem to be related (a bug in the DB code introduced in a recent change. Only PostgreSQL seems to be more strict while MySQL more forgiving in the default configuration. The changed setting brings the bug to the surface similar to PostgreSQL.

**Comment by nboehlke** [comment]
Experiencing the same issue since postgreSQL upgrade (12 to 14). Looking forward to v0.9.15! :+1:

**Comment by christianlupus** [comment]
May I ask you to check another thing that might also be broken?
Open a recipe with a tag associated. The list of tags is visible in the top row close to the recipe description. You can click on the tag name to see all recipes with that tag attached.
I suspect you will also get an error in this case if I am right.

**Comment by opiation** [comment]
I can confirm also getting the same error when displaying a list of recipes by tag:

```
An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "r.date_created" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT \"r\".\"recipe_id\", \"r\".\"name\", \"r\".\"date_created\", \"r\"....
```

Nextcloud server version: 23.0.4
Cookbook version: 0.9.14
PostgreSQL: 12.x
