### ISSUE TITLE
Can't import recipes anymore, libxml-error in logfile

### ISSUE THREAD

**Issue by dpaessler** [nextcloud/cookbook#1193]
**Description**
I don't know exactly when this issue started, but when I try to import a recipe I get a server error. 
This is independent of the website, happens for instance on chefkoch.de, kochbar.de and other sites. It is also independent of the browser, I tried both Chromium and Firefox. 

<details><summary>In the nextcloud.log file I see the following errors (it's in german, sorry):</summary>

```json
{
  "reqId": "YxMapQDuVnVVOW_Iml3ReAAAAFM",
  "level": 2,
  "time": "2022-09-03T11:13:10+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 68 trat 758 Mal beim Parsen von https://www.chefkoch.de/rezepte/423461133169537/Gewuerzgurken.html auf. Er trat zum ersten Mal in Zeile 2 und Spalte 17 auf: error parsing attribute name\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMapQDuVnVVOW_Iml3ReAAAAFM",
  "level": 2,
  "time": "2022-09-03T11:13:10+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 801 trat 372 Mal beim Parsen von https://www.chefkoch.de/rezepte/423461133169537/Gewuerzgurken.html auf. Er trat zum ersten Mal in Zeile 278 und Spalte 95 auf: Tag amp-state invalid\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMapQDuVnVVOW_Iml3ReAAAAFM",
  "level": 2,
  "time": "2022-09-03T11:13:10+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 76 trat 21 Mal beim Parsen von https://www.chefkoch.de/rezepte/423461133169537/Gewuerzgurken.html auf. Er trat zum ersten Mal in Zeile 488 und Spalte 189 auf: Unexpected end tag : amp-img\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMapQDuVnVVOW_Iml3ReAAAAFM",
  "level": 2,
  "time": "2022-09-03T11:13:10+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 23 trat 104 Mal beim Parsen von https://www.chefkoch.de/rezepte/423461133169537/Gewuerzgurken.html auf. Er trat zum ersten Mal in Zeile 723 und Spalte 117 auf: htmlParseEntityRef: expecting ';'\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMapQDuVnVVOW_Iml3ReAAAAFM",
  "level": 2,
  "time": "2022-09-03T11:13:10+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 42 trat 2 Mal beim Parsen von https://www.chefkoch.de/rezepte/423461133169537/Gewuerzgurken.html auf. Er trat zum ersten Mal in Zeile 3527 und Spalte 249 auf: Attribute id redefined\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMdRxatuoKRPIvB9EU1kAAAAA4",
  "level": 2,
  "time": "2022-09-03T11:24:23+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 68 trat 755 Mal beim Parsen von https://www.chefkoch.de/rezepte/1494131254397303/Snirtje.html auf. Er trat zum ersten Mal in Zeile 2 und Spalte 17 auf: error parsing attribute name\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMdRxatuoKRPIvB9EU1kAAAAA4",
  "level": 2,
  "time": "2022-09-03T11:24:23+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 801 trat 369 Mal beim Parsen von https://www.chefkoch.de/rezepte/1494131254397303/Snirtje.html auf. Er trat zum ersten Mal in Zeile 287 und Spalte 95 auf: Tag amp-state invalid\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMdRxatuoKRPIvB9EU1kAAAAA4",
  "level": 2,
  "time": "2022-09-03T11:24:23+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 76 trat 21 Mal beim Parsen von https://www.chefkoch.de/rezepte/1494131254397303/Snirtje.html auf. Er trat zum ersten Mal in Zeile 497 und Spalte 189 auf: Unexpected end tag : amp-img\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMdRxatuoKRPIvB9EU1kAAAAA4",
  "level": 2,
  "time": "2022-09-03T11:24:23+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 23 trat 104 Mal beim Parsen von https://www.chefkoch.de/rezepte/1494131254397303/Snirtje.html auf. Er trat zum ersten Mal in Zeile 732 und Spalte 117 auf: htmlParseEntityRef: expecting ';'\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
{
  "reqId": "YxMdRxatuoKRPIvB9EU1kAAAAA4",
  "level": 2,
  "time": "2022-09-03T11:24:23+02:00",
  "remoteAddr": "ip-address",
  "user": "username",
  "app": "cookbook",
  "method": "POST",
  "url": "/index.php/apps/cookbook/import",
  "message": "libxml: Fehler 42 trat 2 Mal beim Parsen von https://www.chefkoch.de/rezepte/1494131254397303/Snirtje.html auf. Er trat zum ersten Mal in Zeile 3546 und Spalte 249 auf: Attribute id redefined\n",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "version": "24.0.4.1",
  "data": {
    "app": "cookbook"
  }
}
```
</details>

**Reproduction**
1. paste URL into the URL field
2. press "Enter"
3. wait usually 3-4 minutes

**Expected behavior**
1. paste URL into the URL field
2. press "Enter"
3. wait usually 1-2 minutes
4. See recipe

**Actual behavior**
directory with the correct name is created in the recipe-directory, but it's empty. 
A popup shows up, that a server error occurred and the recipe is not visible.
When I try to repeat the import, a popup shows up, that a recipe with that name already exists.

**Browser**
Chromium 105.0.5195.37 

**Versions**
Gentoo Linux, kernel 5.19.6
Nextcloud server version: 24.0.4
Cookbook version: 0.9.14
Database system: MariaDB 10.6.8
PHP version: 8.1.9
libxml version: 2.10.2

**Comment by christianlupus** [comment]
The messages are there just for reference. The libxml is quite strict and triggered formal errors even though one can cope with them (#344). These messages are _sort of_ normal, thus they should be warnings only. They will most probably not cause the import to fail.

---

> directory with the correct name is created in the recipe-directory, but it's empty. [...] When I try to repeat the import, a popup shows up, that a recipe with that name already exists.

The second part is a feature not a bug :smile:. It prevents you from overwriting existing recipes. So, the (empty) folder is correctly detected and importing the same recipe is blocked.

The fact that the recipe was empty in the first round however is not intended (obviously).

---

In a quick test, the import of a random recipe succeeded here (with 0.9.15-rc1). This is mainly the same as 0.9.14 except for some API differences. I have to look through the bug messages once moreor we will have to track that problem down.

**Comment by dpaessler** [comment]
Let me know, if and how I can help by providing additional informations.

**Comment by dpaessler** [comment]
Just updated nextcloud to 24.0.5 and cookbook to 0.9.15.
The error still remains.

**Comment by dpaessler** [comment]
I don't know if this is related. I just opened the cookbook android app and get a warning complaining about the API-version of the server. Translated from German:

"the API-version of the server has been updated.
some features may not work as expected. please wait for an update
1.0"

**Comment by christianlupus** [comment]
> I don't know if this is related. I just opened the cookbook android app and get a warning complaining about the API-version of the server. Translated from German: [...]

You can stick with German :smirk:.
The new API version was updated with 0.9.15. This is just a problem with the Android app.

---

Are you really waiting **minutes** for the recipe to appear? I suspect a few seconds are okay but minutes seem to me like _a bit_ too much!

Do you know how to use the developer tools of your browser? If yes, can you have a look at the network tab and see if there is an answer with status code 500 returned upon the import request?

PS: The stale bot is only to keep my attention on this issue :smile:.

**Comment by dpaessler** [comment]
Actually I get a 502 proxy error. 
There is an apache reverse proxy on a raspberry configured here, so maybe that's the problem.
This is in the logfile I get from developer tools:

`cookbook-main.js?v=986b35e1-11:2          POST https://cloud.domain.com/index.php/apps/cookbook/webapp/import 502 (Proxy Error)
(anonym) @ cookbook-main.js?v=986b35e1-11:2
e.exports @ cookbook-main.js?v=986b35e1-11:2
e.exports @ cookbook-main.js?v=986b35e1-11:2
d.request @ cookbook-main.js?v=986b35e1-11:2
(anonym) @ cookbook-main.js?v=986b35e1-11:2
import @ cookbook-main.js?v=986b35e1-11:2
downloadRecipe @ cookbook-main.js?v=986b35e1-11:2
Ft @ cookbook-main.js?v=986b35e1-11:2
n @ cookbook-main.js?v=986b35e1-11:2
Ft @ cookbook-main.js?v=986b35e1-11:2
e.$emit @ cookbook-main.js?v=986b35e1-11:2
onSubmit @ cookbook-main.js?v=986b35e1-11:2
submit @ cookbook-main.js?v=986b35e1-11:2
Ft @ cookbook-main.js?v=986b35e1-11:2
n @ cookbook-main.js?v=986b35e1-11:2
Qr.a._wrapper @ cookbook-main.js?v=986b35e1-11:2
cookbook-main.js?v=986b35e1-11:2 i {message: 'Request failed with status code 502', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_RESPONSE"config: adapter: ƒ (e)length: 1name: ""prototype: constructor: ƒ (e)length: 1name: ""prototype: constructor: ƒ (e)length: 1name: ""prototype: constructor: ƒ (e)length: 1name: ""prototype: constructor: ƒ (e)[[Prototype]]: Objectarguments: (...)caller: (...)[[FunctionLocation]]: cookbook-main.js?v=986b35e1-11:2[[Prototype]]: ƒ ()[[Scopes]]: Scopes[3][[Prototype]]: Objectarguments: (...)caller: (...)[[FunctionLocation]]: cookbook-main.js?v=986b35e1-11:2[[Prototype]]: ƒ ()[[Scopes]]: Scopes[3][[Prototype]]: Objectarguments: (...)caller: (...)[[FunctionLocation]]: cookbook-main.js?v=986b35e1-11:2[[Prototype]]: ƒ ()[[Scopes]]: Scopes[3][[Prototype]]: Objectarguments: (...)caller: (...)[[FunctionLocation]]: cookbook-main.js?v=986b35e1-11:2[[Prototype]]: ƒ ()[[Scopes]]: Scopes[3]data: "url=https://www.chefkoch.de/rezepte/1472341252147284/Gesunde-lockere-Bouletten-mit-Quark.html"env: {FormData: null}headers: {Accept: 'application/json, text/plain, */*', Content-Type: 'application/x-www-form-urlencoded', requesttoken: 'Y1EvF44mxXrqOi/b24D43lwH56dL2FMpWZ1z7jnma7U=:Mh8eVr1+oBi4QmydnNihnyRXvc0liwJsDugipRa+I/w='}maxBodyLength: -1maxContentLength: -1method: "post"timeout: 0transformRequest: [ƒ]transformResponse: [ƒ]transitional: {silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}url: "/index.php/apps/cookbook/webapp/import"validateStatus: ƒ (e)xsrfCookieName: "XSRF-TOKEN"xsrfHeaderName: "X-XSRF-TOKEN"[[Prototype]]: Objectmessage: "Request failed with status code 502"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}response: {data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">…d.domain.com Port 443</address>\n</body></html>\n', status: 502, statusText: 'Proxy Error', headers: {…}, config: {…}, …}[[Prototype]]: Error
(anonym) @ cookbook-main.js?v=986b35e1-11:2
Promise.catch (async)
downloadRecipe @ cookbook-main.js?v=986b35e1-11:2
Ft @ cookbook-main.js?v=986b35e1-11:2
n @ cookbook-main.js?v=986b35e1-11:2
Ft @ cookbook-main.js?v=986b35e1-11:2
e.$emit @ cookbook-main.js?v=986b35e1-11:2
onSubmit @ cookbook-main.js?v=986b35e1-11:2
submit @ cookbook-main.js?v=986b35e1-11:2
Ft @ cookbook-main.js?v=986b35e1-11:2
n @ cookbook-main.js?v=986b35e1-11:2
Qr.a._wrapper @ cookbook-main.js?v=986b35e1-11:2
index.js:323 OC.requestToken changed cCBwMfsB0Jr7FHv31JxjRw7zFlZ8062P4gvzB46oVi0=:IW5BcMhZtfipbDixk8Q6BnajTDwSgPzKtX6iTKHwHmQ=`

**Comment by dpaessler** [comment]
I'm not using PHP-FPM, just the apache handler. No forward proxy is configured or used.

In the apache log on the reverse proxy I get the following error, where 192.168.2.1 is the Internet router:

`[Sat Oct 01 07:32:31.028543 2022] [proxy:error] [pid 28045] [client 192.168.2.1:39930] AH00898: Error reading from remote server returned by /index.php/apps/cookbook/webapp/import
`
My NC server is running in a dedicated path, but is redirected with the apache ProxyPass directive to be accessed without (where 192.168.2.10 is my NC server):

`ProxyPass / http://192.168.2.10/nextcloud/
 ProxyPassReverse / http://192.168.2.10/nextcloud/`

Everything else works fine, "Security and setup warnings" shows no warning or error, Security Scan result is A+. 
The cookbook import did work before without any change to the setup here.

In the network tab I get the following errors (not translated):

`Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für https://cloud.domain.com/apps/cookbook/js/cookbook-main.js.map?v=16f7d386733aeee611f3: Ladevorgang wegen Zeitüberschreitung abgebrochen konnte nicht geladen werden
cookbook-main.js?v=1610399f-11:2          POST https://cloud.domain.com/index.php/apps/cookbook/webapp/import 502 (Proxy Error)
(anonym) @ cookbook-main.js?v=1610399f-11:2
e.exports @ cookbook-main.js?v=1610399f-11:2
e.exports @ cookbook-main.js?v=1610399f-11:2
d.request @ cookbook-main.js?v=1610399f-11:2
(anonym) @ cookbook-main.js?v=1610399f-11:2
import @ cookbook-main.js?v=1610399f-11:2
downloadRecipe @ cookbook-main.js?v=1610399f-11:2
Ft @ cookbook-main.js?v=1610399f-11:2
n @ cookbook-main.js?v=1610399f-11:2
Ft @ cookbook-main.js?v=1610399f-11:2
e.$emit @ cookbook-main.js?v=1610399f-11:2
onSubmit @ cookbook-main.js?v=1610399f-11:2
submit @ cookbook-main.js?v=1610399f-11:2
Ft @ cookbook-main.js?v=1610399f-11:2
n @ cookbook-main.js?v=1610399f-11:2
Qr.a._wrapper @ cookbook-main.js?v=1610399f-11:2
cookbook-main.js?v=1610399f-11:2 i {message: 'Request failed with status code 502', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_RESPONSE"config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}message: "Request failed with status code 502"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}response: {data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">…d.domain.com Port 443</address>\n</body></html>\n', status: 502, statusText: 'Proxy Error', headers: {…}, config: {…}, …}[[Prototype]]: Error
(anonym) @ cookbook-main.js?v=1610399f-11:2
Promise.catch (async)
downloadRecipe @ cookbook-main.js?v=1610399f-11:2
Ft @ cookbook-main.js?v=1610399f-11:2
n @ cookbook-main.js?v=1610399f-11:2
Ft @ cookbook-main.js?v=1610399f-11:2
e.$emit @ cookbook-main.js?v=1610399f-11:2
onSubmit @ cookbook-main.js?v=1610399f-11:2
submit @ cookbook-main.js?v=1610399f-11:2
Ft @ cookbook-main.js?v=1610399f-11:2
n @ cookbook-main.js?v=1610399f-11:2
Qr.a._wrapper @ cookbook-main.js?v=1610399f-11:2
`

**Comment by christianlupus** [comment]
Can you access http://192.168.2.10/nextcloud/ from your local machine? Eventually, you need to allow connections from the local network in the server's `config.php`. If yes, please have a try with the problem and see if this allows to extract more information about the problem.

Are you really waiting for minutes?

Can you access the API with curl from the rpi (if you need support to test that, just give me a ping)?

**Comment by dpaessler** [comment]
Yes, I can access http://192.168.2.10/nextcloud from my local machine, ending up on https://cloud.domain.com, presumably caused by these directives in my config.php (192.168.2.81 is my reverse proxy):

`'trusted_proxies' => 
  array (
    0 => '192.168.2.81',
  ),
  'overwritehost' => 'cloud.domain.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/',
  'overwritecondaddr' => '^192\\.168\\.2\\.81$',
`

I just startet a stop watch and ended up waiting more than 4 minutes until the error message appears.

Yes, I can access the API from my proxy:

`curl -u username:192.168.2.10 -X GET 'http://192.168.2.10/nextcloud/ocs/v1.php/cloud/capabilities' --header "OCS-APIRequest: true"
`
returns:

`<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <version>
   <major>24</major>
   <minor>0</minor>
   <micro>6</micro>
   <string>24.0.6</string>
   <edition></edition>
   <extendedSupport></extendedSupport>
  </version>
  <capabilities>
   <bruteforce>
    <delay>0</delay>
   </bruteforce>
   <metadataAvailable>
    <size>
     <element>/image\/.*/</element>
    </size>
   </metadataAvailable>
   <theming>
    <name>black cloud</name>
    <url>https://cloud.domain.com</url>
    <slogan>meine daten, meine regeln!</slogan>
    <color>#000000</color>
    <color-text>#ffffff</color-text>
    <color-element>#000000</color-element>
    <color-element-bright>#000000</color-element-bright>
    <color-element-dark>#555555</color-element-dark>
    <logo>https://cloud.domain.com/index.php/apps/theming/image/logo?useSvg=1&amp;v=11</logo>
    <background>https://cloud.domain.com/index.php/apps/theming/image/background?v=11</background>
    <background-plain></background-plain>
    <background-default></background-default>
    <logoheader>https://cloud.domain.com/index.php/apps/theming/image/logo?useSvg=1&amp;v=11</logoheader>
    <favicon>https://cloud.domain.com/index.php/apps/theming/image/logo?useSvg=1&amp;v=11</favicon>
   </theming>
  </capabilities>
 </data>
</ocs>
`

**Comment by dpaessler** [comment]
I just discovered another thing:
I tried to create a new recipe instead of importing one and this also throws the server error. 
So it's not only a problem with import but generally with the creation of recipes.

**Comment by christianlupus** [comment]
OK, let's start with something related to cookbook:

If you type
```
curl -u user:pwd --basic http://192.168.2.10/nextcloud/apps/cookbook/api/v1/recipes | jq
```
you should get a list of all your recipes (you can omit the part `| jq` if you do not have that installed, just to make the output nicer to read).

Now, let's create a recipe with curl:
```
curl -u user:pwd --basic -X POST -H 'Content-Type: application/json' -d '{"name":"Test by CURL"}' http://192.168.2.10/nextcloud/apps/cookbook/api/v1/recipes -v; echo
```

Please remember the number printed out in the last line if you wanted to remove the recipe again using curl.

Does this work? How long does it take approx (mere seconds or minutes)?

Do you have already some recipes in your database, yet?

**Comment by dpaessler** [comment]
> OK, let's start with something related to cookbook:
> 
> If you type
> 
> ```
> curl -u user:pwd --basic http://192.168.2.10/nextcloud/apps/cookbook/api/v1/recipes | jq
> ```
> 
> you should get a list of all your recipes (you can omit the part `| jq` if you do not have that installed, just to make the output nicer to read).
> 

This doesn't work. I get this:

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
<hr>
<address>Apache Server at 192.168.2.10 Port 80</address>
</body></html>`


and this one in access_log on the nextcloud server:

`192.168.2.81 - - [12/Nov/2022:08:45:54 +0100] "GET /nextcloud/apps/cookbook/api/v1/recipes HTTP/1.1" 403 -`

> Does this work? How long does it take approx (mere seconds or minutes)?
>

The error appears immediately.
 
> Do you have already some recipes in your database, yet?

Yes, I imported recipes earlier. There are about 60 recipes in my database.

**Comment by christianlupus** [comment]
I suspect there was nothing logged in the Nextcloud logs, right? Are you sure your credentials are correct? Can you please check if the URL prefix (host, port, installation path) are correct?

Normally you are forwarded with 302 if the route is wrong.

You are not by chance using the 192.168.2.81 machine for your tests, are you?

**Comment by dpaessler** [comment]
> I suspect there was nothing logged in the Nextcloud logs, right? Are you sure your credentials are correct? Can you please check if the URL prefix (host, port, installation path) are correct?

Yes, the credentials are correct and nothing ist logged. The URL prefix is also correct.
I get access when using curl with a regular file, e.g. :

`curl http://192.168.2.10/nextcloud/apps/cookbook/LICENSE`

so it seems that just the API is not working..

I also tried the following (note the additional index.php in the URL):

`curl -u user:pwd --basic http://192.168.2.10/nextcloud/index.php/apps/cookbook/api/v1/recipes`

which leads to the following output:

`{"message":"Password login forbidden, use token instead"}`

This probably comes from the Two-Factor WebAuthn app I have installed. May the use of this app be related to the problem?

> 
> Normally you are forwarded with 302 if the route is wrong.
> 
> You are not by chance using the 192.168.2.81 machine for your tests, are you?

The nextclod server runs on a notebook, which is also my workstation. I tried accessing the API from both my workstation/nextcloud server and from the reverse proxy (192.168.2.81), with the same result.

**Comment by christianlupus** [comment]
Once a 2FA app is active for the user, all API requests are only possible using tokens. Otherwise, one could circumvent the 2FA. The token is somewhat equivalent to the password + second factor.

For the original problem, it is not related as the auth is handled in the main Nextcloud frontend code and not within the cookbook app. But our test requests are rejected due to the 2FA configuration. The simplest way is to go to the settings, create a token and use that instead of your password. That should get you past that point.

**Comment by dpaessler** [comment]
Can you please give me a hint how to use a token with the curl request?

**Comment by christianlupus** [comment]
Ahh, sorry, I oversaw your post.
Just use it as a password. So like 
```
curl -u user:KJGklghKHG8765...
```

**Comment by christianlupus** [comment]
OK, this sounds like a problem with the server installation, to be precise with the rewrite base configuration. See e.g. [this forum entry](https://help.nextcloud.com/t/update-19-0-1-htaccess-rewritebase-and-occ-maintenancehtaccess/87524) and [the documentation](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations)
