### ISSUE TITLE
Import from frischgekocht.billa.at fails with non-descriptive error.

### ISSUE THREAD

**Issue by MacLemon** [nextcloud/cookbook#1209]
**Failing website:**

**Checking if valid metadata are present:**
- [x] Yes, I check the source code of the website and found metadata.
  - Source contains `<article class='recipe is-new' itemscope itemtype="http://schema.org/Recipe">`

**Cookbook version:**
- Cookbook  Version 0.9.15

**Problem description (if applicable):**

# Summary:
Importing from https://frischgekocht.billa.at/ fails with error.

## Steps to Reproduce:
1. Navigate to Cookbook on your instance. `/apps/cookbook/`
1. Focus the “Download recipe from URL” field
1. Paste this recipe URL: https://frischgekocht.billa.at/rezept/kuerbis-erdaepfel-gulasch-mit-debreziner-BI-28065
1. Error is displayed

## Expected Results:
Recipe should be imported into my collection.

## Actual Results:
1. Nextcloud/Cookbook reports an error dialog with “The server reported an error. Please check.”.

The browser Log shows this info:

```
POST https://blackmoor.maclemon.at/apps/cookbook/webapp/import 500
(anonymous) @ xhr.js:220
e.exports @ xhr.js:16
e.exports @ dispatchRequest.js:56
d.request @ Axios.js:109
(anonymous) @ bind.js:9
import @ api-interface.js:48
downloadRecipe @ AppNavi.vue:271
Ft @ vue.runtime.esm.js:2987
n @ vue.runtime.esm.js:1785
Ft @ vue.runtime.esm.js:2987
e.$emit @ vue.runtime.esm.js:3685
onSubmit @ ActionInput.js:2
submit @ ActionInput.js:2
Ft @ vue.runtime.esm.js:2987
n @ vue.runtime.esm.js:1785
Qr.a._wrapper @ vue.runtime.esm.js:7428
AppNavi.vue:301 i {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_RESPONSE"config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}message: "Request failed with status code 500"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}response: {data: '<!DOCTYPE html>\n<html class="ng-csp" data-placehol…y policy</a>\t\t\t</p>\n\t\t</footer>\n\t</body>\n</html>\n', status: 500, statusText: '', headers: {…}, config: {…}, …}[[Prototype]]: Error
```

## Regression:
I've successfully imported other recipes from other websites, so the general function works fine.

## Notes:
I haven't yet cooked this recipe, so I cannot attest to its tastyness.   
The problem is reproducible on at least one other Nextcloud 24 instance, so I guess it's not a problem of my specific instance.

## Version Information:
- Nextcloud 24.0.5
- Cookbook  0.9.15
- `php` 7.4.30

### Browsers tested
- Firefox 104.0.0
- Firefox Developer Edition 105
- Vivaldi (Chromium/Blink based) 5.4.2753.47
- Google Chrome 105.0.5195.125

On Operating systems:
- macOS Monterey 12.5, 12.5.1, 12.6
- Fedora Linux (dunno the exact version, but that person's system is usually pretty well up-to-date)

Since I assume this is a server side problem I think the browser is irrelevant to the issue.

**Comment by Benedikt81** [comment]
Error can be reproced. Error message looks like this:
![image](https://user-images.githubusercontent.com/5584309/190958359-a4e92705-dc15-481e-853a-d398d7dd5cf1.png)

[Nextcloud](https://nextcloud.com/) 24.0.5
Cookbook	0.9.15
PHP: 7.4.3

Browser: Vivaldi 5.4.2753.51
Server OS: Betriebssystem: Linux 5.4.0-121-generic x86_64 (Ubuntu 20.04)

**Comment by christianlupus** [comment]
I was able to reproduce this. The NC server core reports an error in the browser logs:

## Technical details

```
    Remote Address: 192.168.64.1
    Request ID: llng2x5hEiI82Awn2Ajj
    Type: Exception
    Code: 0
    Message: OCA\Cookbook\Helper\TextCleanupHelper::cleanUp(): Argument #1 ($str) must be of type ?string, array given, called in /var/www/html/custom_apps/cookbook/lib/Helper/Filter/JSON/RecipeNameFilter.php on line 26 in file '/var/www/html/custom_apps/cookbook/lib/Helper/TextCleanupHelper.php' line 14
    File: /var/www/html/lib/private/AppFramework/Http/Dispatcher.php
    Line: 165
```

## Trace
```
#0 /var/www/html/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Cookbook\Controller\RecipeController), 'import')
#1 /var/www/html/lib/private/Route/Router.php(298): OC\AppFramework\App::main('OCA\\Cookbook\\Co...', 'import', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#2 /var/www/html/lib/base.php(1023): OC\Route\Router->match('/apps/cookbook/...')
#3 /var/www/html/index.php(36): OC::handleRequest()
#4 {main}
```

## Previous
```
#0 /var/www/html/custom_apps/cookbook/lib/Helper/Filter/JSON/RecipeNameFilter.php(26): OCA\Cookbook\Helper\TextCleanupHelper->cleanUp(Array, true, true)
#1 /var/www/html/custom_apps/cookbook/lib/Helper/Filter/JSONFilter.php(60): OCA\Cookbook\Helper\Filter\JSON\RecipeNameFilter->apply(Array)
#2 /var/www/html/custom_apps/cookbook/lib/Service/RecipeService.php(177): OCA\Cookbook\Helper\Filter\JSONFilter->apply(Array)
#3 /var/www/html/custom_apps/cookbook/lib/Service/RecipeService.php(541): OCA\Cookbook\Service\RecipeService->checkRecipe(Array)
#4 /var/www/html/custom_apps/cookbook/lib/Controller/Implementation/RecipeImplementation.php(222): OCA\Cookbook\Service\RecipeService->downloadRecipe('https://frischg...')
#5 /var/www/html/custom_apps/cookbook/lib/Controller/RecipeController.php(85): OCA\Cookbook\Controller\Implementation\RecipeImplementation->import()
#6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\Cookbook\Controller\RecipeController->import()
#7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Cookbook\Controller\RecipeController), 'import')
#8 /var/www/html/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Cookbook\Controller\RecipeController), 'import')
#9 /var/www/html/lib/private/Route/Router.php(298): OC\AppFramework\App::main('OCA\\Cookbook\\Co...', 'import', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#10 /var/www/html/lib/base.php(1023): OC\Route\Router->match('/apps/cookbook/...')
#11 /var/www/html/index.php(36): OC::handleRequest()
#12 {main}
```

**Comment by christianlupus** [comment]
The problem is located in the [microdata parser](https://github.com/nextcloud/cookbook/blob/master/lib/Helper/HTMLParser/HttpMicrodataParser.php). The parser interprets the breadcrumbs' names as names of the recipes. Thus, multiple names are returned and the filter later on fails.

![Debug steps](https://user-images.githubusercontent.com/8202922/190965068-60c6d787-bf23-4878-8112-c8747d456914.png)

![DOM tree](https://user-images.githubusercontent.com/8202922/190965254-c6b3dffd-1035-48a5-9c30-0cc4c42f93d7.png)
