### ISSUE TITLE
Installing Cookbook on 24.0.5 breaks "Files" on Webui

### ISSUE THREAD

**Issue by roadkingvrod** [nextcloud/cookbook#1214]
**Description**
Installing cookbook causes the "files" web app to not show any folders.  They were immediately available before, and not visible after.  Sync clients on android and windows still sync and show files.

**Reproduction**
1. Look at Files without cookbook installed.
2. Install cookbook
3. Look at files and it's empty

**Expected behavior**
It shouldn't affect files at all
**Actual behavior**
it does.
**Screenshots**

**Browser**
chrome, edge, firefox

**Versions**
Nextcloud server version: 24.0.5 
Cookbook version: app store version

**Comment by roadkingvrod** [comment]
Thank you for responding.  I did some more playing around and while it appeared tied to cookbook, it actually wasn't.  I just happened to do it twice in a row.  Closing the ticket. Thanks again and sorry for the misreport.

**Comment by christianlupus** [comment]
Thanks for reporting back. No problem.
