### ISSUE TITLE
Cant veiw imported recipes 

### ISSUE THREAD

**Issue by critterskins** [nextcloud/cookbook#1221]
Cannot view imported recipes on app works fine within nextcloud itself.

**Comment by critterskins** [comment]
![Screenshot_20220922-143601](https://user-images.githubusercontent.com/22518657/191856661-9845ea33-4947-44f0-a983-0884978ca791.jpg)

**Comment by christianlupus** [comment]
This issue is invalid for multiple reasons. 

- by far not all information are provided. I do not understand the problem. 
- the problem is related to a 3rd party mobile app.

Closing therefore.

**Comment by critterskins** [comment]
> 

Sorry I thought I was contacting the mobile app developer not the nextcloud app dev.

**Comment by christianlupus** [comment]
I hope you find the appropriate developer soon.
