### ISSUE TITLE
keywords usability

### ISSUE THREAD

**Issue by Joe-ncB** [nextcloud/cookbook#1234]
**Is your feature request related to a problem? Please describe.**
auto update keywords
as there is no extra space for ingredients

**Describe the solution you'd like**
a big advantage would be to import the ingredients to the keywords with one click
and by a mistaken one  to select that one to delete -- at the moment i can only delete from the end to begin
even it is stored as a string i can not place the cursor
so in worst case i have to insert all again (exept the first one)

**Describe alternatives you've considered**

intermediate/additional solution is to enhance the search button
like dragndrop some keywords
so i can filter for ingredients i have in the fridge

**Comment by seyfeb** [comment]
> as there is no extra space for ingredients

What do you mean by this? There is an extra section for ingredients!

> a big advantage would be to import the ingredients to the keywords with one click

Can you explain a bit what is the use case for this functionality?

> and by a mistaken one to select that one to delete -- at the moment i can only delete from the end to begin

What do you mean with this? In the keyword multiselect popup you can (de)select any keyword in any order - no need for a certain order. If it better suits your approach, you could also edit the json file which is stored in the recipe directory.

> intermediate/additional solution is to enhance the search button

Which search button? In what way could it be improved?

> like dragndrop some keywords

Could you expand a bit on this?

> so i can filter for ingredients i have in the fridge

Is your idea to be able to limit the search functionality to recipes containing the search string in a certain section, like keywords, ingredients, tools, instructions, etc?

**Comment by Joe-ncB** [comment]
hi obviously i was not clear and precise at all -- i try again
sure there is a space for ingredients but i mean one like that at the top
like the line with the keywords. 
At the moment i mix in there pattern like easy, good, asian, dip, ... with pattern like chili, Tomatos, Rice, etc
in general this is no problem but with so many keys i might forget to insert something which might act as a good constraint.
so i mean - for me - it will be better to have 2 of those spaces one keywords-general and one keywords-ingredients
so i can search for eg rice, onion, tomatos,  all that stuff i find i my fridge
anyway it is only an idea -- if i am the only one there is no need for implementation

but what is really time-consuming in my workflow is that i have to insert all ingredients manually in the keyword area
so a click on a (not existing now) button to transfer all ingredients from the ingredients section to the keyword section would be nice (of cause without the quantity)

or am i missing something here like the delete function in the keyword area

it will be very kind if you can explain more detailed how to delete -- lets say the 3rd keyword out of 5
as i dont have a clue how to do this

with the search button (top right while viewing All recipe) i have to write manually what i am looking for
i guess its better for the flow and fail-safe to click on a list, maybe the keyword-list
to get a bunch of pattern to search for
as you guessed right -- to limit the search functionality to recipes containing the search string in a certain section

maybe i am dreaming but i started just a couple of days ago with the app
and everything is sufficient and everybody is happy the way it is

**Comment by christianlupus** [comment]
This might be referring to https://github.com/nextcloud/cookbook/discussions/1217#discussioncomment-3780020.

**Comment by christianlupus** [comment]
Related might be #135 and #178.

**Comment by seyfeb** [comment]
> so i mean - for me - it will be better to have 2 of those spaces one keywords-general and one keywords-ingredients

I don't think we should make such a special separation, especially with #135 in the talks. What _could_ be derived from this is the question if there is a need for hierarchical keywords, like `Ingredients > Cocoa`, `Diet > Vegetarian`, etc.

> it will be very kind if you can explain more detailed how to delete -- lets say the 3rd keyword out of 5
as i dont have a clue how to do this

Simply clicking on any of the keywords with a checkmark should remove it!

<img width="369" alt="Screenshot 2022-10-02 at 23 55 02" src="https://user-images.githubusercontent.com/7623143/193478021-07f21927-9a4b-495d-b27c-603a4202b141.png">

Are you looking for a __faster__ way to remove keywords, e.g., if there was a clickable delete (cross) button within the keyword? We are using the Nextcloud components to stick with the Nextcloud style, so if there was a need for that we could ask in the respective [github repository](https://github.com/nextcloud/nextcloud-vue).

**Comment by Joe-ncB** [comment]
yes you are so good -- better than me
#1235 thats me .. i mentioned it here because @christianlupus mentioned i should make a bug report or feature request and it was a dicussion i aplologize for duplicity

@seyfeb thanks for clarification. That is enough for me. It is just if i make a mistake (once in a while)

so i see you are hard working on these topics
i can wait for NC style 
looking forward the next updates

**Comment by christianlupus** [comment]
I just redirected into a new issue as I wanted to prevent hijacking the other discussion.

Some bugs/missing functions we are aware of. Some of these could be implemented in a simple way that is not _safe_ and that might cause regressions. So, I tend to create more robust structures but this takes some time and might not be the most obvious way.

Long story short: If you find something missing, it is good to give a (good) feature request, as precise as possible. It can easily be closed or marked as duplicate but an implicit request without explicitly formulating it in an issue can't be addressed.

**Comment by Joe-ncB** [comment]
clear enough
thank you
