### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by aszlig** [nextcloud/cookbook#125]
It's very hard to figure out what has changed between `cookbook` versions, given that there isn't even a summary of changes in the GitHub release notes, nor is there a dedicated `CHANGELOG.md`.

Can you please provide a CHANGELOG.md as documented in the [Nextcloud developer documentation](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog), so that not only people who find the repository see what's changed but they're actually shown in the app update UI.

Thank you in advance.

**Comment by mrzapp** [comment]
I agree, I'll start using the changelog when making releases

**Comment by IzzySoft** [comment]
> I'll start using the changelog when making releases

May I ask where that can be found? :smiley:

**Comment by christianlupus** [comment]
I fear there is no changelog in the past generated. I hope, I will think of it in the future.

**Comment by IzzySoft** [comment]
Thanks, looking forward to it then (might send another heads-up in a few months if you don't mind :wink:)

**Comment by christianlupus** [comment]
Yes, thank you.
For the record: See #353.

**Comment by IzzySoft** [comment]
Cool, thanks!

**Comment by christianlupus** [comment]
OK, I just worked on a PR (#366) to include a basic changelog in the repository. I intent to merge soon.

The thing is, the current changelog does not contain relevant parts of the history. This is manual and tendious work to document all changes of recent versions. For future changes a change in the `CHANGELOG.md` file is requested. However, old data is not so easily extracted. So the question: It it really needed for historical releases?

**Comment by IzzySoft** [comment]
@christianlupus depends on whom you ask. But I think there's no need to search for "ancient ones" and going back to v0.0.1 :rofl: Thanks for getting this started!

**Comment by christianlupus** [comment]
PRs are welcome here. It is mainly a think of going through the commit history from the repo and extracting the merged PRs. Most notably you can have a look at the corresponding PRs to get an idea what is going on. If anyone wants to have a shot on it and runs into issues, you are free to write. I'll try to help.
