### ISSUE TITLE
invalid Path, "|" is not allowed Error When Importing Recipe

### ISSUE THREAD

**Issue by Charli181** [nextcloud/cookbook#1259]
When I try to import a recipe from a particular site, I occasionally get the following Error popup and the recipe does not get imported.

Invalid request for Invalid path, "|" is not allowed (InvalidPathException)

1. In Download text box, enter - 'https://www.marionskitchen.com/chinese-pork-n-ginger-stir-fry/'
2. Click on the download arrow
3. Error message appears after a short period of time

**Expected behavior**
Hoping to have this site be supported for downloading of recipes if possible.

**Actual behavior**
Some recipes work, but others fail with this error. Other sites are working fine so it has to do with the particular page

**Browser**
Chrome 106.0.5249.119

**Versions**
Nextcloud server version: 24.0.6
Cookbook version: 0.9.15
Database system: mysql 10.3.34

**Comment by Charli181** [comment]
SOme further testing on this and I found that the pipe character | is in the name field is causing the issue. If I manually add the recipe and insert a | in the name field, I get another error "Unknown answer returned from server. See logs."

I remove the | and it saves.

Tested the page at schema .org and it returns no error for the type recipe, but does show that there is a | in the name field which I am assuming is the problem. Not sure if we can do some sort of replace function in the name field to swap the | with some other character or add support for the | somehow?

Regards
Sean

**Comment by christianlupus** [comment]
It would be nice to either have a clear error message (the following character is not allowed : |) or replace it with something sensible. 

May i ask you what operating system you are using on the server?

**Comment by Charli181** [comment]
Here is a snipet of my Server details. My NC server is virtualised with VMBOX using the following

Server configuration detail

Operating system: Linux 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64

Webserver: Apache/2.4.41 (Ubuntu) (fpm-fcgi)

Database: mysql 10.3.34

PHP version: 8.0.14

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 24.0.6 - 24.0.6.1

**Comment by christianlupus** [comment]
I was not able to reproduce the problem on my machine. I now added a filter that will remove the pipe chars `|`. I hope this will fix the problem.
