### ISSUE TITLE
Regression in Vue dialogs

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1262]
Merging of #1261 introduces a regression. The buttons are not assigned correctly. Can you check on the, @MarcelRobitaille?

To have a look just open a new recipe. Type something to trigger the changed recipe flag. Navigate somewhere else and you will see a message like this:
![grafik](https://user-images.githubusercontent.com/8202922/196506985-af3e570b-8e4f-4b37-896a-31070b680467.png)

When I click on OK, I am left with the window. When clicking on Cancel or the X in the right top corner, I will be following whatever link I clicked.

**Comment by MarcelRobitaille** [comment]
@christianlupus Sorry about that! It should be fixed in f93a3fe7

**Comment by christianlupus** [comment]
Fixed in the PR directly.
