### ISSUE TITLE
Frontend and API testing

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1265]
Currently, we do not have any frontend, API, or e2e tests. This should be done at some point

**Comment by MarcelRobitaille** [comment]
I agree. Having some tests would be great. I can work on some of them too.

**Comment by christianlupus** [comment]
I am currently (from Tuesday to today) participating in a workshop about that topic. There was some output from that so far. I also applied for a open source license of Browserstack successfully.

Maybe we can generate a roadmap in the coming weeks how to tackle this issue?

**Comment by christianlupus** [comment]
Duplicate of #1288. Closing in favor of the other issue.
