### ISSUE TITLE
Unable to open cookbook

### ISSUE THREAD

**Issue by larrydewey** [nextcloud/cookbook#1276]
**Description**
When attempting to access the cookbook app in Nextcloud via a web browser (I have tested Chrome, Firefox, Brave, and Vivaldi), the server returns a HTTP 504 Status Code.  

**Reproduction**
1. Go to Nextcloud Dashboard
2. Click on Cookbook Icon on the tray
3. See error

**Expected behavior**
The Cookbook application loads

**Actual behavior**
Instead of loading the page, you are redirected back to the Dashboard app.

**Screenshots**
![Nextcloud 504](https://user-images.githubusercontent.com/41640198/197064775-faae9c12-cbcf-4a15-ac03-dcae33a8f503.png)

**Browser**
Multiple browsers:
- Brave
- Vivaldi
- Firefox
- Chromium
- Epiphany

**Versions**
Nextcloud server version: 24.0.6
Cookbook version: 0.9.15
Database system: MariaDB - 10.3.32-1040

**Comment by christianlupus** [comment]
Http 504 is the gateway had time out. The app does not use this by itself. Do i see it correctly (not 100% clear in the image) that the request took almost 10 seconds?

What is your setup exactly? You seem to be running a home server from the url. What hardware are you running on? Is there a reverse proxy involved to do e.g. SSL termination?

Did it work in the past or was this the very first attempt on your server instance to test the cookbook app?

(By the way, i how you have loved it off the browser in there meantime. You accidentally shared session tokens in your screenshot. Invalidate them immediately if not yet done, @larrydewey!)

**Comment by larrydewey** [comment]
> Http 504 is the gateway had time out. The app does not use this by itself. Do i see it correctly (not 100% clear in the image) that the request took almost 10 seconds?

@christianlupus All good questions. It seems to be an intermittent behavior, as I was able to access it later on it the day, but the 504 was only encountered when trying to access the cookbook app. Yes, it took almost 10 seconds for the request to fail, but other applications were fine (calendar, files, photos, maps, etc). 

> What is your setup exactly? You seem to be running a home server from the url. What hardware are you running on? Is there a reverse proxy involved to do e.g. SSL termination?

I have a Synology DS920 NAS where I am running Nextcloud baremetal. 

Specs:
```
#######
# CPU #
#######
processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 122
model name      : Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
stepping        : 8
microcode       : 0x16
cpu MHz         : 2001.000
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 24
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch intel_pt ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdseed smap clflushopt sha_ni xsaveopt xsavec xgetbv1 dtherm ida arat pln pts md_clear arch_capabilities
bugs            : spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 3994.29
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual

##########
# Memory #
##########
MemTotal:        7979300 kB

##########
# Storage # 
##########
Filesystem              Size  Used Avail Use% Mounted on
/dev/mapper/cachedev_0   11T  123G   11T   2% /volume1

```

I am using Apache and using the reverse proxy system built in to the NAS.

> Did it work in the past or was this the very first attempt on your server instance to test the cookbook app?

It has worked in the past, but with the latest update, it seems to be running slower than it was before. I only have 100 recipes in it, so I would think that it should be running quite fast, but my experience has been quite the opposite. I don't believe my web/proxy systems are the issue, as I haven't had any issues with any of my other services running on my NAS. Vaultwarden and Kavita have near immediate reactivity, but Nextcloud has been hit or miss. The cookbook app (which my family loves, by the way) seems to be the slowest of everything on my Nextcloud Hub, though. Because of the slowness, I have been trying to apply suggested changes from the forums and issues, but the performance has still been quite slow. Like I mentioned, with the latest update, it seems to have started timing out when attempting to use it, which is really unfortunate. 

> (By the way, i how you have loved it off the browser in there meantime. You accidentally shared session tokens in your screenshot. Invalidate them immediately if not yet done, @larrydewey!)

I always manually log out of my sessions when finished, but thank you for the heads up!

**Comment by christianlupus** [comment]
> @christianlupus All good questions. It seems to be an intermittent behavior, as I was able to access it later on in the day, but the 504 was only encountered when trying to access the cookbook app. Yes, it took almost 10 seconds for the request to fail, but other applications were fine (calendar, files, photos, maps, etc).

What could be the case is that your cookbook reindexed all recipes. Depending on the system performance (both hard drive as well as CPU and memory, this might take some time. During such times, the cookbook will not serve any requests in a timely manner. There is a  plan to fix this but no user had significant problems so far that I know of.

Retrying a few (!) minutes later should then be possible. If you have access, please check in the settings (left lower corner) what the current reindexing period is.

> I am using Apache and using the reverse proxy system built in to the NAS.
> 
> It has worked in the past, but with the latest update, it seems to be running slower than it was before. I only have 100 recipes in it, so I would think that it should be running quite fast, but my experience has been quite the opposite. I don't believe my web/proxy systems are the issue, as I haven't had any issues with any of my other services running on my NAS. Vaultwarden and Kavita have near immediate reactivity, but Nextcloud has been hit or miss. The cookbook app (which my family loves, by the way) seems to be the slowest of everything on my Nextcloud Hub, though. Because of the slowness, I have been trying to apply suggested changes from the forums and issues, but the performance has still been quite slow. Like I mentioned, with the latest update, it seems to have started timing out when attempting to use it, which is really unfortunate.

I do not think the proxy in itself is the problem. I was just curious about the return value. Further, when adding a reverse proxy, some problems might be hidden: The proxy might log the actual error on the last hop while just reporting back 504 to the client. Also, there are multiple timeouts involved: those of the real server and those of the proxy.

What type were these suggested changes you made? Timeouts?

Is there anything logged in the `nextcloud.log` that indicates a networking issue?

I just posted in [another issue](https://github.com/nextcloud/cookbook/issues/1257#issuecomment-1287182663) a comment about how to access the API via curl. With that you can directly access from the NAS to itself and check if the requests work in general. Also, I would be interested in the timing, just prepend it with `time`.

At best, you try to circumvent the reverse proxy that way for now just to rule it out and reduce the complexity. If this works, you can make the same measurements through the proxy.
If you see a significant different in the timing, the reindex job was just done. I would be interested in this time difference. You can also trigger the reindex manually(via `/apps/cookbook/api/v1/reindex`) if you see no difference and are unsure.

Always make two requests in a row to ensure the second request has the reindex job done just recently.

> I always manually log out of my sessions when finished, but thank you for the heads up!

Better safe than sorry :+1:

**Comment by DiamondCreeper75** [comment]
The cookbook only functioned for me when the database system was configured to use SQLite, if I tried MySQL or PostgreSQL, I got a 504 error.
