### ISSUE TITLE
Error parsing recipe: `Cannot parse recipe: Unknown object found during flattening of instructions.`

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/cookbook#1297]
**Description**
I'm getting an error importing a recipe. The page seems to have invalid HTML but shouldn't it still be imported? 

**Reproduction**
1. Try to import https://ilovevegan.com/spinach-avocado-and-marinated-tofu-salad/

**Expected behavior**
Recipe imported successfully.

**Actual behavior**
There is a popup saying "Cannot parse recipe: Unknown object found during flattening of instructions."

The logs report:
```
  Warning  cookbook           libxml: Error 513 occurred 8 times while parsing https://ilovevegan.com/spinach-avocado-and-marinated-tofu-salad/. First time it   2022-10-28T10:48:44+00:00
                              occurred in line 523 and column 829: ID mmmlogo already defined


  Warning  cookbook           libxml: Error 800 occurred while parsing https://ilovevegan.com/spinach-avocado-and-marinated-tofu-salad/. First time it occurred  2022-10-28T10:48:44+00:00
                              in line 499 and column 1: Misplaced DOCTYPE declaration


  Warning  cookbook           libxml: Error 801 occurred 156 times while parsing https://ilovevegan.com/spinach-avocado-and-marinated-tofu-salad/. First time it 2022-10-28T10:48:44+00:00
                              occurred in line 495 and column 595: Tag header invalid


  Warning  cookbook           libxml: Error 23 occurred 5 times while parsing https://ilovevegan.com/spinach-avocado-and-marinated-tofu-salad/. First time it    2022-10-28T10:48:44+00:00
                              occurred in line 59 and column 185: htmlParseEntityRef: expecting ';'


  Warning  cookbook           libxml: Error 68 occurred 54 times while parsing https://ilovevegan.com/spinach-avocado-and-marinated-tofu-salad/. First time it   2022-10-28T10:48:44+00:00
                              occurred in line 14 and column 108: htmlParseEntityRef: no name
```

**Browser**
Which browser are you using? Firefox 106.0.1

**Versions**
Nextcloud server version: ?? 24.0.6
Cookbook version: ?? 7e17b69079a898d6c0e02037780ca86b4d430778
Database system: MariaDB

**Comment by MarcelRobitaille** [comment]
Should we add a tag for these import/parse errors?

**Comment by christianlupus** [comment]
There is already one :wink:.

The errors/warnings are mostly ignored and not of much importance. We might want to remove them from the NC logs altogether, once #1067  is implemented/merged.

I will have a look at the page you mentioned. The message means, however, that the parsing algorithm of XML already succeeded and the JSON is going to be built. Something was offending, I do not yet know what it was.

**Comment by MarcelRobitaille** [comment]
> There is already one :wink:

I don't see it. What is the name? Also, I saw a ruby tag in there. We don't have any ruby, do we?

> I will have a look at the page you mentioned. 

Thanks. I had a poke around the code. I thought those logs meant something was failing already upon parsing the HTML. I'm still not very familiar with the backend.

**Comment by christianlupus** [comment]
> I don't see it. What is the name? Also, I saw a ruby tag in there. We don't have any ruby, do we?

Ok, just to be sure we are talking is the same thing. There is a tag _website support_ that i added already to this issue. It is intended for problems with inputting from various sites. Is this what you meant?

> Thanks. I had a poke around the code. I thought those logs meant something was failing already upon parsing the HTML. I'm still not very familiar with the backend.

I am still on my way to make the backend code more documented. But this involves often a refactor cycle. 

The messages mainly mean that the pages are not strictly stick to the XML language standards. Nope that HTML is not 100% XML. It should be compatible but HTML is more forgiving. Thus, the XML parser complains about various issues in the imported sites. Many are not critical. Most of the sizes do not serve valid HTML (in the sense of the standard). This causes the errors and warnings. 

If you want, we can together have a look at the complete backend, of this is something you want to get a grasp on. Just an offer.

**Comment by MarcelRobitaille** [comment]
> Ok, just to be sure we are talking is the same thing. There is a tag website support that i added already to this issue. It is intended for problems with inputting from various sites. Is this what you meant?

Yes, that's what I meant. Sorry, I didn't expect it to be called "website support" and I didn't notice you added a tag.

> The messages mainly mean that the pages are not strictly stick to the XML language standards. Nope that HTML is not 100% XML. It should be compatible but HTML is more forgiving. Thus, the XML parser complains about various issues in the imported sites. Many are not critical. Most of the sizes do not serve valid HTML (in the sense of the standard). This causes the errors and warnings.

That makes sense. I just didn't see anything else in the logs and assumed the XML parsing errors were the cause.

> If you want, we can together have a look at the complete backend, of this is something you want to get a grasp on. Just an offer.

Sure!

**Comment by christianlupus** [comment]
> I saw a ruby tag in there. We don't have any ruby, do we?

I just saw, I forgot to answer. Yes, we do have Ruby in use: Building the GitHub pages uses the static website generator Jekyll that ist using ruby.

**Comment by christianlupus** [comment]
I just checked the reason why the recipe does not parse successfully. We are not capable of parsing `HowToSection`s correctly at the moment. The offending recipe instructions are
![grafik](https://user-images.githubusercontent.com/8202922/198985889-cb448572-5e86-4aa1-8849-c95777b03c05.png)

The exception is thrown in [this line](https://github.com/nextcloud/cookbook/blob/effbcb57408de92eba21cb19c78853db78011672/lib/Helper/Filter/JSON/FixInstructionsFilter.php#L101).
