### ISSUE TITLE
Can't scroll recipes 

### ISSUE THREAD

**Issue by psoidon** [nextcloud/cookbook#1310]
Upgraded to NC 25 now I can't scroll the main cookbook panel.
Side bar and tags scroll ok but main panel with either "all recipes" or an individual recipe will not scroll.

Probably a configuration issue on my server but not sure how to resolve.

**Comment by MarcelRobitaille** [comment]
It is not a configuration issue. The Cookbook app does not yet support NC25. Please see #1208. Please also search for existing issues before reporting, like #1298 or #1290 which report no scrolling after the update.

I am sorry that there is not a better solution for you. I am really disappointed in how this update was handled. There is no warning before updating that apps will be broken, and as far as I know we cannot simultaneously support NC24 and NC25.

**Comment by psoidon** [comment]
OK thanks,  I did look for known issues but didn't find it.
