### ISSUE TITLE
Picture of the recipe cannot be resized/enlarged on iPhone App

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/cookbook#1319]
**Description**

Thx for adding this great to app to the nextcloud app store.

Mostly - i will upload complete pics from my physical cookbook pages to the nextcloud web app (cookbook).
So - when i'm cooking i'm  just clicking on the recipe pic.

Problem is, that i cannot enlarge the pic on the iphone App (as i can do on the web app).

**Reproduction**
1. Choose on a specific recipe
2. Click on the picture
3. Picture will not enlarge to full size
4. Also, cannot resize the pic "by fingers"

**Expected behavior**

By clicking the recipe picture, the full size of the recipe should appear and 
it should also allow to resize the picture of the recipe (because normally the pic in the iPhone app is too small to read it).

**Actual behavior**
cannot enlarge the pic on the iphone App (as i can do on the web app).

**Screenshots**

**Browser**
Edge

**Versions**
Nextcloud server version: 24.0.6
Cookbook version: cookbook: 0.9.15
Database system: MySQL/MariaDB/PostgreSQL/Sqlite
10.3.35-MariaDB
iPhone iOS: 16.1

**Comment by seyfeb** [comment]
Just to be sure: When you say "on the iphone App" you mean, on the iPhone in Safari?

**Comment by Githopp192** [comment]
no, i mean the iPhone cookook app on the iPhone itself (Nextcloud CookBook) 

Entwickler:
Hexane Tech, Inc.

**Comment by seyfeb** [comment]
Then you should contact the developer/open an issue in the app's  repository. Here we develop only the Nextcloud Cookbook app (serverside and Nextcloud browser app)!
