### ISSUE TITLE
Printing function does not work as expected

### ISSUE THREAD

**Issue by vxq9e7bx** [nextcloud/cookbook#1322]
**Description**
Printing does not work as expected: 
macOS 16 / Safari -> blank page
macOS 16 / Firefox -> only first page

**Reproduction**
1. Install nextcloud + cookbook
2. Click on recipe with more than 1 page of content
3. "Print recipe"
4. Print in browser or using system dialog

**Expected behavior**
Full recipe is printed / exported to pdf

**Actual behavior**
Safari: 1 blank page is printed
Firefox: 1 page with content is printed

**Browser**
Firefox 106.0.5 (64-bit) 
Safari Version 16.1 (18614.2.9.1.12)

**Versions**
Nextcloud server version: 25.0.1
Cookbook version: 0.10.0
Database system: MariaDB

**Comment by christianlupus** [comment]
Yes, I can confirm this. Thi sis due to the fact that the core is not assuming that any app might be printing. So, the CSS is just off.
