### ISSUE TITLE
Visual regression when opening the list of recipes per category during editing of category name in NC<=24

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/cookbook#1343]
**Description**

**Reproduction**
1. Open left sidebar
2. Click on pencil-icon to edit categories 
3. Move mouse to folder-icon of a category -> folder-icon -> triangle-icon
4. Click on triange-icon 
5. Click on pencil-icon to edit (expanded) category
6. See error: category has disappeared

**Screenshots**
___
![nc_cb2 1](https://user-images.githubusercontent.com/34692335/201166171-c34760fd-66e7-4d13-b7c1-a08a6d52c6fd.png)
___
![nc_cb2 2](https://user-images.githubusercontent.com/34692335/201166184-ab6c9945-e209-4bb3-9e72-a35703810b94.png)
___
![nc_cb2 3](https://user-images.githubusercontent.com/34692335/201167593-d7c33e39-2668-42c9-a3ed-969a8fa6695e.png)
___
![nc_cb2 4](https://user-images.githubusercontent.com/34692335/201166971-8b39fb25-6dcf-48a3-b221-eb5b0905f7cb.png)

**Versions**

Nextcloud server version: 24.0.7.1
Cookbook version: 0.9.18

**Comment by christianlupus** [comment]
Closed as NC24 is EOL now.
