### ISSUE TITLE
Save Recipe not working after update

### ISSUE THREAD

**Issue by Smolders2007** [nextcloud/cookbook#1345]
**Description**
When recipe is opened for edit and edits performed, the Save button 

**Reproduction**
1. Display any recipe
2. Click on 'Edit'
3. Make a change
4. Press ... and selecct Save

**Expected behavior**
The recipe should be updated
**Actual behavior**
An error message is displayed and in the log the following entry is added.
OCA\Cookbook\Exception\RecipeExistsException: Another recipe with that name already exists

**Browser**
Google Chrome?

**Versions**
Nextcloud server version: 25.0.1
Cookbook version: 10.1
Database system: MySQL/MariaDB/PostgreSQL/Sqlite

**Comment by SakshiT25** [comment]
Hi, I'm interested in working on this issue.

**Comment by Smolders2007** [comment]
Just let me know how I can help

**Comment by Smolders2007** [comment]
Hi,

I am ready to help you, but I just let me know what I need to do.

Jean

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________
Van: SakshiT25 ***@***.***>
Verstuurd: dinsdag 22 november 2022 17:51
Aan: nextcloud/cookbook ***@***.***>
CC: Smolders2007 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nextcloud/cookbook] Save Recipe not working after update (Issue #1345)


Hi, I'm interested in working on this issue.

**Comment by christianlupus** [comment]
I just tested the described steps and for me, I am not able to reproduce the issue.

What change did you make exactly? Did you change the title by chance? Are you sure that there is no recipe with the (new) title? What is the exact text of the error message in the browser? Can you share a screenshot?

Can you go to the recipe folder in the web interface (files app) or synced to the local hard drive and look for a folder with the name of the recipe in question? How many recipes do you have ATM in the library roughly?

**Comment by Smolders2007** [comment]
Hi Christian,

I tried myself again and it seems that it must have been with one specific recipe. I tried several other ones and it seems to work fine. Sorry for the inconvenience.

Jean

Outlook voor Android<https://aka.ms/ghei36> downloaden
________________________________

**Comment by christianlupus** [comment]
I will close this issue here. If it reappears or if you is someone else find a reproducible case, just comment and we can reopen.
