### ISSUE TITLE
Make timer UI more consistent

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/cookbook#1408]
I noticed some inconsistencies in the timer UI in the recipe view page:

- The label says `(H:MM)`, but this is not true once the timer is started. When the timer is running, it shows `H:MM:SS`. 
- The label in the recipe view page says `(H:MM)` whereas the label in the recipe edit page says `(hours:minutes)`.
- The seconds are only shown when the timer is running, which in itself is inconsistent.
- I think removing `(H:MM)` from the label (also from the recipe edit page) would make the UI cleaner. As an alternative, we could make it clear in the timer's value what each number represents.

In the recipe view page, the running timer shows `0:00:45` which does not match the label `(H:MM)`
![image](https://user-images.githubusercontent.com/8503756/210118703-17a9bc1d-8ab3-46ab-9c88-2554b9357e5a.png)

The recipe edit page uses `(hours:minutes)`
![image](https://user-images.githubusercontent.com/8503756/210118955-27683691-e2e5-47cb-8aa9-78c08a541a22.png)

I would like to propose removing `(H:MM)` from the labels and replacing `0:00:45` in the timer value with `0h 00m 00s`. This makes it clear what each value represents without the need for a legend. We can also do this in the recipe edit page. 

We could also replace the two different text boxes in the recipe edit page with a single box where the user enters `1h20m` for example. It could start with `00h00m`, and we could automatically move the cursor over after the two hour digits are typed by the user. We could even support writing arbitrary durations like `1d20h30m45s`. I've seen similar UX on other websites for durations, phone numbers, and things like that. I see pros and cons to this though.

**Comment by christianlupus** [comment]
I am not so sure if this is such a trivial issue. If we are talking of English only, this might well be a simple case. If we consider the translations as well, this might be more involved. The current version allowed to have the texts mostly fixed. With the `n` method, one numerical translation can be realized. But not multiple ones as far as i know. 

I see multiple ways

- declare SI units the world default and sick with that
- only translate the string adding replacement tokens ignoring any plural form
- concatenate three strings each with plural option for hours, minutes and seconds. 

Maybe there are more options. I have not finally thought I'd this issue, just to raise the awareness of the issue.
