### ISSUE TITLE
At Chrome is the time settings field to small

### ISSUE THREAD

**Issue by 743814ck3y3** [nextcloud/cookbook#1411]
On chrome are up/down arrows displayed in focused number input fields, which makes the field to small for a time larger than 9.

![cookbook-chrome-arrows](https://user-images.githubusercontent.com/115884770/210179934-ae8123f2-b8d7-4685-bac1-8867a29aff81.jpg)

**Comment by xdubx** [comment]
yes pls update 
```
fieldset > input {
    width: 70px !important;
    text-align: center;
}
```
