### ISSUE TITLE
Feature Request: Shareable/Collaborative Recipes

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/cookbook#1420]
It would be cool if it would be possible to share Recipes as well as Recipefolders with other nextcloud users. Also it should be possible to allow editing, or only readonly.

**Comment by seyfeb** [comment]
For limited sharing, have a look [at the documentation](https://nextcloud.github.io/cookbook/user/#:~:text=currently%20not%20supported.-,Sharing%20Recipes,-Sharing%20with%20another) (you may share the recipe folder).

For extended share option there is already an issue (#392)

**Comment by MrLoverLoverMMMM** [comment]
Thanks
