### ISSUE TITLE
API code generation enhancement

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/cookbook#1421]
**Is your feature request related to a problem? Please describe.**
It's very good having an openapi spec to work with although it's not quite ready for automated library generation.
A list of problems I found:

- Some Objects returned do not have names like the [Category get](https://github.com/nextcloud/cookbook/blob/4222b4815505ad913063f46c72647dd583751f58/docs/dev/api/0.1.0/openapi-cookbook.yaml#L415-L434) for example (see matrix discussion)
- missing `operationId` on the endpoints

Those will lead to the code generator deciding on the object name or the function name to invoke a call. And it gets ugly very fast like `ApiV1KeywordsGet200ResponseInner`or `ApiV1CategoryCategoryGetRequest`.

- incorrect use of types like [`string|integer`](https://github.com/nextcloud/cookbook/blob/4222b4815505ad913063f46c72647dd583751f58/docs/dev/api/0.1.0/objects.yaml#L349) (wich should be `oneOf: ...`) or plain [String for date-time](https://github.com/nextcloud/cookbook/blob/4222b4815505ad913063f46c72647dd583751f58/docs/dev/api/0.1.0/objects.yaml#L334-L335) (open PR in #1419)

The first is strictly an invalid openapi spec while the second one would lead to the generated lib handling the validation and parsing of the date format into a suitable object to use in the code.

**Describe the solution you'd like**
All of the above would not need an altering of the api itself but a change in the documentation. The added properties would allow better and more efficient code generation and better openapi complience.

I'd like to add solutions to my already open PR and discuss everything over there although I'd need some help in finding good names for the `operationId` field and I'm quite bad at picking them :)

As mentioned the API itself wouldn't change but people already using the current spec for code generation would need to adapt to it. I don't think this would be a problem as the migration would be marginal (no logic change just replacing the object name `crtl+f` and replace would do the trick). Client authors could also just stay with the old spec as it would still be api compatible so no code change required at all.

**Describe alternatives you've considered**
null

**Comment by christianlupus** [comment]
I added a PR to tackle this issue. Please have a look if this can be closed by the PR.

**Comment by Leptopoda** [comment]
I've added my thoughts over there.
And even If you disagree with my opinion over there my main reason for starting the discussion is that some return types of the API should be made named objects like the category endpoint should return a category object with the attributes name and count :)

I'll later also explain my mentioned other ideas for inprovement

**Comment by Leptopoda** [comment]
For completeness adding that the size query parameter and it's behavior isn't documented.
I'd suggest using an enum field that contains the three possible values `enum { full, thumb, thumb16 }`

Again I'll try this locally with my app and when it's in a usable state I'll make a PR
