### ISSUE TITLE
No check mark in keyword dropdown

### ISSUE THREAD

**Issue by Benedikt81** [nextcloud/cookbook#1424]
**Description**

When I edit the keywords of an existing recipe with keywords, there is no checkmark in the dropdown. For example, the "apfel" keyword is set in this recipe:
----
![image](https://user-images.githubusercontent.com/5584309/210973058-a1333890-dde7-41f7-8fa5-212b6e286e24.png)
----
But when I open the dropdown, "apfel" has no checkmark:

![image](https://user-images.githubusercontent.com/5584309/210972991-14333c99-5c74-444a-bdd0-9cd464056e66.png)
----
Also, the existing keywords are not shown, once the dropdown is opened.

**Browser**
Vivaldi 5.6.2867.50 (Chromium 108). Same behaviour on Firefox 108.0.2

**Versions**
Nextcloud server version: 25.0.2
Cookbook version: 0.10.1
Database system: MariaDB

**Comment by seyfeb** [comment]
Are there any errors logged in the console when the recipe-edit page is loaded or the dropdown is opened? Were the keywords already part of the recipe when you navigated to the edit page? Are they correctly show on the recipe page?

**Comment by Benedikt81** [comment]
> Are there any errors logged in the console when the recipe-edit page is loaded or the dropdown is opened? 
When loading the edit view of the recipe:
![image](https://user-images.githubusercontent.com/5584309/211143744-81c87f7c-329a-4708-94fa-1965cce7b4cf.png)

When opening the dropdown this doesn't change.

There is also an item under "issues" in the developer console:
![image](https://user-images.githubusercontent.com/5584309/211143862-3a8266ab-dee9-4734-93fd-2711435163e7.png)

> Were the keywords already part of the recipe when you navigated to the edit page? 

Yes. I can also add that the keywords can be selected or deselected just fine. They will (dis)appear in the text box after clicking on the line in the dropdown. It's just that the check mark is not shown.

> Are they correctly show on the recipe page?

Yes.

**Comment by Benedikt81** [comment]
Server environment:

>OS: Ubuntu 20.04

>PHP 7.4.3 (cli) (built: Nov  2 2022 09:53:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

>Server version: Apache/2.4.41 (Ubuntu)
Server built:   2022-06-14T13:30:55

**Comment by seyfeb** [comment]
And does this happen only for this specific recipe or all recipes in your database? Could you share the recipe's json file with us? 

Am 7. Januar 2023 12:55:42 MEZ schrieb Benedikt Nyqvist ***@***.***>:
>Server environment:
>
>>OS: Ubuntu 20.04
>
>>PHP 7.4.3 (cli) (built: Nov  2 2022 09:53:44) ( NTS )
>Copyright (c) The PHP Group
>Zend Engine v3.4.0, Copyright (c) Zend Technologies
>    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
>
>>Server version: Apache/2.4.41 (Ubuntu)
>Server built:   2022-06-14T13:30:55
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/cookbook/issues/1424#issuecomment-1374455619
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tiredofit** [comment]
I see this as well:

````
Nextcloud 25.0.1
PHP 8.1
Cookbook 0.10.1
Docker: tiredofit/nextcloud:25 (Nginx / PHP-FPM)
````

From my developer tools:

````
Unknown property ‘zoom’.  Declaration dropped. [cookbook:9:10](https://nextcloud.example.com/apps/cookbook/)
Expected declaration but found ‘*’.  Skipped to next declaration. [cookbook:10:5](https://nextcloud.example.com/apps/cookbook/)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [cookbook:55:13](https://nextcloud.example.com/apps/cookbook/)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [cookbook:71:13](https://nextcloud.example.com/apps/cookbook/)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [cookbook:137:13](https://nextcloud.example.com/apps/cookbook/)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [cookbook:204:13](https://nextcloud.example.com/apps/cookbook/)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [cookbook:309:13](https://nextcloud.example.com/apps/cookbook/)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [cookbook:321:13](https://nextcloud.example.com/apps/cookbook/)
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. [cookbook:585:13](https://nextcloud.example.com/apps/cookbook/)
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. [cookbook:15:10](https://nextcloud.example.com/apps/cookbook/)
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. [cookbook:1:2688](https://nextcloud.example.com/apps/cookbook/)
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. [cookbook:1:5966](https://nextcloud.example.com/apps/cookbook/)
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. [cookbook:1:6563](https://nextcloud.example.com/apps/cookbook/)
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. [cookbook:1:2857](https://nextcloud.example.com/apps/cookbook/#/)
Unknown pseudo-class or pseudo-element ‘deep’.  Ruleset ignored due to bad selector. [cookbook:1:24](https://nextcloud.example.com/apps/cookbook/#/)
````

**Comment by Benedikt81** [comment]
> And does this happen only for this specific recipe or all recipes in your database? Could you share the recipe's json file with us?

It's for all recipes. 
[recipe.json.txt](https://github.com/nextcloud/cookbook/files/10367076/recipe.json.txt)

**Comment by seyfeb** [comment]
> I believe there may be some issues with rendering CSS as I am seeing some missing buttons - I don't know what a "proper" installation is to look at as I have just started using this app:

I think this is a separate issue. maybe the icon class got removed in a dependency. This should be easily fixed - I opened a separate issue (#1428). Btw. these should be up/downarrow buttons for moving the instructions to different positions.

Wrt. the original issue: I can reproduce this locally for the `stable` branch but not the `master` branch. Either this has already been fixed or something breaks in the CI, any idea @christianlupus ?

**Comment by Benedikt81** [comment]
> Wrt. the original issue: I can reproduce this locally for the `stable` branch but not the `master` branch. Either this has already been fixed or something breaks in the CI, any idea @christianlupus ?

stable has vue 7.0.1, master has 7.1.0. It seems likely that there is some issue related to the version of vue.js that causes this bug. As the bug is not breaking the functionality, it's probably more efficient to wait for the next version and see if it fixes the bug. I will report back once I've installed it.

**Comment by seyfeb** [comment]
You're right, indeed. Leaving this for reference: https://github.com/nextcloud/nextcloud-vue/pull/3513 The PR is included in `@nextcloud/vue` 7.1.0. I'm closing this for now, but it may be reopened if the issue persists in the next version.

**Comment by christianlupus** [comment]
I just checked and in the latest development version, it seems to work:

![Screenshot_Vue](https://user-images.githubusercontent.com/8202922/212534419-9b5a3afb-f685-42d0-b864-2ebb509ea2b3.png)

**Comment by Benedikt81** [comment]
I installed 0.10.2 today, issue is fixed for me as well.
