### ISSUE TITLE
Fix dependency on @nextcloud/broswerslist-config

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1444]
I found yesterday that there is a problem with the `@nextcloud/browserslist-config` dependency.

If you install all dependencies without said dependency (currently it is installed by default, so uninstall it) in its own folder (say `/tmp/cookbook`), it is not a problem to build the Vue app by means of `npm run build-dev`. 

If you on the other hand stick with the best practices defined by the dev environment of Julius Haertl, you install it inside the server code. In this case, the Vue app does **not** build (at least on my machine).

The steps are somewhat
```bash
cd /tmp
# Clone the server
git clone --depth 1 https://github.com/nextcloud/server.git
# Prepare the app
cd server/apps
git clone https://github.com/nextcloud/cookbook.git
cd cookbook
# Run NPM
npm ci
npm uninstall @nextcloud/browserslist-config
npm run build-dev
```

Additionally, if you install the dependencies of the server, (`npm ci` in `/tmp/server` above), the build succeeds. From the backtrace, I interpret that babel (?) is leaving the current working directory looking for further possible dependencies in parent ones.

Does anyone (maybe @MarcelRobitaille or @seyfeb) know why this is happening? Can you confirm it?

We have some modifications in comparison to the original configurations as provided by the scaffolding templates on the app store. Maybe we shot into our own foot and need to revert or a more default configuration as it should be handled in the meantime what we need. I am unsure if this is the problem here.

**Comment by MarcelRobitaille** [comment]
I can reproduce this. Using the above commands, I get an error when building. If I clone cookbook only into `/tmp` and not as a subfolder of the nextcloud server, it builds perfectly even after uninstalling browserslist-config. I am using node 16.14.2 and npm 8.5.0. Unfortunately, I have no idea why this is happening. It seems quite strange to me to build in a subfolder of the main server. Do you have a link to these best practices?

**Comment by christianlupus** [comment]
It comes from the dev environment. There is the docker dev environment by Julius Härtl that is promoted as the quasi-standard in the ecosystem of Nextcloud.

In the [complex setup](https://github.com/juliushaertl/nextcloud-docker-dev#complex-setup) it is described in detail. In fact, there you have three git repos inside each other.

**Comment by MarcelRobitaille** [comment]
Thank you for the link. Maybe you could bring this up with Julius if you have a way to contact him? I know that personally I just clone `cookbook` and `nextcloud-docker-dev` into `~/code` and mount `cookbook` as a docker read only volume like `../cookbook:/var/www/html/apps/cookbook:ro`. Maybe cloning apps inside server should be avoided if the builds are not isolated. Maybe we could talk to Julius, and unless there is a compelling reason to do it this way, we could update this best practice.

**Comment by christianlupus** [comment]
Currently, the problem seems to be gone. I do not know what solved it but I can no longer reproduce it. We might want to have an eye for similar issues.

@juliushaertl I wanted to ping you here. This could be an issue that arises with other apps as well. If you know of a reason for that, sharing would be nice. If not, you might see issues in the future and remember this issue :smile:.
