### ISSUE TITLE
can't show certain characters i.e. " \ " in recipe

### ISSUE THREAD

**Issue by herrselent** [nextcloud/cookbook#1463]
We use the cookbook app for providing colleagues technical information i.e. on how to set up the printer in the network .

Problem is, not all characters will be shown either in the cooking steps or the preparation utilities etc. once you saved the recipe. Seems to be a bug? 

Especially typing \ as it is used in network paths doesn't work. The app changes it to underscore after saving the recipe. 

Is this a quick fix?

---

Depends on #1126

**Comment by christianlupus** [comment]
Not a quick fix available but it could be fixed. 

The thing is that the path in the Nextcloud core reflects the name of the recipe. This, certain chars trigger filesystem problems. These are replaced by underscores. 

Doing this **only** in the filesystem while still providing valid string names of the recipes would solve the underlying problem and make the filter obsolete.

**Comment by christianlupus** [comment]
It would be good to have the storage driver in place before tackling this issue (#1126)
