### ISSUE TITLE
Nextcloud 26 support

### ISSUE THREAD

**Issue by a3linux** [nextcloud/cookbook#1562]
When upgrade to Nextcloud 26.0.0, the Cookbook app is disabled as it is not compatible with the new Nextcloud version.

Cookbook could be enable with trusted by Nextcloud 26.0.0.

**Comment by christianlupus** [comment]
The development version is already marked as NC26 compatible. The latest one is working with NC26 but the release was not yet pushed out. I will have a look at this and try to get a version out for support ASAP.

**Comment by christianlupus** [comment]
Closed with version 0.10.2
