### ISSUE TITLE
Enhance recipe recalculation algorithm

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1603]
> I just checked a few additional cases. Now, I found a few issues, that might come up in the close future (or to help enhance the code base). I will nevertheless approve/merge this PR to get the functionality into the app. The fixes can then be applied step by step.

> I will open a new bug with all found issues in order to tackle them.

_Originally posted by @christianlupus in https://github.com/nextcloud/cookbook/issues/1573#issuecomment-1501198468_

The issues in question are the following:

- [x] The code assumes at least one whitespace char between the unit and the amount. E.g. in German, it is used like this `100g` without whitespace.
- [ ] Similarly, the code uses pure decimal points for fractions. In other languages, a comma is used as the decimal separator.
- [x] For large quantities, some users might add separators each 3 digits like this: `1,000`, `1 000`, or `1.000` This is especially critical as it conflicts with decimal comma above. I suggest to reject any number with both comma and point
- [ ] Fractions like `3 1/2 cups of sugar` will be parsed with a numerically wrong result. It should at least be rejected by the algorithm. However, it will even cause a wrong calculation without notification (ex: 2 x `1 1/2` should be 3, and the algorithm returns `2 1/2`). Better would be to parse these correctly.
- [x] I discovered rounding issues (6 servings used 2 eggs, changing to 9 servings displays `2.99` instead of the expected 3)
- [x] I would have preferred if the algorithm was encapsulated in its own module under `js` and imported from there. This might keep the overall code structure more tight and clear.

@j0hannesr0th what are you thinking about these points?

**Comment by j0hannesr0th** [comment]
@christianlupus I'll fix that tomorrow.

**Comment by christianlupus** [comment]
No worries. This is just to keep the points together.

**Comment by j0hannesr0th** [comment]
@christianlupus here are my thoughts:

>The code assumes at least one whitespace char between the unit and the amount. E.g. in German, it is used like this 100g without whitespace.

Sure, easy fixable. Will just use the first number I find, not matter which characters follow.

Possible examples which will work after fix:
- 100g flour
- 100 g flour
- 100 flour
- 100flour
- 1Ei
- 1 Ei

> Similarly, the code uses pure decimal points for fractions. In other languages, a comma is used as the decimal separator.

I'll accept comma and point as a decimal separator.

> For large quantities, some users might add separators each 3 digits like this: 1,000, 1 000, or 1.000 This is especially critical as it conflicts with decimal comma above. I suggest to reject any number with both comma and point

Agree. If I find both of them, I'll mark it as wrong format.


> Fractions like 3 1/2 cups of sugar will be parsed wrongly with a numerically bad result. It should at least be rejected by the algorithm. However, it will even cause wrong a wrong calculation (ex: 2 x 1 1/2 should be 3, the algorithm returns 2 1/2)

I'll add a check for: integer followed by "integer / integer". If I find it, I'll show wrong format error message. I'm going to add a second example with decimal amount: 10.5 g yeast

> I discovered rounding issues (6 servings used 2 eggs, changing to 9 servings displays 2.99 instead of the expected 3)

Will check this one.

> I would have preferred if the algorithm was encapsulated in its own module under js and imported from there. This might keep the overall code structure more tight and clear.

I agree that we have to extract the regex into a new module. Is it okay for you if I extract it into a module with multiple regexes instead of one single regex handling all cases?

**Comment by christianlupus** [comment]
> I agree that we have to extract the regex into a new module. Is it okay for you if I extract it into a module with multiple regexes instead of one single regex handling all cases?

I am perfectly fine with a module in `src/js/` folder (see e.g. https://github.com/nextcloud/cookbook/blob/master/src/js/api-interface.js). There is even an alias `cookbook` in place to allow for absolute paths ([example](https://github.com/nextcloud/cookbook/blob/1f4d477c96318b02de7910a843fc285b9fa169a8/src/components/AppIndex.vue#L6)).

You can implement the module however it seems useful and readable. If it was testable, that would be an additional add-on. If you use multiple RegEx expressions, that seems perfectly fine (and might be better to understand). I would however prefer if the interface to the rest of the app was well-defined, aka just a checker and a parser function that abstracts away all the logic (or classe methods or whatever).

**Comment by christianlupus** [comment]
Hello @j0hannesr0th, did you succeed in your work so far?

I am at least partially back in the development and try to clean up a few issues at the moment. I just wanted to ask you for a quick heads-up.

Thanks!

**Comment by j0hannesr0th** [comment]
Hi @christianlupus I'm sorry I didn't have much spare time in the last weeks. Now I'll have more time again and will provide a PR soon.

**Comment by j0hannesr0th** [comment]
Hi @christianlupus now you can test it #1723 and give feedback to me.

**Comment by christianlupus** [comment]
@j0hannesr0th I merged #1723 as a good starting point and to avoid diverging of the branches too much.

I also moved the complete algorithm to its own file `src/js/yieldCalculator.js` and fixed a few minor issues with it (side effects with other parts of the code).

However, there are still issues left to address:

1. The decimal comma is not handled appropriately by `parseFloat`. For example, `0,99 kg sugar` will be parsed as `0 kg sugar`.
2. The comments on the regex expressions are outdated. I marked them. Please update the descriptions or remove them. It might be better to describe what you want to achieve with them instead of a detailed description of the regex (that can be extracted from the regex code itself).
3. The case of `2 1/3 cups of milk` is currently _only_ marked as failing. You cannot calculate with it. (aka this is partially solved and could be published at least)

**Comment by j0hannesr0th** [comment]
@christianlupus thank you for your feedback.

I wrote some comments here: https://github.com/nextcloud/cookbook/pull/1743
