### ISSUE TITLE
Saving Problem

### ISSUE THREAD

**Issue by githubloginuser** [nextcloud/cookbook#1621]
Unfortunately, the app seems to have a big problem with the save function. 
After saving a recipe for the first time, the spinner remains as if the process cannot be completed.
The app refuses saving changes of recipes in the following. 

NextCloud v24.04 
on Server: 
Betriebssystem: Linux 5.15.0-60-generic x86_64
Prozessor: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz (4 cores)

**Comment by christianlupus** [comment]
Honestly, I have not had such issues in the past and I cannot reproduce this issue currently. I can edit/create new recipes and save them successfully.

Is there anything logged in `data/nextcloud.log`? Is there any error in the browser console present?

Unfortunately, you did remove significant parts of the bug report template so these information pieces need to be requested manually. Without any clue, I can't do much to fix this.

**Comment by GhostTalker** [comment]
Issue still exist. No errors in the logfile.

**Comment by christianlupus** [comment]
Ok, then, how about the browser debug console? Are there any messages?

Is the problem reproducible or just appearing randomly?
