### ISSUE TITLE
www.vegrecipesofindia.com: No parser found for the given import.

### ISSUE THREAD

**Issue by Razzaline** [nextcloud/cookbook#1638]
**Failing website:**
https://www.vegrecipesofindia.com/bombay-biryani-recipe-dum-veg-biryani/

**Checking if valid metadata are present:**
- [x] Yes, I checked the source code of the website and found metadata.

**Cookbook version:**
0.10.2

**Problem description (if applicable):**
The page cannot be imported. The error message is: "No parser found for the given import."

**Comment by christianlupus** [comment]
Duplicate of #1675
