### ISSUE TITLE
bakerbynature.com: No parser found for the given import.

### ISSUE THREAD

**Issue by Razzaline** [nextcloud/cookbook#1639]
**Failing website:**
https://bakerbynature.com/the-most-wonderful-vegan-chocolate-chip-cookies-ever/

**Checking if valid metadata are present:**
Yes, I check the source code of the website and found metadata.

**Cookbook version:**
0.10.2

**Problem description (if applicable):**
The page cannot be imported. The error message is: "No parser found for the given import."

**Comment by christianlupus** [comment]
Duplicate of #1675
