### ISSUE TITLE
Minutes don't show correctly

### ISSUE THREAD

**Issue by Mike710Shine** [nextcloud/cookbook#1657]
**Description**
When i configure the minutes over 9 there where show as 1 when its configure from 10 to 19 and 2 when its configure from 20 to 29 and so on.

**Reproduction**
1. Go to cookbook
2. Click new receipe
3. configure the minutes under cooking duration

**Expected behavior**
when i configure 15 i will se 15.

**Actual behavior**
when i configure 15 i see only 1.

**Screenshots**
When i take a Screenshot you will only see the 1 like 1 minutes but its configured 15 for example.

**Browser**
Opera and Chrome

**Versions**
Nextcloud server version: 26.0.1
Cookbook version: 0.10.2
Database system: MariaDB 10.11

All in Docker Container

**Comment by christianlupus** [comment]
Is this the same as #1411, @Mike710Shine?

**Comment by Mike710Shine** [comment]
Was the same as #1411
