### ISSUE TITLE
Feature request: API to get all recipes in a category

### ISSUE THREAD

**Issue by Schlaubischlump** [nextcloud/cookbook#171]
The `/api/recipes` endpoint does not provide a way to get all recipes belonging to a specific category.

**Comment by mrzapp** [comment]
@mcorteel do we use the search endpoint for that now, or how does that work with the new routing?

**Comment by mcorteel** [comment]
There isn't an endpoint for that. I guess we should create a `CategoryController` with an `index` action to get a list of categories and a `show` action to get all recipes in a category.

**Comment by mcorteel** [comment]
Actually I'm not sure here. There is a list of categories (`/categories`) and the index action in `RecipeController` has a parameter that allows filtering by a list of keywords.

@mrzapp Should we just add another parameter that allows filtering by category in `RecipeController::index`?

Also, I guess `MainController::categories` should be moved to a separate `CategoryController` and put behind the `/api` URL prefix.

**Comment by mrzapp** [comment]
@mcorteel I think you're right, it should probably be fetched from `/api/categories`. Listing recipes by category with a `category` request parameter is also the way I'd go about it.

**Comment by Schlaubischlump** [comment]
What's about the keywords ? To get a list of all keywords you have to use the MainController. To filter by keywords you have to use the index action in `RecipeController`. Should a new `KeywordController` be added to make it consistent with the proposed changes ? It just seems wrong to fetch the keywords using the `MainController`, when the list of categories is fetched using its own endpoint.

**Comment by mcorteel** [comment]
That's right!

**Comment by christianlupus** [comment]
This seems to be fixed already some time ago: [This route](https://github.com/nextcloud/cookbook/blob/57b2331522c64e1c7f90a407927caf55ffda0c2c/appinfo/routes.php#L34) allows direct access to all recipes associated with a category. For the tags there is a [link as well](https://github.com/nextcloud/cookbook/blob/57b2331522c64e1c7f90a407927caf55ffda0c2c/appinfo/routes.php#L36).

I will close this here therefore.
