### ISSUE TITLE
Recipe Sharing

### ISSUE THREAD

**Issue by EpicJosch** [nextcloud/cookbook#1732]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I'd really like to have a sharing function in the cookbook. So you can share your recipes and edit them together with another person registered on the nextcloud. Is that possible?

**Comment by TheMBeat** [comment]
Duplicate.

Sharing with NC users, see https://github.com/nextcloud/cookbook/issues/120
Public sharing see https://github.com/nextcloud/cookbook/issues/392
related to https://github.com/nextcloud/cookbook/issues/340
