### ISSUE TITLE
Error Data Access after upgrade to NC27

### ISSUE THREAD

**Issue by hanichl** [nextcloud/cookbook#1755]
**Description**
After upgrade to NC27, the app can not be opened for an existing user "oskar", new created users can access normally.

**Reproduction**
1. Go to 'Cookbook app in Browser'
2. Click on 'Cookbook'
3. See error

**Expected behavior**
App should open without error message

**Actual behavior**
Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen.
Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.
Weitere Details können im Server-Protokoll gefunden werden.
Technische Details
Entfernte Adresse: 192.168.178.50
Anfragekennung: oJRQbUEd26czPIiHLAhN

**Screenshots**

**Browser**
Firefox 114, Chrome 14

**Versions**
Nextcloud server version: 27.0.0.8
Cookbook version: 0.10.2
Database system: MariaDB

<details><summary>Nextcloud logs regarding the request</summary>

Download the file here: [cookbook_error.txt](https://github.com/nextcloud/cookbook/files/12024976/cookbook_error.txt)

```json
{
  "reqId": "fU0cSjnB2AKEmR3TiPSu",
  "level": 3,
  "time": "2023-07-12T07:00:47+00:00",
  "remoteAddr": "192.168.178.50",
  "user": "oskar",
  "app": "PHP",
  "method": "GET",
  "url": "/nextcloud/index.php/apps/cookbook/",
  "message": "file_get_contents(/var/www/html/nc_data/oskar/files/Rezepte/Toskanischer Mandelkuchen mit Karamellfächer /recipe.json): Failed to open stream: No such file or directory at /var/www/html/nextcloud/lib/private/Files/Storage/Local.php#305",
  "userAgent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
  "version": "27.0.0.8",
  "data": {
    "app": "PHP"
  }
}
{
  "reqId": "fU0cSjnB2AKEmR3TiPSu",
  "level": 3,
  "time": "2023-07-12T07:00:47+00:00",
  "remoteAddr": "192.168.178.50",
  "user": "oskar",
  "app": "index",
  "method": "GET",
  "url": "/nextcloud/index.php/apps/cookbook/",
  "message": "",
  "userAgent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
  "version": "27.0.0.8",
  "exception": {
    "Exception": "OCP\\Files\\GenericFileException",
    "Message": "",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/nextcloud/apps/cookbook/lib/Service/DbCacheService.php",
        "line": 140,
        "function": "getContent",
        "class": "OC\\Files\\Node\\File",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/cookbook/lib/Service/DbCacheService.php",
        "line": 121,
        "function": "parseJSONFile",
        "class": "OCA\\Cookbook\\Service\\DbCacheService",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/cookbook/lib/Service/DbCacheService.php",
        "line": 66,
        "function": "parseJSONFiles",
        "class": "OCA\\Cookbook\\Service\\DbCacheService",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/cookbook/lib/Service/DbCacheService.php",
        "line": 403,
        "function": "updateCache",
        "class": "OCA\\Cookbook\\Service\\DbCacheService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/nextcloud/apps/cookbook/lib/Service/DbCacheService.php",
        "line": 392,
        "function": "checkSearchIndexUpdate",
        "class": "OCA\\Cookbook\\Service\\DbCacheService",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/cookbook/lib/Controller/MainController.php",
        "line": 56,
        "function": "triggerCheck",
        "class": "OCA\\Cookbook\\Service\\DbCacheService",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 230,
        "function": "index",
        "class": "OCA\\Cookbook\\Controller\\MainController",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 137,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/AppFramework/App.php",
        "line": 183,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Route/Router.php",
        "line": 315,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/html/nextcloud/lib/base.php",
        "line": 1064,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/html/nextcloud/lib/private/Files/Node/File.php",
    "Line": 56,
    "CustomMessage": "--"
  }
}
```
</details>

**Comment by motorsense** [comment]
Hi, same issue here

**Comment by hanichl** [comment]
Hello, i dont have Redis as a cache, mine is OPcache (through PHP, i guess). Any clue how to get around ?

**Comment by christianlupus** [comment]
Hello @hanichl,

can you please check your recipe folder for the folder of recipe _Toskanischer Mandelkuchen mit Karamellfächer_? Is there a whitespace at the end of the folder name?

Thanks

**Comment by christianlupus** [comment]
Hi @motorsense,

> Edit: Problem solved to me. Redis was the Problem.

We do not make use of redis. It would be interesting to know what the issue was on your side as there were multiple issues in the past that seemed related to redis. Maybe you can shed some light on at least your case. Feel free to open a new discussion to clear this issue.

**Comment by motorsense** [comment]
After upgrade to NC 27 NC shows a warning in administration for configuring redis for Transactional File Locking. So I configure it and the warning goes away. After that I test cookbook and it shows the error massage above. Office also don't work. It don't open documents. At last I test the Notes App. It shows a little redis error massage at the right top corner. I reread my redis config in NC and see a copy-paste error in Socket name. After correct that all the 3 not working apps woks. Sorry for my bad English.

**Comment by hanichl** [comment]
Hello @christianlupus .
There is NO folder "Toskanischer Mandelkuchen mit Karamellfächer" at all in the directory of the recipes. !??!
And there is NO record for "Toskanischer Mandelkuchen mit Karamellfächer" in the mariadb-table " oc_cookbook_names". ??!
I tried to clear some php cache with 
opcache_reset()
clearstatcache()
but the error still persist.
Thank you

**Comment by christianlupus** [comment]
Hello, I checked your stack trace and updated your initial commit to make it simpler to read it.

The cookbook app triggers its rescan of all recipes (which happens on regular intervals). This rescan will update the internal cache in the database (said `oc_cookbook_names` table). In order to do this, first all recipe candidates are parsed and iterated over. Then, the DB is updated with these files to contain (only) the recipes existing in the filesystem.

When reading the file in question, PHP issues this error: `file_get_contents(/var/www/html/nc_data/oskar/files/Rezepte/Toskanischer Mandelkuchen mit Karamellfächer /recipe.json): Failed to open stream: No such file or directory at /var/www/html/nextcloud/lib/private/Files/Storage/Local.php#305`. So, the list of recipes that was built from the existing files in the DB of NC somehow reports these files to be present.

- You are user `oskar`, right?
- Is your recipe folder configured to be `/Rezepte` (or the German default)?
- Can you check the `/Rezepte` folder for the folder in the NC web frontend (to have the cache of NC included)?
- You could try to rescan the folder `/Rezepte` by means of `occ files:rescan -p oskar/files/Rezepte`. Does this resolve the problem?
- Is there any sharing or so activated/involved?
- Do you know if the name of the recipe (which is rather specific) exists in any other cookbook/location?

**Comment by hanichl** [comment]
- You are user oskar, right? >> right :)

- Is your recipe folder configured to be /Rezepte (or the German default)? >> yes

- Can you check the /Rezepte folder for the folder in the NC web frontend (to have the cache of NC included)? >> in NC - Rezepte the folder "Toskanischer Mandelkuchen" is present !

- You could try to rescan the folder /Rezepte by means of occ files:rescan -p oskar/files/Rezepte. Does this resolve the problem? >> **after a files:scan, the suspicious folder in NC has gone, and the app can be started normal**

- Is there any sharing or so activated/involved? >> yes

- Do you know if the name of the recipe (which is rather specific) exists in any other cookbook/location? >> no further usage in other cookbooks
_------------------------------
So this command did the trick:
sudo -u www-data php occ files:scan -p oskar/files/Rezepte

Thank you, you made my day 👍

**Comment by christianlupus** [comment]
I suspect this was a local caching issue in the `oc_files` table of your installation. I suspect this was a bug in the upgrade process or whatever. At least it is resolved and I will close it now.

If the problem reappears, we can investigate further.
