### ISSUE TITLE
Recipe import fails if website contains multiple <script type="application/ld+json">

### ISSUE THREAD

**Issue by turnbeutel** [nextcloud/cookbook#1759]
**Description**

If the recipe's _html_ file includes **more than one** <script type="application/ld+json"> references, the cookbook parser responds with the error message:`failed as HTTP status code 403 is not in expected range`. Deleting any occurrence to other json that is not a `"@type": "Recipe"` fixes the issue.

**Reproduction**

1. Try to import this [recipe](https://www.chefkoch.de/rezepte/1137301220006209/Zucchini-Reis-Pfanne-a-la-Helene.html) via the cookbook nextcloud application
2. See error: `failed as HTTP status code 403 is not in expected range`
3. Try to import the same [recipe](https://www.maskiertemuchachos.org/test.html) but with only a single ld+json (I deleted manually any ld+json reference, that is not of the type recipe)
4. See import success

**Expected behavior**

I would expect the parser look only for ld+json files that comply with "@type": "Recipe"

**Actual behavior**

Rigth now, I'm not able to import any recipe from chefkoch.de, into the nextcloud cookbook app. This website is one of the biggest german speaking recipe providers so it happens quite often to me that I would like to import from there.

**Screenshots**

<img width="670" alt="Bildschirmfoto 2023-07-17 um 13 07 51" src="https://github.com/nextcloud/cookbook/assets/9333180/7f2da38c-81a9-43e8-92cf-56de16d1bbf4">

**Browser**

Firefox 116.0b5 (64-Bit) for MacOS

**Versions**
Nextcloud server version: Nextcloud Hub 4 26.0.3
Cookbook version: 0.10.2
Database system: MySQL/MariaDB/PostgreSQL/Sqlite

**Comment by pjehan** [comment]
This also affects the french website marmiton.org.

**Comment by RobertWi** [comment]
Also affects dutch https://www.ah.nl/allerhande

**Comment by turnbeutel** [comment]
I had some time debugging and figured out, that it is **not** the second "application/ld+json" file in the html page but the  **server** _chefkoch.de_ itself refusing the connection to the curl call in _DownloadHelper.php_ function _downloadFile()_.

Calling curl from my nextcloud instance returns:
curl https://www.chefkoch.de/rezepte/955491201155012/Hokkaido-Kuerbissuppe.html
<!DOCTYPE html>
<html>
  <head>
    <title>403 Access denied</title>
  </head>
  <body>
    <h1>Error 403 Access denied</h1>
    <p>Access denied</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 1005762998</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

Calling curl from my laptop returns the requested webpage. So this is probably a scraper protection from the recipe website.

**Comment by christianlupus** [comment]
One idea from my side here:
Could you do the call from your browser and copy the user agent to the curl call? I am just curious if they use some IP based approach or lol at the agent header. 

The latter could be changed in the cookbook download method.

**Comment by turnbeutel** [comment]
Hi Christian, I tried your suggestion with the following call. It looks to me like a IP base approach like you mentioned.

`curl https://www.chefkoch.de/rezepte/955491201155012/Hokkaido-Kuerbissuppe.html -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0"
<!DOCTYPE html>
<html>
  <head>
    <title>403 Access denied</title>
  </head>
  <body>
    <h1>Error 403 Access denied</h1>
    <p>Access denied</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 433013591</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>`
