### ISSUE TITLE
Cookbook fails to open after Nextcloud updated to 27.0.2

### ISSUE THREAD

**Issue by linuxsquad** [nextcloud/cookbook#1806]
**Description**
After updating to Nextcloud Hub 5 (27.0.2) , Cookbook version 0.10.2  fails to open and the following error message shown: 
![screenshot](https://github.com/nextcloud/cookbook/assets/1435303/b8d7c2cd-874a-49b0-a6db-1bf6a28c9af8)

**Reproduction**
1. Login to Nextcloud server (version 27.0.2)
2. Go to Cookbook (version 0.10.2)
3. Clock on Cookbook 
4. see the above error message

**Expected behavior**
Cookbook open existing recipies and functional as prior to the update. 

**Actual behavior**
Opening Cookbook fails with the above error message 

**Screenshots**
Attached

**Browser**
Brave on Linuix

**Versions**
Nextcloud server version: 27.0.2
Cookbook version: 0.10.2
Database system: MariaDB 10.6.12

**Comment by linuxsquad** [comment]
logs
`

192.168.192.50 - - [04/Sep/2023:19:09:25 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 304 -
192.168.192.50 - - [04/Sep/2023:19:09:30 -0500] "GET /index.php/apps/cookbook/ HTTP/1.0" 500 3660
192.168.192.50 - - [04/Sep/2023:19:09:30 -0500] "GET /index.php/apps/theming/icon?v=0 HTTP/1.0" 404 25949
192.168.192.50 - - [04/Sep/2023:19:09:32 -0500] "GET /index.php/apps/photos/service-worker.js HTTP/1.0" 200 14615
192.168.192.50 - - [04/Sep/2023:19:09:34 -0500] "GET /index.php/apps/cookbook/ HTTP/1.0" 500 3660
192.168.192.50 - - [04/Sep/2023:19:09:34 -0500] "GET /index.php/apps/theming/icon?v=0 HTTP/1.0" 404 25949
192.168.192.50 - - [04/Sep/2023:19:09:34 -0500] "GET /index.php/apps/cookbook/ HTTP/1.0" 500 3660
192.168.192.50 - - [04/Sep/2023:19:09:35 -0500] "GET /index.php/apps/theming/icon?v=0 HTTP/1.0" 404 25949
192.168.192.50 - - [04/Sep/2023:19:09:36 -0500] "GET /index.php/apps/photos/service-worker.js HTTP/1.0" 200 14615
`

**Comment by christianlupus** [comment]
The log is not very useful here as the main request fails already. Could you temporarily enable the debug mode on your server and retry? That is too sweet the setting `debug` to `true` in your `config.php`?

**Comment by linuxsquad** [comment]
Updated to NC to 27.1.0, the issue is still there

**Comment by christianlupus** [comment]
I created a [branch for you](https://github.com/nextcloud/cookbook/compare/master...investigation/1806-invalid-storage) to test out which file is failing. You could patch your PHP files accordingly and have a look at the NC logs (keep them on level 0 aka debug). There should be one message for each file that is parsed.

Can you manually access the last file (which would be the one failing)?

**Comment by linuxsquad** [comment]
> Just to avoid searching in the wrong direction: The recipe files of the user you tested with is it in the local file storage or is it located somewhere else (like on group folder or so)?

The file are under NCADMIN user, but USER_A shares group permissions to access this folder. Here is what Ive tested:
1- Accessing under NCADMIN, produced the same error 
2- copy RECIPE folder to USER_A  directory, produced the same error

**Comment by linuxsquad** [comment]
> I created a [branch for you](https://github.com/nextcloud/cookbook/compare/master...investigation/1806-invalid-storage) to test out which file is failing. You could patch your PHP files accordingly and have a look at the NC logs (keep them on level 0 aka debug). There should be one message for each file that is parsed.
> 
> I put here a patch if you prefer that: [cookbook-1806.patch.txt](https://github.com/nextcloud/cookbook/files/12675447/cookbook-1806.patch.txt)
> 
> Can you manually access the last file (which would be the one failing)?

Thanks, I will test them later today/tomorrow

**Comment by linuxsquad** [comment]
Thanks, Apparently...  it couldn't find a recipe dir that I tried to delete and it failed. So I restored it and it works again. +++

**Comment by linuxsquad** [comment]
BTW, what are the steps to remove the recipe if the conventional way deleting it fails?

**Comment by christianlupus** [comment]
Normally, the removal in the web frontend should work correctly. There is no backup solution AFAIK. Removing the corresponding files in the files app should be an alternative...
