### ISSUE TITLE
Any possible for recipeInstructions to and media ?

### ISSUE THREAD

**Issue by toyqiu** [nextcloud/cookbook#1813]
I think only one index picture is not enough for a dish

**Comment by christianlupus** [comment]
You are referring to the index images in the top of the recipe, the thumbnail image in the list of all recipes, or (from the title of the issue) to add images to the instruction steps?

**Comment by toyqiu** [comment]
> You are referring to the index images in the top of the recipe, the thumbnail image in the list of all recipes, or (from the title of the issue) to add images to the instruction steps?

 (from the title of the issue) to add images to the instruction steps

**Comment by seyfeb** [comment]
There was already the feature request and some discussion around adding images to instructions in issue #324 
If you are suggesting a different feature this issue may be reopened.
