### ISSUE TITLE
Switch to @nextcloud/dialogs

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1819]
### Discussed in https://github.com/nextcloud/cookbook/discussions/1817

<div type='discussions-op-text'>
<sup>Originally posted by **Qfrijters** September 19, 2023</sup>
Pretty much what the title says, or I might be just beyond stupid (which is entirely possible). I am on nextcloud version 27.1.0  and the latest version of cookbook (from March). I am really new to the cookbook plugin but I couldn't find anything in the documentation (or I just read over it 3 times). The recipe folder is located on a different drive than where I have nextcloud installed. 

Thanks in advance.

https://github.com/nextcloud/cookbook/assets/68586456/c88dd9b5-3fa0-4c75-ac49-ebb017d31ec6

</div>

---

### Additional comments

Discussed with the team of the server. The reason is the usage of the legacy `OC.dialogs.filepicker` (in [1](https://github.com/nextcloud/cookbook/blob/e84355def19e79e51f7ccd6b36b9b4391e3dff4b/src/components/SettingsDialog.vue#L318), see also [2](https://github.com/search?q=repo%3Anextcloud%2Fcookbook%20filepicker&type=code)). This hsoul dbe replaced with @nextcloud/dialogs NPM package.

**Comment by radoeka** [comment]
#1824 is probably similar to this issue
