### ISSUE TITLE
Cannot change the Cookbook folder

### ISSUE THREAD

**Issue by radoeka** [nextcloud/cookbook#1824]
**Description**
I tried to change the Cookbook folder, but I did not succeed.
The configuration remains unchanged at '/Recepten'

**Reproduction**
1. Go to https://'\<fqdn>/apps/cookbook/ 
2. Click on Cookbook Settings
3. Scroll down to Recipe Folder (it is the first setting, the setting on top of the popup window)
4. Change the current setting '/Recepten', using the file browser to another folder.  I select 'Intern/Recepten'
5. The file browser (popup window) works.  I can select another folder

**Expected behavior**
The folder I select is remembered/starts to be used.  This is not the case

**Actual behavior**
The selected folder is neglected

**Browser**
Chrome, Firefox.  Up to date versions.  Both show the same behavior

**Versions**
Nextcloud server version: 27.1.1
Cookbook version: 0.10.2
Database system: Sqlite

**Comment by radoeka** [comment]
Screenshot of the settings window:
![image](https://github.com/nextcloud/cookbook/assets/2937666/b07343aa-75b1-4180-85d0-22c34e3d4a2d)

**Comment by tjcjr** [comment]
I am having the same issue.

**Comment by Qfrijters** [comment]
uh, small update
as of version Nextcloud Hub 6 (27.1.2), I don't seem to have this issue anymore
Can't say if anything else is missing tho, but I can choose a folder now

**Comment by christianlupus** [comment]
There was a big in the server that caused a bug. They fixed it in the server in the meantime, so updating the server should fix this. 

A more permanent solution is #1819.
