### ISSUE TITLE
Add cookbook client to readme

### ISSUE THREAD

**Issue by VincentMeilinger** [nextcloud/cookbook#1833]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I developed an iOS native cookbook client application, and I‘d like to add it to the list of cookbook clients.
[Here](https://apps.apple.com/app/id6467141985) is a link to the application in the AppStore.
Is this still possible? If so, how should I do this?

**Comment by christianlupus** [comment]
Hey. Generally, this is possible. 

The simplest was if you provided a pull request. Is that possible for you?

**Comment by VincentMeilinger** [comment]
Ok, nice!
So I'll just create a new branch and then a pull request?
Thank you for helping me out here!

**Comment by christianlupus** [comment]
I suspect, you are not part of the NC repository.

1. Create a fork of this project so you have writing permissions.
2. Create a branch (no existing one) and put your changes there. Make sure, you sign off any (!) commits.
3. Push the changes in the branch to your fork.
4. If you use the console, GitHub will output a link to open a PR automatically. Click it and follow the instructions

If the link was not there or not visible, go on manually:

5. Go to the GitHub website.
6. Most probably, you will be presented with a notification of a new branch that might need a PR, see point 4 above.
7. If not, go to pull requests, and open a new one. Configure to merge your branch into the `master` branch of the cookbook repo.

The rest can be discussed there or I will merge things straightly.

**Comment by VincentMeilinger** [comment]
Thank you for the detailed description! I created the PR now, I hope it is is correct.

**Comment by christianlupus** [comment]
Closed by means of #1837
