### ISSUE TITLE
Swagger documentation typo

### ISSUE THREAD

**Issue by lneugebauer** [nextcloud/cookbook#1838]
**Description**
There is a typo in the [objects.yaml](https://github.com/nextcloud/cookbook/blob/1aea31ed734ce1853d8f9cf967137ec0ab0bb619/docs/dev/api/0.1.2/objects.yaml) file of the Swagger documentation.
Recipe instructions are named `resipeInstructions` twice instead of `recipeInstructions`. This seems to effect documents of all versions.

**Expected behavior**
The documentation should show `recipeInstructions`.

**Actual behavior**
The documentation currently shows `resipeInstructions`. With my setup the API endpoint returns the correct value though.

**Versions**
Nextcloud server version: 26.0.5
Cookbook version: 0.10.2
Database system: MySQL

**Comment by christianlupus** [comment]
I think, this issue was solved and just not closed. I remember I tried to fix it. If there is still an issue open, please comment.
