### ISSUE TITLE
Error 403 forbidden on download recipe and image

### ISSUE THREAD

**Issue by Qfrijters** [nextcloud/cookbook#1840]
**Description**
Normally you get a parse error when a site doesn't support the import of a recipe, or the format isn't right. However, I got a HTTP status 403 error.

**Reproduction**
click on "Download recipe from URL
enter this site "https://www.plus.nl/recept/kip-parmezaan-in-geroosterde-paprikasaus-met-tomaatjes-en-aubergine-r-24k0197"
error will appear

**Expected behavior**
Either a parse error or a succesful import of the recipe

**Actual behavior**
403 error

**Screenshots**
![image](https://github.com/nextcloud/cookbook/assets/68586456/d560c7a1-fdaf-483b-a227-08f7a2891af5)
![image](https://github.com/nextcloud/cookbook/assets/68586456/1e48f878-27a9-4e9b-bdd5-6ba23c790207)

Second image is actually from downloading a photo, but it's from the same site and it's also a 403 forbidden error.

**Browser**
edge

**Versions**
Nextcloud server version: 27.1.2
Cookbook version: 0.10.2
Database system: MariaDB

**Comment by christianlupus** [comment]
Hello and thans for reporting this.

Could you please recheck the behavior. I am not able to reproduce the it here. I can load the web site and view it in my browser. However, tey seem not to provide any Schema.org data to import. So, the importer will fail anyways if we are looking at the same recipe.

**Comment by Qfrijters** [comment]
expected behaviour: parse error as there is no schema.org
Also, this is a server in a datacenter and not a pc at home.
https://github.com/nextcloud/cookbook/assets/68586456/6dc3a7a9-fdc8-43ca-9d1d-4c3d3787474c

**Comment by christianlupus** [comment]
Could this be a duplicate of #1759?

**Comment by Qfrijters** [comment]
I just read that thread, I think the source of both issues is the same, and @turnbeutel mentioned it. I think, just like him, it is a scraper protection. Especially as @RobertWi literally mentioned the same site, only for me it worked and it didn't for him. I had an issue with another Dutch supermarket site.

**Comment by Tommy-01** [comment]
I got the same error with receipes from https://www.rewe.de/rezepte

Formerly this site works but since some time import from the App and the web frontend didn't work.
Url for example:
https://www.rewe.de/rezepte/spitzkohlpuffer/

**Comment by codesnippy** [comment]
Got the same error on https://www.ah.nl/allerhande/recept/R-R1189235/gemberbier

In the past it work normally from this site.

**Comment by Jordanb716** [comment]
Just got this error with https://www.foodnetwork.com/recipes/alton-brown/corn-dogs-recipe-1941945

**Comment by n8henrie** [comment]
For the last few weeks, I've been getting 403s with all FoodNetwork recipes that I've tried.

For example, first one I tried today: https://www.foodnetwork.com/recipes/food-network-kitchen/air-fryer-fried-shrimp-8059268

I also suspect scraper protection, as a plain `curl` fails with 403 (even if I spoof user agent):

```console
$ curl -I 'https://www.foodnetwork.com/recipes/food-network-kitchen/air-fryer-fried-shrimp-8059268'
HTTP/2 403
mime-version: 1.0
content-type: text/html
content-length: 464
cache-control: max-age=0
expires: Thu, 26 Dec 2024 15:57:36 GMT
date: Thu, 26 Dec 2024 15:57:36 GMT
set-cookie: layout=DESKTOP; path=/
set-cookie: __ds_loc_country=US; path=/; domain=.foodnetwork.com
set-cookie: __ds_loc_state=NM; path=/; domain=.foodnetwork.com
vary: User-Agent
server-timing: ak_p; desc="1735228656043_399338645_418606152_25_8642_38_56_15";dur=1
$
$ curl --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:62.0) Gecko/20100101 Firefox/62.0" -I https://www.foodnetwork.com/re
cipes/food-network-kitchen/air-fryer-fried-shrimp-8059268
HTTP/2 403
mime-version: 1.0
content-type: text/html
content-length: 464
cache-control: max-age=0
expires: Thu, 26 Dec 2024 15:58:14 GMT
date: Thu, 26 Dec 2024 15:58:14 GMT
set-cookie: layout=DESKTOP; path=/
set-cookie: __ds_loc_country=US; path=/; domain=.foodnetwork.com
set-cookie: __ds_loc_state=NM; path=/; domain=.foodnetwork.com
vary: User-Agent
server-timing: ak_p; desc="1735228694042_399338635_2258563962_22_8673_41_44_15";dur=1
```

But it loads fine from the same machine in Firefox.

Interestingly, it looks like it works if I include the `--compressed` flag (as well as spoof user agent):

```console
$ curl 'https://www.foodnetwork.com/recipes/food-network-kitchen/air-fryer-fried-shrimp-8059268' \
    --compressed \
    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0'
HTTP/2 200
content-type: text/html;charset=utf-8
strict-transport-security: max-age=63072000; includeSubDomains
last-modified: Thu, 26 Dec 2024 15:56:13 GMT
accept-ranges: bytes
content-encoding: gzip
access-control-allow-origin: *
access-control-allow-method: GET
content-security-policy: frame-ancestors 'self';
content-length: 88727
cache-control: max-age=3329
expires: Thu, 26 Dec 2024 16:57:11 GMT
date: Thu, 26 Dec 2024 16:01:42 GMT
vary: Accept-Encoding
set-cookie: layout=DESKTOP; path=/
set-cookie: __ds_loc_country=US; path=/; domain=.foodnetwork.com
set-cookie: __ds_loc_state=NM; path=/; domain=.foodnetwork.com
vary: User-Agent
server-timing: ak_p; desc="1735228902481_399338574_35083294_1060_8198_44_42_15";dur=1
```
