### ISSUE TITLE
Feature Request : extra fields

### ISSUE THREAD

**Issue by Web-svg** [nextcloud/cookbook#185]
Hi,
Many thanks for this great apps.
I am able to import automatically many saved page from cookido/thermomix site where I own an account (I have tried with ~20 recipes so far).

I have noticed that extra areas exist like nutritional informations, advice,tips an usefool accessories areas are part of the recipe description and are not imported as of today.

Does it make sense to think about them and have assocated field/data taken into account and imported as well ?
Attached screenshots from what I get with original saved page and imported one within NC 18.0.3. and 0.6.3 app.
![2020-04-03 10_37_32-Livre de recettes - Fwatc](https://user-images.githubusercontent.com/63095113/78341151-816ae800-7597-11ea-8922-44f32c2d5e11.png)
![2020-04-03 10_36_19-Cookidoo® - Tartare de saumon frais](https://user-images.githubusercontent.com/63095113/78341170-89c32300-7597-11ea-97ab-8df049fabd54.png)

[view-source.txt](https://github.com/mrzapp/nextcloud-cookbook/files/4425968/view-source.txt)

**Comment by mrzapp** [comment]
Yes, we are missing nutritional fields and perhaps also tools from our importer. I will add it to our `0.7.0` milestone.

**Comment by mrzapp** [comment]
Related to #225
