### ISSUE TITLE
[Feature Request] Ingredient calculator

### ISSUE THREAD

**Issue by Killerkomando** [nextcloud/cookbook#1884]
It would be really cool if you could adjust the number of people and then adjust the amount of ingredients as well. This would simplify the whole calculation. 

A very good site that has this feature is currently the website Chefkoch.de (German recipe site):

Here is a link to the feature:
[Chefkoch.de](https://www.chefkoch.de/rezepte/2345941373128983/Fischfilet-mit-Limettenbutter-und-Linsen-Risotto.html?portionen=5)

I would be very happy if this feature would be integrated.

**Comment by seyfeb** [comment]
We may reopen this issue if I misunderstood your request. On the linked site I see the option to adjust the number of servings which results in updated ingredients. This is already implemented (see #116 with #1573 ) but not yet released.

However, I'm not sure what you mean by "then adjust the amount of ingredients as well". I do not see such behavior on the linked site and suppose you simply mean the recalculation of servings. I this is not the case, please explain in more detail and we can reopen the issue!
