### ISSUE TITLE
Internal Server Error after upgrade to 0.10.3

### ISSUE THREAD

**Issue by nivekznews** [nextcloud/cookbook#1919]
**Description**
```
[no app in context] Fehler: Exception: syntax error, unexpected '|', expecting variable (T_VARIABLE) in file '/www/htdocs/xxxxx/websites/nextcloud/apps/cookbook/lib/Helper/Filter/JSON/AbstractJSONFilter.php' line 29 at <<closure>>

0. /www/htdocs/xxxxx/websites/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(["OC\\Core\\Cont ... "], "getProviders")
1. /www/htdocs/xxxxx/websites/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OC\\Core\\Contr ... r", "getProviders", ["OC\\AppFramewo ... "], ["ocs.core.UnifiedSearch.getProviders"])
2. /www/htdocs/xxxxx/websites/nextcloud/ocs/v1.php line 64
   OC\Route\Router->match("/ocsapp/search/providers")
3. /www/htdocs/xxxxx/websites/nextcloud/ocs/v2.php line 23
   require_once("/www/htdocs/xxxxx ... p")

GET /cloud/ocs/v2.php/search/providers?from=%2Fcloud%2Fsettings%2Fadmin%2Flogging
from xx.xx.xx.xx by admin at 2023-12-04T20:43:55+00:00
```

**Reproduction**
1. Install v0.10.3
2. Reload nextcloud page
3. Open cookbook
4. Error is shown

**Expected behavior**
Cookbook should be shown

**Actual behavior**
Error page is shown. Nextcloud log contains error message mentioned in Description of this issue. 

**Screenshots**
![nextcloud-cookbook-error](https://github.com/nextcloud/cookbook/assets/1656210/26c84a6c-8cee-494c-a8c9-828fa3c5bd6a)

**Browser**
Firefox v120.0b9
Chromium 119.0.6045.159
On Linux Manjaro

**Versions**
Nextcloud server version: 25.0.13
Cookbook version: v0.10.3
Database system: MariaDB
PHP version: 7.4

**Comment by johnjaylward** [comment]
Having a similar but different error. 10.0.3 killed my cookbook

log snippet:

```
    "app": "index",
    "method": "GET",
    "url": "/index.php/apps/cookbook/",
    "message": "Could not resolve OCA\\Cookbook\\Helper\\Filter\\JSONFilter! Class \"OCA\\Cookbook\\Helper\\Filter\\JSONFilter\" does not exist",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0",
    "version": "27.1.0.7",
    "exception": {
        "Exception": "OCP\\AppFramework\\QueryException",
        "Message": "Could not resolve OCA\\Cookbook\\Helper\\Filter\\JSONFilter! Class \"OCA\\Cookbook\\Helper\\Filter\\JSONFilter\" does not exist",
        "Code": 0,
        "Trace": [
            {
                "function": "OC\\AppFramework\\Utility\\{closure}",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->",
                "args": [
                    "*** sensitive parameters replaced ***"
                ]
```

**Comment by johnjaylward** [comment]
> Having a similar but different error. 0.10.3 killed my cookbook
> 
> log snippet:
> 
> ```
>     "app": "index",
>     "method": "GET",
>     "url": "/index.php/apps/cookbook/",
>     "message": "Could not resolve OCA\\Cookbook\\Helper\\Filter\\JSONFilter! Class \"OCA\\Cookbook\\Helper\\Filter\\JSONFilter\" does not exist",
>     "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0",
>     "version": "27.1.0.7",
>     "exception": {
>         "Exception": "OCP\\AppFramework\\QueryException",
>         "Message": "Could not resolve OCA\\Cookbook\\Helper\\Filter\\JSONFilter! Class \"OCA\\Cookbook\\Helper\\Filter\\JSONFilter\" does not exist",
>         "Code": 0,
>         "Trace": [
>             {
>                 "function": "OC\\AppFramework\\Utility\\{closure}",
>                 "class": "OC\\AppFramework\\Utility\\SimpleContainer",
>                 "type": "->",
>                 "args": [
>                     "*** sensitive parameters replaced ***"
>                 ]
> ```

Interesting. I had another plugin that was causing issues ("Write support for LDAP"). After I disabled it, the Cookbook plugin started working again with no issues.

Seems that is another plugin fails it may cascade into other plugins if they are poorly behaving.

**Comment by nivekznews** [comment]
> @nivekznews, what PHP Version are you running? I would guess pre-8.0, am I right?

I am running php version 7.4

**Comment by christianlupus** [comment]
OK, I got the point. Will handle this soon.

**Comment by christianlupus** [comment]
Let's see, what happens with the 0.10.4 version, @nivekznews. Please report back.

**Comment by Whitie** [comment]
I have the error with 0.10.4 now, running PHP 8.1.26.
0.10.3 worked without a problem (server version is 27.1.4).
