### ISSUE TITLE
unknown class in 0.10.3

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1921]
> Having a similar but different error. 0.10.3 killed my cookbook
> 
> log snippet:
> 
> ```
>     "app": "index",
>     "method": "GET",
>     "url": "/index.php/apps/cookbook/",
>     "message": "Could not resolve OCA\\Cookbook\\Helper\\Filter\\JSONFilter! Class \"OCA\\Cookbook\\Helper\\Filter\\JSONFilter\" does not exist",
>     "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0",
>     "version": "27.1.0.7",
>     "exception": {
>         "Exception": "OCP\\AppFramework\\QueryException",
>         "Message": "Could not resolve OCA\\Cookbook\\Helper\\Filter\\JSONFilter! Class \"OCA\\Cookbook\\Helper\\Filter\\JSONFilter\" does not exist",
>         "Code": 0,
>         "Trace": [
>             {
>                 "function": "OC\\AppFramework\\Utility\\{closure}",
>                 "class": "OC\\AppFramework\\Utility\\SimpleContainer",
>                 "type": "->",
>                 "args": [
>                     "*** sensitive parameters replaced ***"
>                 ]
> ```

_Originally posted by @johnjaylward in https://github.com/nextcloud/cookbook/issues/1919#issuecomment-1839576504_
            
Could you please provide a full trace to see? I am unsure if there is something important there but I have the problem that I cannot track it down to a concrete location. I was hoping for a hint there...

**Comment by johnjaylward** [comment]
[cookbook_trace.json](https://github.com/nextcloud/cookbook/files/13552321/cookbook_trace.json)

**Comment by johnjaylward** [comment]
as noting in the original issue https://github.com/nextcloud/cookbook/issues/1919#issuecomment-1839678213


> I had another plugin that was causing issues ("Write support for LDAP"). After I disabled it, the Cookbook plugin started working again with no issues.
> 
> Seems that if another plugin fails it may cascade into other plugins if they are poorly behaving.

**Comment by johnjaylward** [comment]
issue in the other plugin that cascaded here: https://github.com/nextcloud/ldap_write_support/issues/608

**Comment by christianlupus** [comment]
If you reactivate the LDAP plugin, is the cookbook failing again?

The file OCA\\Cookbook\\Helper\\Filter\\JSONFilter was moved to a new location. So, assuming the installation is not broken, I would guess that the file location was somehow cached.

**Comment by johnjaylward** [comment]
That may be it... I did restart my apache server as well, which would have cleared the cache.

Re-enabled the LDAP plugin and cookbook still works. So the cookbook issue may have just been cache related.

**Comment by christianlupus** [comment]
If you are using Apache with mod_php and enabled opcache in PHP, the restart was exactly the solution to the caching problem. I guess that will be it.

I close this here, if it returns or anyone else runs into it, we can reopen anytime.
