### ISSUE TITLE
Fehler	cookbook	OCP\AppFramework\QueryException: Could not resolve OCP\IL10N! Class can not be instantiated

### ISSUE THREAD

**Issue by sreutter** [nextcloud/cookbook#1954]
**Description**
cookbook does not work in the newest version on nc 27.1.4. (cookbook 0.10.4)

**Reproduction**
1. Try to click on the cookbook symbol
2. there is directly an internal server error

**Expected behavior**
normal operation of the cookbook app

**Actual behavior**
you get an internal server error

**Screenshots**
![grafik](https://github.com/nextcloud/cookbook/assets/12584679/8cfd43bf-5124-4695-94c3-8ceb125daffa)

**Browser**
Firefox 120

**Versions**
Nextcloud server version: 27.1.4
Cookbook version: 0.10.4
Database system: MariaDB

**Comment by christianlupus** [comment]
Hey. Where did you find the error message? Was there more?

I am asking because the IL10N interface is quite old and stable. I just checked the spelling. Nothing seems to be wrong and the CI test have passed so far as well. I can use the app both on the latest matter as well as the 27 Nextcloud server. 

So, either there is something more to your setup that makes a difference, or there is some basic problem with your setup anyways. Other apps are working as expected?

**Comment by sreutter** [comment]
Hello,
there were no problems in former nextcloud versions, <27.1.4, as far as i remember.
other apps all work.
there is one more failure message: 
OCP\AppFramework\QueryException: Could not resolve OCA\Cookbook\Helper\Filter\JSONFilter! Class "OCA\Cookbook\Helper\Filter\JSONFilter" does not exist
both found in "Protokollierung" in the Admin section.
could it be something php related? php was installed via the official php repo, not the debian repo.

**Comment by sreutter** [comment]
Also,
habe rausgefunden, was das Problem war.
Ich hatte zuletzt redis installiert, um die Einrichtungswarnung wegzukriegen. 
ich habe jetzt redis für die eine Instanz wieder deaktiviert - und siehe da, jetzt geht cookbook wieder (auf beiden Instanzen).
ein weiterer Fehler war tatsächlich auch in der Notes App. Die hat zwar in Instanz 1 noch funktioniert, nicht aber in Instanz 2.
Ich lasse das gerade mal so auf deutsch stehen, hoffe das ist ok. Übersetzung vom Computer...

So,
found out what the problem was.
I had last installed redis to get rid of the setup warning. 
I have now deactivated redis again for one instance - and lo and behold, cookbook is working again (on both instances).
Another error was actually also in the Notes app. It still worked in instance 1, but not in instance 2.
I'll just leave it in German, hope that's ok. Translation from the computer...

**Comment by christianlupus** [comment]
Ok, thanks for reporting back!

Kein Problem, ich spreche deutsch als Muttersprache :smile:.

It is interesting that Redis was able to break the app as we are not doing anything with it actively. Although, we got plenty issues recently about redis, so it would be nice to know the reason for it.

All I could think was to restart both redis and the web server in orderr to clean out any caches. If you find more information, I would be grateful if you shared.

I will close this issue as it seems unrelated with the actual cookbook app.
