### ISSUE TITLE
Nutrition removal unclear

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1967]
> Unclear what `----` option is supposed to mean => Accidentially selecting it deletes line
> 
> If it is supposed to delete a line, my suggestion would be to better remove this option (which is not an actual option) and add a trash can symbol next to the line instead.

Yes, it is way to remove an entry from the list of nutrition data. So, yes, it should remove the line.

Adding a trash can might be better in UI but I wanted to avoid doing more changes to the components if possible.

_Originally posted by @christianlupus in https://github.com/nextcloud/cookbook/issues/1950#issuecomment-1852048243_
            
A better UI should be chosen for removing a nutrition should be found.

Depends on #1950

**Comment by seyfeb** [comment]
Closed by ##1978
