### ISSUE TITLE
Separator text line to group list of ingredients and list of instruction steps

### ISSUE THREAD

**Issue by turnbeutel** [nextcloud/cookbook#1999]
For better readability it would be nice to be able to enter _separating text lines_ between the **list of ingredients** or the **list of instruction steps** to group steps according to their area. For instance, to bake a Quiche you need to have a dough and a filling. 

------ Dough -------
- 1 kg flour
- 2 eggs
- ....

------ Filling -------
- 2 Eggs
- 4 Peppers
- 2 onions
- - ...

These separating/grouping lines could have some escape sequence in them to prevent them be included in the recalculation process of the portion calculator

<img width="476" alt="Bildschirmfoto 2023-12-15 um 20 56 08" src="https://github.com/nextcloud/cookbook/assets/9333180/9eef8dd3-6328-4a1a-89a9-eb9219b38bc6">

**Comment by christianlupus** [comment]
Eventually, we could add some margin for the headings to separate them visually.

**Comment by seyfeb** [comment]
@turnbeutel Are you aware of the `## Title` syntax for creating subtitles? Please check #311

**Comment by turnbeutel** [comment]
@seyfeb Thanks for sharing this hint, I didn't know this syntax yet. Looks like my wish is fulfilled already. Many thanks.
