### ISSUE TITLE
Handle file access issues more smoothly

### ISSUE THREAD

**Issue by linuxsquad** [nextcloud/cookbook#2010]
[Cookbook_Err_log.json](https://github.com/nextcloud/cookbook/files/13703656/Cookbook_Err_log.json)

**Description**
After applying 10.5 update server error re-appeared (previously Ive opened a ticket re: this https://github.com/nextcloud/cookbook/issues/1806) 

**Reproduction**
1. Apply 10.5. update 
2. Go to Cookbook icon
3. Browser shows an error message 

**Screenshots**
The same screenshot as https://github.com/nextcloud/cookbook/issues/1806

**Browser**
Chromium on Linux

**Versions**
Nextcloud server version: 27.1.5 
Cookbook version: 0.10.5 (updated from 0.10.3)
Database system: MariaDB

**Comment by linuxsquad** [comment]
You provided me a path file (https://github.com/nextcloud/cookbook/issues/1806) and after applying it to the 10.5 code, the issue is fixed.

**Comment by christianlupus** [comment]
I would create a fix by just ignoring any failed files. That way, the error would be gone but reindexing errors will maybe get unnoticed.
