### ISSUE TITLE
Add subsections for ingredients/instructions

### ISSUE THREAD

**Issue by tomse** [nextcloud/cookbook#2022]
**Is your feature request related to a problem? Please describe.**

It would be nice to have the opportunity to split up the ingredients list into subsections.
and instructions

**Describe the solution you'd like**

have the possibility to split the ingredients list into subsections with a small headline.

i.e.
**Dough**
10g sugar
500g flour
50ml water
2 tsp salt

**Filling**
2 tblspoon cinnamon
2 tblspoon sugar
50g butter

**Describe alternatives you've considered**

in order to have the servings work a number is required, which isn't pretty

0.01 Dough
10g sugar
500g flour
50ml water
2 tsp salt
0.01 Filling
2 tblspoon cinnamon
2 tblspoon sugar
50g butter

**Comment by seyfeb** [comment]
See #311
