### ISSUE TITLE
Link other recipies

### ISSUE THREAD

**Issue by dennisrall** [nextcloud/cookbook#2043]
How hard would it be to implement a feature to link to other recipes? I checked the recipe schema, but didn't find a matching field. However, I think it would be great to link side dishes to a main course.

**Comment by christianlupus** [comment]
You mean like already implemented 🫣😁?

There is a feature that `[this example](#r/123)` will be replaced by a link with the text `this example` and the URL of the recipe with id 123.

You should see a pop-up when you type the `#` if I am correct. 

Please report back if that is what you are looking for.

**Comment by seyfeb** [comment]
A slight correction to the answer: It would be either

```
[other recipe](#/recipe/123)
```

for the recipe with id `123` using plain markdown or you could in a text box hit `#` and this would open a popup that allows to select a recipe, which in turn would input something like

```
 #r/123 
```

(without the Markdown brackets) which would render as the linked recipe name acting as a link to the selected recipe.
