### ISSUE TITLE
unable to activate/download after NC28 upgrade

### ISSUE THREAD

**Issue by andyrtr** [nextcloud/cookbook#2058]
After Upgrade to NC28 an cookbook 0.11.0 I can't enable it in NC app settings anymore getting "Exception
Could not download app cookbook could not enable apps"

Happens in Firefox and Chromium as well. NC is running under apache web server 2.4.58-1 and mariadb 11.2.2-1.

{
  "reqId": "VArADj79h1ADm2KxT3cb",
  "level": 3,
  "time": "2024-01-13T11:09:21+00:00",
  "remoteAddr": "192.168.1.2",
  "user": "andyrtr",
  "app": "settings",
  "method": "POST",
  "url": "/settings/apps/enable",
  "message": "could not enable apps",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "version": "28.0.1.1",
  "exception": {
    "Exception": "Exception",
    "Message": "Could not download app cookbook",
    "Code": 0,
    "Trace": [
      {
        "file": "/usr/share/webapps/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
        "line": 451,
        "function": "downloadApp",
        "class": "OC\\Installer",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 230,
        "function": "enableApps",
        "class": "OCA\\Settings\\Controller\\AppSettingsController",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 137,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/Route/Router.php",
        "line": 315,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/base.php",
        "line": 1069,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/index.php",
        "line": 39,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/usr/share/webapps/nextcloud/lib/private/Installer.php",
    "Line": 389,
    "message": "could not enable apps",
    "exception": {},
    "CustomMessage": "could not enable apps"
  }
}

[nextcloud.log.txt](https://github.com/nextcloud/cookbook/files/13927763/nextcloud.log.txt)

**Comment by christianlupus** [comment]
When the update service wants to download the app and you have it already locally, there is a problem with your installation. The enable should not do the download unless the app was not previously installed. 

Can you confirm the version 0.11.0 is already present locally?

**Comment by andyrtr** [comment]
Yes, I've installed the cookbook app using a self built local package.

**Comment by andyrtr** [comment]
All files are copied over to /usr/share/webapps/nextcloud/apps/cookbook-0.11.0 / - I had no issues with NC27 and 0.10.2 doing the same before.

**Comment by christianlupus** [comment]
It must be named `cookbook`. The version must not be there.

**Comment by andyrtr** [comment]
Thanks. That helped. Now I can enable the app and the icon is shown in top bar. 

The web page remains empty for cookbook. That seems to be a different issue. But I can at least access it using the an Android App.

**Comment by christianlupus** [comment]
If the web page is still empty, the question is: have you installed the dependencies and built the frontend?
```
composer i
npm ci
npm run build
```
