### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by boyi01** [nextcloud/cookbook#207]
Are there Any Android app's that allow to usw thus App one Smartphone ?

If not I plan to make one

**Comment by Teifun2** [comment]
I've started a flutter project a little time ago but as i have no experience and not to much time it is going very slowly. As far as i know there is no other project going on.
![flutter](https://user-images.githubusercontent.com/7461832/80645149-051ad600-8a6b-11ea-8f90-db61cd7357f5.gif)
That's basically how far i got :P 
I'm in the matrix chat, so if you want to contact me directly there if you need something from me.
But if you want to start your own app that's also fine for me.

**Comment by boyi01** [comment]
That's cool, i would be my first app to... but maybe i'm a little advanced in Programming
but where i find the matrix chat :D

**Comment by cgudea** [comment]
I've been messing around with some new android libraries and have been working on a recipe app that uses the nextcloud-cookbook files as its data source

![output](https://user-images.githubusercontent.com/2689445/81213817-76580d00-8fc6-11ea-9baf-5607daf07533.gif)

**Comment by logos88** [comment]
It would be great if the opensource app [openrecipes](https://gitlab.com/ddorian/openrecipes) got cookbook syncronisation

**Comment by nobodywasishere** [comment]
What if we started with the Nextcloud Notes app as a base, that way we already have authorization/etc out of the way, alongside fitting in with the rest of the NC apps? It may take some time to figure out how the app works, though, and figure out how to get it to work with recipes instead of notes. https://github.com/stefan-niedermann/nextcloud-notes

**Comment by boyi01** [comment]
We're writting a App

**Comment by Teifun2** [comment]
To elaborate a little. We started a flutter project to create an android and possibly also an IOS app for nextcloud-cookbook. Under these circumstances flutter is very desirable as it has cross platform capabilities. The idea of using existing authorization is a good one but as nextcloud-notes is developing in java there is not much we can directly use for a flutter / dart project.

https://github.com/Teifun2/nextcloud-cookbook-flutter
The flutter project is in its early stages as I didn't have any experience with flutter nor Kotlin. @boyi01 is also helping and we are confident that we can get a working app. 

If anyone would like to pursue the approach of forking nextcloud-notes i would encourage them as it also seems like a very good idea!

**Comment by mrmenb** [comment]
I wanted to learn about Android App programming for some time, and used this for myself as a testcase. I came up with a basic app which does list and detailled displays the recieps from nextcloud-cookbook. 
To do so I sync the recipes folder to my phone and have a visual representation for each recipe whithin the app. At the current state it is possible to change some properties (cookTime ect.) from whithin the app. 
I did put it on GitHub if someone is interested: [https://github.com/mrmenb/ncCookbook](https://github.com/mrmenb/ncCookbook)

**Comment by mrzapp** [comment]
Reopening, as this seems to be the go-to discussion for this topic :)

**Comment by ps2sunvalley** [comment]
Just wanted to say that this NC app is awesome! But to add/piggyback on the feedback from others would be that android/iOS apps or at least a way to view the recipes easily on a phone/tablet is a must.  I like to use my iPad in the kitchen with me to reference a recipe and while having them all centralized and self hosted is great, referring to them on my computer in the other room is less than great.  Anyways, I see that such an app is in development, just wanted to show more support for the project.

**Comment by boyi01** [comment]
If you want, i guess you can test the app on IOS

**Comment by hitam4450** [comment]
Sorry, I do use ANDROID !

**Comment by boyi01** [comment]
the app is in flutter, so usable in android and IOS

**Comment by ps2sunvalley** [comment]
> If you want, i guess you can test the app on IOS

Sure, whenever it is at a point to test I'd be happy to use and provide feedback

**Comment by hitam4450** [comment]
> the app is in flutter, so usable in android and IOS

Ok, thanks for your feedback !

**Comment by Mic92** [comment]
By the way depending on how motivated you are it is also possible these days to develop iOS apps in a VM: https://github.com/kholia/OSX-KVM Otherwise I might have a look at this at some point. I can debug/test both iOS/Android.

**Comment by IzzySoft** [comment]
[Nextcloud Cookbook](https://apt.izzysoft.de/fdroid/index/apk/de.micmun.android.nextcloudcookbook) is available in my repo if anyone is interested. Still beta and actively developed, it already runs quite stable (v0.30.0 has a little scrolling issue which will be solved in the next version, expected within a week or so). It's a viewer only, and relies on the data having been synced to the device by other means (e.g. via the Nextcloud Android app). Works well, you might wish to mention it. Once its author declares it "stable", it will move to F-Droid.org.

**Comment by Teifun2** [comment]
@IzzySoft That looks very nice!

We have also been working on a android app developed with flutter such that it can then also be used for iOS.
https://github.com/Teifun2/nextcloud-cookbook-flutter

If somone wants to check it out. Development is a little slow but continuous. I'm still looking for feedback so please come and test the app. There is an internal testing currently going on over Google Play or otherwise i will distribute  apks.

**Comment by hitam4450** [comment]
Hi, I installed the app and it looks good!

keep up your good work !

**Comment by IzzySoft** [comment]
@Teifun2 if you want your app added to my repo as well, I'd recommend [tagging your releases](https://github.com/Teifun2/nextcloud-cookbook-flutter/releases) and attaching the corresponding `*.apk` to the tags, so my updater can pick them. Then ping me for the "initial pick" :wink:

**Comment by Teifun2** [comment]
@IzzySoft That sounds awesome! I added the release tags and for the latest one i attached the apk. Whats next?

**Comment by IzzySoft** [comment]
@Teifun2 I've moved this [to your app's issue tracker](https://github.com/Teifun2/nextcloud-cookbook-flutter/issues/12). Anyone interested is welcome to follow up.

**Comment by christianlupus** [comment]
I will close this as no discussion has been done here and this is most probably not the right place anyways: we have different 3rd party apps for mobile devices and bugs/enhancements/... should be discussed in their repositories.

If there really is the need to keep this open, feel free to write a comment and we can consider reopening.
