### ISSUE TITLE
[FEATURE REQUEST] Add "Sub-Section" text to Ingredients and Instructions sections

### ISSUE THREAD

**Issue by pajades** [nextcloud/cookbook#2089]
Many (if not all) of the recipe collection apps I've used have the ability to add non-ingredient entries into the ingredient list and non-step entries into the instruction list by enclosing the text in [square brackets], thereby creating a sub-heading (or sub-section) within the list such as:
[WET]
1 egg
1 cup milk
[DRY]
1 cup flour
1 tsp baking soda
1/4 cup sugar

This would yield a display like:
**WET**
1 egg
1 cup milk
**DRY**
1 cup flour
1 tsp baking soda
1/4 cup sugar

**and the text in brackets is ignored by any scaling or quantifying functions.**

This same functionality extends to the instruction list:
[CRUST]
step 1
step 2
[FILLING]
step 1
step 2

This displays as:
**CRUST**
1. step 1
2. step 2

**FILLING**
1. step 1
2. step 2

**Comment by seyfeb** [comment]
See #311
