### ISSUE TITLE
Link to other recipes with hashes

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/cookbook#209]
Allow linking of a recipe as a dependency for another recipe.
eg. There are several basic dough which are used for different pastries

- [ ] May use `#recipes/2443839` as shortcode for a cooking step in edit mode.
  - [ ] If a # is inserted in edit mode show a list of recipe for inserting.
  - [ ] Show last used recipe for inserting first.
- [ ] Show the recipe steps inside and add ingredients to the list in the main recipe.

**Comment by mrzapp** [comment]
The first time around, let's just implement the "mention" feature using hashes and ids, like we mention issues here on GitHub. Then we can expand on that later

**Comment by seyfeb** [comment]
I started playing around with this and wondered: What if someone wants to write sth like: 

"This is the #1 of all Hummus recipes in the world". 

Should we require the user to escape the hash? Like

"This is the \#1 of all Hummus recipes in the world"

and render it accordingly in the recipe viewer?

**Comment by Mannshoch** [comment]
If you check that Recipe-ID do not start at 0 or a Receipe ID start with a special prefix like R// so you have to write #R//1234 it may work.
