### ISSUE TITLE
Import recipe from copy-paste (text)

### ISSUE THREAD

**Issue by sunjam** [nextcloud/cookbook#2100]
**Is your feature request related to a problem? Please describe.**
Have an option to import from text as opposed to a url.

**Describe the solution you'd like**
Writing in the creation menu is okay, but I think the parse errors for a lot of sites could also be negated by copy-pasting the relevant text to avoid confusion.

**Describe alternatives you've considered**
Writing in everything by hand.  Cookbook seems to understand what the different parts of the recipes are, but is confused by the majority of recipe sites, which includes walls of texts and ads, which live before and after the actual recipe.  Thanks for considering either way!

**Comment by christianlupus** [comment]
First, we are not parsing the sizes in detail. Instead, the sizes provide a way for search engines to extract the relevant parts of a recipe in machine-readable form. (you might have seen previews of recipes and stuff on e.g. Google) if there was ads added, the site owner is to be blamed.

Apart from that, you know that there are in fact a few features included to simply the insertion of raw text? For example the instructions and ingredients should allow to paste multiline text that is split automatically. 

How would the partying of a plain text work on your opinion? How to distinguish the instructions from ingredients and tools? What about the other meta data like URL, author, dates, title and image?

**Comment by sunjam** [comment]
I'll work my way through more recipes and write something up, and try to include some mock ups or screenshots for how the process goes.

**Comment by Eisbergsalat** [comment]
Is this feature really not coming or did it get automatically get marked as "not planned"?
I am actually really hoping, this feature or even # 2584 will come

👍
