### ISSUE TITLE
Fix regression introduced with Typescript

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#2144]
With 601de51 a regression was introduced into the code base. I do not know why the CI did not trigger a warning/error but with that commit the check of eslint fails.

To check this, simply checkout the corresponding commit and run `npm ci && npm run eslint`.  Eslint reports a dozen errors like this:
```
/home/christian/Dokumente/nextcloud-docker-dev/workspace/server/apps-extra/cookbook/src/components/AppControls/AppControls.vue
  201:23  error  Unexpected use of file extension "js" for "@nextcloud/vue/dist/Components/NcActions.js"       import/extensions
  202:28  error  Unexpected use of file extension "js" for "@nextcloud/vue/dist/Components/NcActionButton.js"  import/extensions
  204:22  error  Unexpected use of file extension "js" for "@nextcloud/vue/dist/Components/NcButton.js"        import/extensions
  205:27  error  Unexpected use of file extension "js" for "@nextcloud/vue/dist/Components/NcActionInput.js"   import/extensions
  206:27  error  Unexpected use of file extension "js" for "@nextcloud/vue/dist/Components/NcLoadingIcon.js"   import/extensions

```

Just dropping the extension from the `import` statements will render the app non-buildable. For the parent commit, the linter seems to be perfectly happy.

As I am not used to and not experienced with typescript, could you have a look, @seyfeb?

**Comment by seyfeb** [comment]
I justed started with ts, too, but I did not notice the issue 🤔  I made some changes in #2115 and have no troubles building the app -  would you mind trying if you have any issues there?

**Comment by christianlupus** [comment]
The building of the app is not the problem here. The checked-in code will work. However, the eslint checker will fail on the current code base. This will cause trouble with anz PR that has the JS code updated. Also, my hooks trigger and reject the commit at the moment.

The code stops to build successfully, once you try to be compatible with the complaints of eslint and remove the `.js` suffix. Then, the bundler no longer detects the dependencies and fails to build the app.

Same happens on the commit 6f9c883231 (current refactor/add-scheama-js-classes).

**Comment by christianlupus** [comment]
Very strange. I tried again on a plain new clone of the code base. There, eslint is not complaining anymore. Checking the CI once more, I saw the problem was somewhere completely different (unrelated to eslint).
