### ISSUE TITLE
When creating a recipe or editing is , it randomly not save the last ingredient or the last instruction (or both)

### ISSUE THREAD

**Issue by Tonic8** [nextcloud/cookbook#2174]
**Description**
When creating a new recipe it won't save the last ingredient or the last instruction (or both). when editing to add the last ingredient or the last instruction, it won' save it again. to resolve the issue 
- i must add the ingredient i need, +  1 more (fake) ingredient or the last intruction + 1 more instruction (like "enjoy!")

it's seems to be random.

**Reproduction**
1. Create a recipe
2. add 6 ingredients
3. add 6 instructions
4. Save
5. count the ingredient list saved
6. count the instructions list saved

**Expected behavior**
:) the right numbers of ingredients or and instructions

**Actual behavior**
when it occur checking the json file result the last ingredient and/or instruction is not present.

**Screenshots**

- ![Instructions manquantes01](https://github.com/nextcloud/cookbook/assets/18634390/bd4d8225-d57b-40ab-b738-aaa05accf5bd)

- ![Instructions manquantes02](https://github.com/nextcloud/cookbook/assets/18634390/5dc3cfd0-4450-4fa0-9810-d1b53b23f462)

- **editing the recipe to add the missing instruction and adding an extra instrcution**

- ![Instructions manquantes03](https://github.com/nextcloud/cookbook/assets/18634390/13a8270d-1372-4366-a3b6-f1f02696ea6d)

- ![Instructions manquantes04](https://github.com/nextcloud/cookbook/assets/18634390/3677ab23-7f74-4064-a550-bedc749b3f7f)

**Browser**
Chrome 122.0.6261.95 on windows 10

**Versions**
Nextcloud server version: 27.1.6
Cookbook version: 0.10.5
Database system: MariaDB

**Comment by tomdeck** [comment]
I have a very similar (potentially the same) issue: when adding instructions manually, these are not saved. One work-around I found was: add the new instruction; move it up; move it back down to the initial position; save

**Comment by Tonic8** [comment]
il will try , as fo rnow i add 1 extra inxtruction and 14 extra ingredient before saving the first time and then remove them

**Comment by Tonic8** [comment]
i just added 20 recipes today and had no issue.

i'm now running nextcloud 27.1.8 (previously on 27.1.6), but still with Cookbook 0.10.5

any suggestion or we close the ticket?

**Comment by christianlupus** [comment]
It will close itself unless someone steps in. Let's see if others have the problem as well.

**Comment by david-aigner** [comment]
Same issue here!
Version 0.11.0
Nextcloud Hub 8 (29.0.2)

**Comment by christianlupus** [comment]
There seems still to be a user having the issue.

@david-aigner, unfortunately, I cannot reproduce it. Would you be willing to track down the problem on a more technical level? I would try to guide you and see if we can rule out if it is a frontend or backend issue. 
How reproducible is this for you? Can you somehow "trigger" the effect consistently, or is it _just_ happening from time to time?
