### ISSUE TITLE
Fraction to Decimal Conversion for Ingredients As Toggle Option

### ISSUE THREAD

**Issue by captaincouch** [nextcloud/cookbook#2257]
**Is your feature request related to a problem? Please describe.**

My partner, a heavy user of the app, has often found it frustrating when the fractions for ingredients are automatically converted to decimal amounts. It's much more difficult to visually parse and is generally, at least in our part of the world, not a way most people measure ingredients.

**Describe the solution you'd like**

A toggle feature to allow conversions in both fractions and decimals would be very much appreciated.

**Describe alternatives you've considered**

N/A

**Comment by christianlupus** [comment]
Generally, I understand your point. Is the original recipe given in fractions or decimal representation? If I remember correctly, the algorithm should stick with the existing notation method. If it is pure integer, I guess it falls back to decimals.

One difficulty I personally have (as I am from a decimally-oriented country): what are acceptable fractions? I mean, if the original recipe was for 6 servings and should contain 5/8 cups of water, a single serving would be 5/48 cups, Honestly, this looks very strange to me. Now, take the fact we want to have 7 servings, we are at 35/48 cups. This gets worse, once you consider larger recipes (think 10, 12 or 15 servings). How would you handle such fractions? Would you at some point round or go to decimals?

As I said: I have no native feeling for these fractions and personally find them unnerving as I cannot read them intuitively. Could you help me, so I can either implement myself or delegate to someone else the implementation of these calculations?
