### ISSUE TITLE
Do not redownload the url-image

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/cookbook#2259]
**Description**
If an URL is the base of a receip image and you edit it later. On save the Url try to redownload. If the image does not exist an error appear and you could not procceed.

**Reproduction**
1. Go to a receip
2. Click on edit something and save
3. See error

**Expected behavior**
No redownload of the image if the URL not changed.

**Actual behavior**
If an URL is the base of a receip image and you edit it later. On save the Url try to redownload. If the image does not exist an error appear and you could not procceed.

**Browser**
Firefox

**Versions**
Nextcloud server version: 28.0.4
Cookbook version: 0.11.0

**Comment by christianlupus** [comment]
@seyfeb with the upcoming changes in the frontend and the new class structure in the JS code, how is the URL of the image handled? Is it just kept as it is? I just want to avoid conflicts with the fix for this issue.
