### ISSUE TITLE
Changing the recipe folder has no effect

### ISSUE THREAD

**Issue by basvandenbrink** [nextcloud/cookbook#2274]
**Description**
Changing the recipe folder has no effect

**Reproduction**
1. Go to 'https://fqn/apps/cookbook'
2. Click on 'Cookbook settings'
3. Click on text box in 'Recipe folder'
4. Select a new folder using the folder OR typing the directory path directory (tried both)
5. Click Rescan library

**Expected behavior**
The UI is refreshed and showing the correct recipes

**Actual behavior**
The UI is refreshed and nothing changed. Going to the Setting will show the old Recipe folder

I also expected a POST request changing the config value in the Inspector. POST requests do show up when changing other config values.

Actually, capturing such request and replaying it with body `{"folder": "<new_dir>"}` does update the recipes folder correctly.

**Browser**
Tested with Firefox and Edge

**Versions**
Nextcloud server version: 28.0.4
Cookbook version: 0.11.0
Database system: PostgreSQL

**Comment by christianlupus** [comment]
This sounds like a pure frontend issue. If no request is made then the update cannot happen obviously. You even verified that the backend works as expected.

I tried it in my dev instance and cannot see this error right now. I would suggest to have a look at the upcoming v0.11.1 if  that fixes the problem (honestly, I did not check with the older 0.11.0 but only with master). If this is persistent, we have to look into the details on why this is not working exactly.
