### ISSUE TITLE
Add importer for WP Recipe Maker (Wordpress Plugin)

### ISSUE THREAD

**Issue by sedrubal** [nextcloud/cookbook#2384]
**Failing website:** https://biancazapatka.com/de/vegane-koettbullar-schwedische-hackbaellchen/

**Checking if valid metadata are present:** Yes, I check the source code of the website and found metadata.

**Cookbook version:** ? (I assume latest)

**Problem description (if applicable):**
The page cannot be imported. The error message is: "No parser found for the given import."

The website seems to use this WordPress Plugin: https://wordpress.org/plugins/wp-recipe-maker/

**Comment by nathanielhourt** [comment]
Should be fixed by nathanielhourt/cookbook@a022da704e4774ec29c31a1c8146e92d5bb7ad88
