### ISSUE TITLE
New install interal server error

### ISSUE THREAD

**Issue by Hellothere123890** [nextcloud/cookbook#2392]
**Description**
I have a new installation of Nextcloud using docker, when I install the app and click on the icon all i receive is an internal server error. 

**Reproduction**
1. Install next cloud
2. Download an enable cookbook
3. Click on the cookbook icon

**Expected behavior**
Be able to use the cookbook page

**Actual behavior**
internal server error, see screen shot

**Screenshots**
![nextcloud_error_screenshot](https://github.com/nextcloud/cookbook/assets/132856887/7df72bbe-98cf-4294-971c-2f9b61630a07)

**Browser**
Vivaldi
Arch linux extra 6.8.3381.44-1

**Versions**
Nextcloud server version: 29.0.2 (dockerhub latest)
Cookbook version: 0.11.0
Database system: MariaDB

(Edit: wrong screenshot)

**Comment by christianlupus** [comment]
I just tried with the development environemnt and I did not see a problem installing the app. Can you enable the debug mode and see if you can post the backtrace?

**Comment by christianlupus** [comment]
I meant to enable the debug mode by setting `'debug' => true` in `config.php` of your instance. That should make the error more verbose (reset to false after you are done). It will report in the frontend (browser) as well as the logs.

**Comment by Hellothere123890** [comment]
I was looking through the logs and this is the line that kept popping up that seems relevant to cookbook:
 `GET /apps/cookbook/ HTTP/1.1" 500 3255 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`

**Comment by joshtrichards** [comment]
You need to take a look at your *Nextcloud Server* log, not your web server log. Check `nextcloud.log` in your data directory. It should have the context for the error. An *Internal server error* is just a generic message when there's a serious enough problem to stop Nextcloud until whatever is going on is remedied.

**Comment by Hellothere123890** [comment]
Hello, I have decided to just reinstall next-cloud all over-again and install cookbook. It seems to be working fine now so I will just roll with it. Thank you for your help even though I wasn't every helpful along the way!
