### ISSUE TITLE
App stopped working, error when restart. 

### ISSUE THREAD

**Issue by Queerio123** [nextcloud/cookbook#2398]
Hello,
since some days (not sure when exactly, I noticed it yesterday) the cookbook app was down. 
It wasnt disabled by me, so it might be error-related. 

When I try to restart it, it produces an error: 

![image](https://github.com/nextcloud/cookbook/assets/146453815/34e4f47b-dfc1-46d0-a245-f3b7b77d6f4f)

**Versions**
Nextcloud server version: 28.0.7
Cookbook version: 0.11.1
Database system: mysql 10.5.15

**Comment by christianlupus** [comment]
Hello. 

I would almost bet that the installation of the 0.11.1 release failed for some reason in your instance and the files were not completely written to the drive. There should be (within the cookbook app folder) a folder appinfo with an info.xml file. I guess the least is missing at least. 

If that is the case, you could download the latest release, and just overwrite the app files (best make a backup).
