### ISSUE TITLE
Printing as PDF in Ubuntu 20.04 and Firefox 77.0.1 only prints 1 page.

### ISSUE THREAD

**Issue by RobRobM** [nextcloud/cookbook#242]
Printing a recipe as PDF in Firefox in Ubuntu only prints 1 page. Chrome works as expected. (Might not be a Cookbook issue)

[Gestoofde kip met zwarte olijven - example Firefox 77.0.1 and Ubuntu 20.04.pdf](https://github.com/mrzapp/nextcloud-cookbook/files/4745125/Gestoofde.kip.met.zwarte.olijven.-.example.Firefox.77.0.1.and.Ubuntu.20.04.pdf)

Ps. Missing steps 3 and 4 ;-)
3. Voeg de stukken kip toe en braad rondom aan. Bestrooi ze met zout en peper. Schenk de wijn en azijn erbij en laat deze bijna helemaal verdampen. Voeg de olijven en ansjovis toe en leg de deksel schuin op de pan en laat de kip in circa 40 minuten gaarstoven

4. Doe de kip en olijven over in een voorverwarmde schaal en serveer. Eet smakelijk!

**Comment by hitam4450** [comment]
Same here...

**Comment by mrzapp** [comment]
This is really odd. When using print media query emulation, it shows everything fine, but when actually printing, only the first page is displayed. This is clearly a bug in Firefox, since it works in every other browser I tested with, but let's keep it open, in case a workaround comes up.

**Comment by RobRobM** [comment]
F.y.i. recipes don't print as PDF at all in gnome-web 3.36.1 (WebKitGTK 2.28.2)

**Comment by e-jim** [comment]
Hello,

I'm sorry if I'm spamming you, but I just want to inform you that I noticed the same behaviour as described by @RobRobM using Firefox 78.7.0 ESR on Debian 11 (Bullseye).

It works correctly with Firefox 86.0b9 (current beta) on the same system.

Hope this helps.

**Comment by christianlupus** [comment]
I just installed a test VM on Debian 11. It is shipped with Firefox 91.11.0esr. The problem is not visible there. Please check if the problem is still persistent and can be reproduced with a current and updated OS. If yes, please provide installation steps (to set up a VM here for debugging).
