### ISSUE TITLE
Search is not Working Page not Found

### ISSUE THREAD

**Issue by poltrian** [nextcloud/cookbook#243]
Hello,

at both 7.1 & 7.2 search is not working. "Page not found"

**Comment by mrzapp** [comment]
@sam-19 would you mind looking into this one as well?

@mcorteel does this conflict with your implementation of global search?

**Comment by mcorteel** [comment]
The global search is completely undocumented... Basically, you do this:
```
this.searchTerm = null;
let searchFunction = (query) => {
    this.searchTerm = query;
};
let searchClearedFunction = () => {
   this.searchTerm = null;
};
let search = new OCA.Search(searchFunction, searchClearedFunction);
```
Of course, in a real life implementation, you would do something more with the two functions, but you get the gist!

**Comment by sam-19** [comment]
The search page should not even be accessible, but for some reason the disabled="true" on this line is not working.
https://github.com/mrzapp/nextcloud-cookbook/blob/3c1e7adf205948511ed03936f171496adb92bbe3/src/components/AppControls.vue#L9

Before it can be implemented, we need some sort of UI for it. Do we want to allow specific searches for recipe names, ingredients, tools, instructions, keywords, etc? And how do we present them on the search page? Do we want to allow AND/OR operands for complex searches? I would just remove the button from the UI for now and maybe think about how to implement it properly at some later time.

**Comment by mrzapp** [comment]
@sam-19 I think we should just reimplement the old search for now. It was located in the top bar and used the `main#search` route (`/search/{query}`). The search results would appear in the main view.

**Comment by sam-19** [comment]
Just an update, this is next on my list once I'm back from vacation.

**Comment by sam-19** [comment]
Okay, I have a pull request ready for this one as soon as @mrzapp has processed my previous PR. It has two functions, filter (for just filtering results in the current view by name without running any new queries) and an implementation of the search function. The Nextcloud Vue breadcrumb component has some limitations on how these can be displayed, so now they are under a three-dot menu on the index page breadcrumbs. I would have liked the search bar to open on the breadcrumb bar itself, but alas, it seems to be impossible at the moment.
