### ISSUE TITLE
über direkte ip-adresse in android keine verbindung

### ISSUE THREAD

**Issue by birinrw** [nextcloud/cookbook#2434]
welche einstellungen muß ich machen um direkt im heimnetz über android mit netzwerk-ip zugreifen zu können ??

**Comment by christianlupus** [comment]
Hallo.
Ich muss leider sagen, dass die Android-Apps nicht von uns (also den Maintainern von nextcloud/cookbook) verwaltet werden. Diese sind Drittapps, die andere Entwickler bereit stellen, basierend auf unseren publizierten Interfaces. Daher können wir leider keine (sinnvolle) Unterstützung an der Stelle anbieten.

Welche App ist es denn? Ggf kann man mal den entsprechenden Entwickler ansprechen?
