### ISSUE TITLE
Right on directorry for sharing needed

### ISSUE THREAD

**Issue by ewok2** [nextcloud/cookbook#2488]
NC : 29.0.6
Cookbook : 0.11.1

Not sure if it is a bug or a needed point...

I have a cookbook on my account.
I want to share it to other NC users.
I have share the directory reciepe to the other user in read only.
The first time you open cookbook in the other user NC web, it say the directory choosen should be write enable to allow other user to add reciepe. But it works for other user to read the reciepe.
But when the other user install an IOS App cookbook, the app succeed to connect to cookbook but canb show any reciepe.
=> as soon as you add writting right to the user the ios app see all the reciepe.

Idealy if cookbook could : 
- accept more than one directory (one with writting other not necessary)
- or accept a structure like "main"/book1/reciepe1 "main"/book1/reciepe2 "main"/book2/reciepe1
- or allow the app ios to works without wirting? but maybe this part is more to the IOS dev ;-)

**Comment by christianlupus** [comment]
This issue consists of multiple parts.

1. Fixing the iOS app. This _we_ cannot do. It is a third party app and you should ping them related to this issue.
2. Alolowing for structures recipes and multiple cookbooks. In fact this is already planned, see also #599 and #2196

I will thus close this issue as duplicate.
