### ISSUE TITLE
App: http Login "Zertifikatsfehler"

### ISSUE THREAD

**Issue by schokolab** [nextcloud/cookbook#2562]
Hi, 

I'm using the latest app version from the f-droid store. 
After installing the app I try to connect from the Android Cookbook app to nextcloud server. The error “Zertifikatsfehler” is displayed on the Android device.

Server is http://192.168.x.x
My Nextcloudserver needs no SSL-Certificate, it's only used in my local home network. 
Login with this credits is possible with any other Nextcloud Apps, eg. Nextcloud Notes

App: Latest Version from f-droid: 0.22.0
Android 15, Graphene OS

**Comment by christianlupus** [comment]
I am sorry, I cannot help here. This repo is only developing the NC cookbook app. The Android apps are developed externally. I have to close therefor here.
