### ISSUE TITLE
A new app for travellers

### ISSUE THREAD

**Issue by jaleel1618** [nextcloud/cookbook#2575]
Dear Developers,

I appreciate the effort put into this project. However, I would like to inquire if it is possible to create a separate application for travelers using the same templates as the cookbook. Most of the elements are already in place; it would only require changing some titles and adding an option to include videos.

Thank you for considering this suggestion.

**Comment by christianlupus** [comment]
This sounds very off-topic. Therefore I will close this issue now.

Anyways, if you have concrete questions, feel free to ask them, contact me directly, or ask on the forum (I am there as well trying to help in the development sub-forum).
