### ISSUE TITLE
Sharing recipe with other users or external users

### ISSUE THREAD

**Issue by nodiaque** [nextcloud/cookbook#2577]
Hello,

It would be great if there was a way to share recipe with other users (either per recipe or per cookbook) and allow both read only / full access to them for collaboration.

Allowing for read only guest would be a plus.

Thank you!

**Comment by nodiaque** [comment]
Yeah you have the share the folder, not the best thing since cookbook require a base path to work, you then need everyone to use the same basepath to collaborate.

**Comment by benchti** [comment]
hello  @nodiaque i think you could read this ticket https://github.com/nextcloud/cookbook/issues/120

**Comment by christianlupus** [comment]
Duplicate of #120 and #392
