### ISSUE TITLE
Sharing with family and friends

### ISSUE THREAD

**Issue by baxterblk** [nextcloud/cookbook#2589]
**Is your feature request related to a problem? Please describe.**
No problem. In-fact, quite the opposite! This feature request might be a selling point for others though!

**Describe the solution you'd like**
I would love to share recipes within my Nextcloud Cookbook with friends and family who do not have a Nextcloud account. Having either a "Share" function or a "Publish to Web" function to make it public would be fantasitc!

**Describe alternatives you've considered**
Alternatives? I have written recipes on notecards, put them in the mail, and waited for a response! Haha I'm kidding. But really, the only real alternative is to use the actual URL from the recipe or require them to create an account.

**Comment by benchti** [comment]
hello @baxterblk you could follow  and upvote this ticket https://github.com/nextcloud/cookbook/issues/120 .
