### ISSUE TITLE
SQLSTATE[HY000]: General error: 1114 The table 'oc_filecache' is full

### ISSUE THREAD

**Issue by jomuench** [nextcloud/cookbook#2601]
I am adding an URL on the webui to import a new entry from a website and get this error:

An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1114 The table 'oc_filecache' is full

nextcloud version = [Nextcloud Hub 9](https://nextcloud.com/) (30.0.2)
cookbook app version = 0.11.2

in nextcloud event log, I see entry:
`Undefined array key "id" at /var/www/html/custom_apps/cookbook/lib/Helper/Filter/JSON/RecipeIdTypeFilter.php#13`

and
`OCA\Cookbook\Controller\RecipeController::import uses the @NoAdminRequired annotation and should use the #[OCP\AppFramework\Http\Attribute\NoAdminRequired] attribute instead`

(things worked fine last approx. 2 years)

**Comment by christianlupus** [comment]
Can you create new files in the files app? This sounds like you had completely different problems with your database.

**Comment by jomuench** [comment]
indeed when I try to create a new file, it throws the same error.

**Comment by christianlupus** [comment]
Please check the first before we proceed here. Possible hints:
https://www.reddit.com/r/NextCloud/comments/1efvnvh/error_update_the_table_oc_filecache_is_full/?rdt=61407
https://stackoverflow.com/questions/730579/1114-hy000-the-table-is-full

**Comment by jomuench** [comment]
my filesystem was full. Stupid me...
Thanks for your support!
