### ISSUE TITLE
Mobile Categories

### ISSUE THREAD

**Issue by poltrian** [nextcloud/cookbook#268]
In the mobile version, the categories are very cumbersome. In the Version 6x you simply wiped the category back and forth

**Comment by mrzapp** [comment]
I believe @sam-19 is looking into this, as they mentioned in #260, so this will eventually be improved.

**Comment by sam-19** [comment]
Unfortunately, I did not use the 6.x version of the app on mobile at any point, so I'm not exactly sure what this means. Was the side navigation display controlled by swipe gestures? Did you implement this functionality yourself, @mrzapp, or was it a part of the Nextcloud core templates? If it was something you implemented, maybe you could give me a hint. If not, it may be out of my league to implement without risk of breaking something else, unless I can find an example from one of the core apps that use Vue.

**Comment by mrzapp** [comment]
@sam-19 I didn't implement this, it seemed to be standard for NC core. But honestly, all we can do now is copy what other apps are doing, and not worry too much about what it used to be.

**Comment by sam-19** [comment]
I found a related issue on the nextcloud-vue repository. It seems Vue doesn't support touch events natively, but there is a third party package for that: [https://www.npmjs.com/package/vue2-touch-events](https://www.npmjs.com/package/vue2-touch-events). Installing dependency would increase complexity, but unless I can find another way, is it okay to you to use this, @mrzapp?

**Comment by mrzapp** [comment]
@sam-19 absolutely, fine with me :)

**Comment by seyfeb** [comment]
I think this is solved. If not, please report back. Closing this for now.
