### ISSUE TITLE
tooltip of info-icon in settings is just "Last update" 

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/cookbook#279]
**Description**
In settings is an info-icon with a tooltip. The text of the tooltip is just "Last update:"

**Reproduction**
1. Go to 'settings'
2. Move mouse over the the info-icon
3. See tooltip "Last Update:"

**Expected behavior**
The date and time of the last update are displayed or there should be no info-icon (my preference)

**Screenshots**
![cb20202627](https://user-images.githubusercontent.com/34692335/85920687-1b2ff180-b876-11ea-9f7d-452cc141dacf.png)

**probably:**
https://github.com/mrzapp/nextcloud-cookbook/blob/14612e14d28326cd910c1953c558b97e510e1c41/src/components/AppNavi.vue#L67

**Versions**
Cookbook: 0.7.6
NC: 18.0.6, NC 9

**Comment by sam-19** [comment]
This is a leftover from the misinformed translation method venture. To make it work the title of the button would have to be called from a computed property. If you want to take a shot at implementing it, @cloud2018, be my guest :). Then again, as you said, is that information even needed? Checking when the library was last scanned takes a lot longer than just (unnecessarily) scanning it again. With @mrzapp's permission that button cloud also be completely removed.

**Comment by cloud2018** [comment]
@sam-19 Sorry, I am not so skilled in developing php/vue, otherwise i would have provided a PR

**Comment by mrzapp** [comment]
@sam-19 feel free to remove the last updated info, it's not crucial
