### ISSUE TITLE
Papercut: In top navigation: hand-cursor without a link

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/cookbook#281]
**Description**
A hand-cursor is displayed in the top navigation if the mouse is over "Category" and over the name of the selected category, although there is no link.

**Reproduction**
1. Select a category
2. In the top menue move the mouse over the breadcrumbs
3. OK: If the mouse is over the home-icon, a hand-cursor is displayed and there is a link. 
4. not OK: If the mouse is over "category" and over the name of the selected category, a hand-cursor is displayed, but there is not a link. 

**Expected behavior**
Only over clickable areas a hand-cursor is displayed.

**Screenshots**
Areas without link, but with a hand-cursor:
![cb20202627](https://user-images.githubusercontent.com/34692335/85922795-49b5c880-b886-11ea-8b67-c70b8b5d9ea4.png)

**Comment by mrzapp** [comment]
@cloud2018 thanks for the report, would you be willing to contribute a patch? The relevant file for this issue would be [this one](https://github.com/mrzapp/nextcloud-cookbook/blob/master/src/components/AppControls.vue)

In order to run the development environment, you just need to `npm install` and `npm run dev` in the root directory.

**Comment by sam-19** [comment]
I actually noticed this during development, but was unable to fix it (granted, I did not use _that_ much time on it). If you can find a way, kudos to you. I may take another shot at it once some of the more urgent bugs are fixed.

**Comment by cloud2018** [comment]
Maybe the easiest way is just to remove the word "Category".

In files app there is only the home-icon and the name of the folder (in level 1). "myfolder1" links to the current page
![cook2](https://user-images.githubusercontent.com/34692335/87072453-10813f00-c21c-11ea-97c2-87ed9e21ae77.png)

Without word "Category" it is similar to the files app:
![cook1b](https://user-images.githubusercontent.com/34692335/87072455-124b0280-c21c-11ea-9764-d563e2bd1efe.png)

**Comment by christianlupus** [comment]
This might be solved by #896.

**Comment by MarcelRobitaille** [comment]
This is not solved by #896. That only takes the buttons out of the breadcrumb component, but the navigation is still the same as before.

I did some digging. The offending rule is [here](https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Breadcrumb/Breadcrumb.vue#L260-L266). nextcloud/vue is assuming that everything in the breadcrumb before the last element is clickable. This suggests to me that maybe breadcrumb isn't the best component for this.

I see a few options:
1. Hack the css to overwrite these rules
2. Use a different component other than `Breadcrumbs`.
3. Remove the `Category` breadcrumb

**Comment by christianlupus** [comment]
I would say, that 2&3 are similar/related :smile:.

The breadcrumbs are intended for ... well breadcrumbs. That is a list of navigatable entries that visualize the current location in the navigation tree. We do neither have a navigation tree ATM (single cookbook), nor do we have any _depth_ in the recipes.

So, according to my understanding, we are just misusing the breadcrumb component here and it should be dropped (in our app) completely. If we are defining our own component as a replacement, we can easily add the word `Category` if there is sufficient space left.

This is just my opinion and might well be questioned. I just remember different discussions in different rooms/issues/chats that the breadcrumbs are a bad choice.

**Comment by MarcelRobitaille** [comment]
I was part of one such discussion for #896. However, here I can see the case for Breadcrumbs. The category button would have to be a link to all categories or something. Maybe it's better just to replace breadcrumbs though. I do like the styling and the home button is nice.

**Comment by christianlupus** [comment]
The home button can be imported. Do this is no strict argument for the breadcrumbs.
