### ISSUE TITLE
Encoding errors with recipes from hellofresh.ch

### ISSUE THREAD

**Issue by clesmian** [nextcloud/cookbook#284]
**Description**
Importing recipes from hellofresh.ch works just fine, but there are encoding issues with special characters like äüöîé etc.

**Reproduction**
1. Import recipe from hellofresh.ch containing special characters (for example: https://www.hellofresh.ch/recipes/herzhafte-gnocchi-pfanne-5e136097a18baa02e540e58b) 
2. Check for example the headline of recipe 

**Expected behavior**
It should say "Käse-Mix", but it's displaying "KÃ¤se-Mix"

**Technical details**
As far as I can see the json included by hellofresh.ch is completely valid and everything works just fine, when you copy it from the pages source and put it into a json file inside of the recipe folder. 
I suspect that  somewhere along the lines of parsing the recipe there is an issue with incorrect encoding. 

Unfortunately I've not enough experience with php to debug the code myself and find the root cause of the issue.

**Comment by glogiotatidis** [comment]
I get encoding errors from https://akispetretzikis.com/el/categories/soypes-2/karotosoypa which is pretty popular in greece. I believe the problem is that neither of those two websites declare document charset with `<meta charset="utf-8" />` and I guess php defaults to `latin` 

My suggestion is that cookbook defaults to utf-8 if no charset is defined.

**Comment by burkhre2** [comment]
I get encoding errors for german 'umlaut' (e.g. instead of 'ü' I get 'Ã¼' )  from some webpages, e.g. https://migusto.migros.ch/de/rezepte/kuerbis-schoggi-kuchen where `<meta charset="utf-8" />` is specified in the page source. So the problem might be something else than just the default charset setting.

But another German page also with 'umlaut' characters e.g. https://cloud.marebu.ch/apps/cookbook/#/recipe/17082 is imported correctly.

**Comment by cholletk** [comment]
Same there in french for fooby.ch (https://fooby.ch/fr/recettes/12340/roastbeef-aux-topinambours-et-au-sarrasin) and like @burkhre2 , there is <meta charset="utf-8"/> in soruce

**Comment by christianlupus** [comment]
The problem with some of the named sites is that they do not contain valid HTML. Especially the definition of the content encoding is coming too late (must be within the first 1024 characters).

See:
* [Showing results for https://fooby.ch/fr/recettes/12340/roastbeef-aux-topinambours-et-au-sarrasin - Nu Html Checker](https://validator.w3.org/nu/?showsource=yes&showoutline=yes&useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&acceptlanguage=&doc=https%3A%2F%2Ffooby.ch%2Ffr%2Frecettes%2F12340%2Froastbeef-aux-topinambours-et-au-sarrasin "Showing results for https://fooby.ch/fr/recettes/12340/roastbeef-aux-topinambours-et-au-sarrasin - Nu Html Checker")
* [Showing results for https://migusto.migros.ch/de/rezepte/kuerbis-schoggi-kuchen - Nu Html Checker](https://validator.w3.org/nu/?showsource=yes&showoutline=yes&useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&acceptlanguage=&doc=https%3A%2F%2Fmigusto.migros.ch%2Fde%2Frezepte%2Fkuerbis-schoggi-kuchen#l85c105 "Showing results for https://migusto.migros.ch/de/rezepte/kuerbis-schoggi-kuchen - Nu Html Checker")

This is something you could report back to the site providers that they are not confirming the standards (holds true for almost every site on the web ;-)).

Apart from that, I checked all mentioned recipe sites and they all specify the charset in the HTTP headers. As we are downloading [in a separate function](https://github.com/nextcloud/cookbook/blob/master/lib/Service/RecipeService.php#L806-L837), the headers are not evaluated/used. The DOM parser has only the main content where the charset is not reachable within the boundary of 1024 characters. Most probably therefore it is ignored and the parsing uses the wrong charset.

**Comment by melchiorharcourt** [comment]
Of course, these sites don't comply with HTML specifications, but it's the case of > 99% sites as you say (at least kitchen sites!) on the web...Looking forward to future updates!

**Comment by NemesisRE** [comment]
Any updates? I finally have found something that my wife likes but I have always to fix those encoding errors to not lose her to a physical cookbook collection that she would buy otherwise ^^

**Comment by MarcelRobitaille** [comment]
What if we pass the encoding from the `Content-Type` header to `DOMDocument()`? [The constructor takes `encoding` as a second argument.](https://www.php.net/manual/en/class.domdocument.php) 

Here is my idea:
1. Extract the encoding from the content type header from the `$http_response_header` variable set after calling `file_get_contents` [here](https://github.com/nextcloud/cookbook/blob/a19daa5618e826144e381b1e2f20d77018ad2df9/lib/Service/RecipeService.php#L846).
2. Pass the encoding as an argument to `parseRecipeHtml`.
3. Pass the encoding to `DOMDocument`: `new \DOMDocument("1.0", $encoding)`

I also found this, which sounds like it might be useful: https://www.php.net/manual/en/class.domdocument.php#118509

**Comment by christianlupus** [comment]
I was thinking it might be better to use guzzle than build something for ourselves. There are multiple things to consider and having a library solve this for us seems very plausible for me...

**Comment by MarcelRobitaille** [comment]
I can confirm that [this recommendation](https://www.php.net/manual/en/class.domdocument.php#118509) with `mb_convert_encoding` works for this recipe: https://www.hellofresh.ch/recipes/herzhafte-gnocchi-pfanne-5e136097a18baa02e540e58b. Simply setting `'utf-8'` to `\DOMDocument` did not work though.

@christianlupus Regarding guzzle, this seems like only an HTTP client to me. I do not see any HTML parsing functionality. Do you recommend this to easily extract the content-type header, or what is the advantage? 

As a quick test, I tried replacing our `file_get_contents` with the following:
```php
$client = new GuzzleHttp\Client();
$res = $client->request('GET', $url);
$html = $res->getBody();
```

However, I am still getting the issue if I remove `mb_convert_encoding`.
