### ISSUE TITLE
add possibility to delete recipes

### ISSUE THREAD

**Issue by rapkin61** [nextcloud/cookbook#305]
**Is your feature request related to a problem? Please describe.**
It might be a problem of the app, the documentation, or the user (me).
Up to now I haven't found a way to delete a recipe. I tried to delete the underlying file in folder - but the recipe is still there within the app (but clicking in it gives an error).
I also looked for a context menu entry that would do the task ... and also looked for a documentation, just in case there was a way to delete a recipes I could not think of.

**Describe the solution you'd like**
The most desireable way probably was a context menu entry "delete recipe"

**Describe alternatives you've considered**
n.a.

**Comment by Teifun2** [comment]
If you delete the underlying folder you need to rescan your library. (on the bottom left there is a button for that. Settings -> Rescan Library)

There is also a button on the top for each recipe that lets you delete the specific recipe! 
![Unbenannt](https://user-images.githubusercontent.com/7461832/90311165-830acc00-def8-11ea-9825-28b747f7bdfa.PNG)

If you are looking for bulk deletion then deleting the folders is the easiest way!

I hope this answers your question?
