### ISSUE TITLE
Resting time not implemented

### ISSUE THREAD

**Issue by kojid0** [nextcloud/cookbook#312]
It seems like resting time is not yet implemented, therefore time calculation doesn't make much sense.
In this [example](https://www.chefkoch.de/rezepte/2609101409859076/Haehnchen-Wrap-mit-Honig-Senfsauce.html), preparation time + cooking time != total time, because "resting time" is missing.
![Unbenannt](https://user-images.githubusercontent.com/24477557/91319373-99e4d480-e7bc-11ea-9f5e-510ff104b00c.PNG)

**Comment by sam-19** [comment]
I don't think resting time is a part of the [recipe schema](https://schema.org/Recipe) (or at least I can't find it), and I think @mrzapp's idea has been to stick as close to the official schema as possible. Also, there can be other reasons to why total time does not match prepping + cooking time, and trying to include them all would not be practical. On the other hand, I do see how having a resting time field with a countdown function (like cook time has) would be especially useful. This field could be hidden on the recipe page, if the value is empty. Maybe this should be left open for discussion, for now.

**Comment by christianlupus** [comment]
I see it the same as @sam-19: There is no mention of a reest time in the schema.org. Thus, I will close this here.

If there is a bigger motivation except for the visual correct sum on screen, we can still discuss and reopen.
