### ISSUE TITLE
add mobile apps to README

### ISSUE THREAD

**Issue by geeseven** [nextcloud/cookbook#319]
**Is your feature request related to a problem? Please describe.**
Mobile applications are a key feature to extend the functionality of the cookbook app.

**Describe the solution you'd like**
I would like to see a section in the README that lists the various mobile applications that are out there.  Something like the [News][0] app.

**Describe alternatives you've considered**
n/a

I would be more than happy to submit a pull request to list the two I recently stumbled on. 

[0]: https://github.com/nextcloud/news#sync-clients

**Comment by christianlupus** [comment]
Best would be if you could provide a PR directly. This will cause the least of work and the chances are good that once someone finds more, this is simply added.

Thanks for the contribution.

**Comment by Tuetenk0pp** [comment]
just a hint: if you are on iOS, add a safari-bookmark of the recipe page to your home-screen.

**Comment by christianlupus** [comment]
@geeseven Are you still interested in contributing this update?

**Comment by seyfeb** [comment]
I just added two Android clients to the README in #372 . Are those the two you were referring, @geeseven?

**Comment by christianlupus** [comment]
Merging the PR will close this issue. If you have more clients to add @geeseven just issue a comment (or open a simple PR yourself). Thank you.
And thank you @seyfeb for the contribution.
