### ISSUE TITLE
Batch category renaming

### ISSUE THREAD

**Issue by seyfeb** [nextcloud/cookbook#322]
## Current state

Currently recipes are put in a category by typing in the category name. The categories are then created by clustering recipes with the same category string. Renaming a category, e.g., from `Starters` to `Starters & Antipasti` would require manually opening each recipe of the category and updating the category field.

## Proposed state

Add some editing UI (e.g., a pencil next to the category name that opens a popup for renaming) and iterate over all recipes matching the old category string and update to the new string.

Slightly related to #313.

**Comment by sam-19** [comment]
This is definitely a needed feature. But I think #313 should be resolved first, as this would have to be remade at that point anyways.

**Comment by seyfeb** [comment]
Should we can iterate over all recipes make update calls from the frontend or should we set up an API endpoint which does the renaming on the server?

I would think the second way is better in the sense that the risk of having some "in-between" state where some recipes have been recategorized and some have not yet been updated can only result from server errors and not, e.g., an unstable internet connection on the client side.

@christianlupus What do you think?

**Comment by christianlupus** [comment]
For me an API endpoint makes sense. Seems also faster as much fewer requests are needed. For a large cookbook set (like the 800) the iteration might cause trouble.
