### ISSUE TITLE
'None' category selection

### ISSUE THREAD

**Issue by sttrebo** [nextcloud/cookbook#326]
when i am importing several recipies, i sometimes loose track on which categories I have added the new recipies to.  it ends up being time consuming to track down those items that are not categorized yet.  is there a way to add a filter for uncategorized recipies?

**Comment by christianlupus** [comment]
This is an issue with the DB backend. I found it during my work on PR #297. I have not explicitly tried it out, but once a recipe has no category assigned it is shown only without selecting a category explicitly, unless I am completely mislead.

**Comment by sttrebo** [comment]
thanks for looking at this.  but from what i see, you can only either select a category or select 'all recipies'.  there doesn't seem to be a way to not select any.  
![Capture](https://user-images.githubusercontent.com/2676482/95105791-84809580-06ec-11eb-824e-a19b01ad9f07.JPG)

**Comment by christianlupus** [comment]
You are right, the frontend needs also to make this visible.
