### ISSUE TITLE
Add secondary compact layout or make layout more compact by default

### ISSUE THREAD

**Issue by khaytsus** [nextcloud/cookbook#328]
The recipe image takes up almost half of the view, leaving the actual instructions off the bottom of the screen.  It would make sense to make it a more columnar view with a smaller image.

Maybe image of the recipe top left, description and time information to the right of that.  then under it, the same format that ingredients and instructions are today.  Basically just move description and timing info to the right of the image.

Attaching badly gimped image of suggestion ;)
![Screenshot_2020-10-04_10-31-10](https://user-images.githubusercontent.com/5436277/95018495-21c8c480-062e-11eb-8258-1192a3d43452.png)

**Comment by christianlupus** [comment]
This only works for wide screens. For narrow screens the effect is completely reversed. However I consider the normal PC ratio the normal user of the web view.

@sam-19 do you see a chance to make this design responsive to float according to the window width? You have the most frontend experience in our app as far as I see things.

**Comment by sam-19** [comment]
I have done something like this with floating elements before, but not so much with flex. I can try some options, but where would you think the breakpoint (for the image width) should be?
