### ISSUE TITLE
Missing search bar

### ISSUE THREAD

**Issue by hideYourPretzels** [nextcloud/cookbook#330]
**Description**
After install, the app's search bar is missing.

**Reproduction**
1. Go to Cookbook App
2. Try to search recipes. 
3. Observe the search bar is missing.

Nextcloud Version: 19.0.3
Cookbook version: 0.7.6

**Expected behavior**
A search bar is available as shown on the App's web page 
See top left corner of the capture below (2nd text box)
![](https://raw.githubusercontent.com/mrzapp/nextcloud-cookbook/stable/img/screenshot.jpg)

**Screenshots**
Capture of the missing search box:
![nextcloud19 0 3_CookBook_MissingSearchBar](https://user-images.githubusercontent.com/72358863/95026046-bcf18680-068e-11eb-983e-378d55bf2934.png)

**Browser**
Firefox 81 and Chromium 85

**Comment by christianlupus** [comment]
See #243, #318. Other ossues might be of interest here as well (e.g. minor #300, #313).
The search was disabled as it was not functional yet.

Closing here as duplicate. If there are more points I did oversee in the issue, feel free to complain and I will reopen.
