### ISSUE TITLE
Sorting order of recipes: first capital then lower case

### ISSUE THREAD

**Issue by seyfeb** [nextcloud/cookbook#333]
**Description**
This may be wanted behavior, although I don’t like it personally. I noticed that the recipes are sorted by title, first considering the capitalization of the first letter (capitals first, then lower case), and then the alphabetic order. As an example the current order would be

1. BBzzzz
2. Bbaaaa
3. aaaaaa

**Reproduction**
1. Create recipes with above titles
2. Go to the “All recipes” overview page

**Expected behavior**
I would expect the case to be ignored, in terms of the example:

1. aaaaaa
2. Bbaaaa
3. BBzzzz

**Screenshots**

<img width="664" alt="Screenshot 2020-10-09 at 10 49 49" src="https://user-images.githubusercontent.com/7623143/95563020-2bcb3880-0a1d-11eb-8704-7bc7fb703d79.png">

**Browser**
Vivaldi, Firefox, Opera

**Comment by christianlupus** [comment]
OK, so I will close this issue right now. If the issue persists, we can reopen anytime.

The reason for not using a reference was that way I have a real side-effect-free function. Might be a bit worse in performance but better in terms of debugging/testing.
