### ISSUE TITLE
Activate dependabot

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#336]
Should we enable a dependency tracker like dependabot to get informed about new versions?

**Comment by christianlupus** [comment]
As I do not know who is responsible for this repo, I can only ask @mrzapp to activate this.

**Comment by mrzapp** [comment]
@christianlupus I actually don't know either, after the repo got moved I lost all privileges except push. I'll investigate.

**Comment by mrzapp** [comment]
This may be another one for @ChristophWurst?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/cookbook/pull/394

**Comment by mrzapp** [comment]
@ChristophWurst thanks! Seems like no special access was needed after all

**Comment by ChristophWurst** [comment]
nope, all repos get Dependabot, it just needs either a custom config on the web (from admins) or a config file. For this community app I chose the config file because then you can update configuration without us :)
