### ISSUE TITLE
Logs gets spammed 

### ISSUE THREAD

**Issue by maxammann** [nextcloud/cookbook#344]
**Description**
When importing the log gets filled with errors until there is no more disk space. Also the import fails sometimes. Sometimes it succeeds

**Reproduction**
1. Import the recipe https://www.chefkoch.de/rezepte/18711004787789/Risotto-mit-gruenem-Spargel-und-Parmesan.html
2. The logs gets filled with errors until it reaches several gigabytes. The first 10 lines of the log are attached
[log.txt](https://github.com/nextcloud/cookbook/files/5378720/log.txt)

[data.txt](https://github.com/nextcloud/cookbook/files/5393956/data.txt)

**Expected behavior**
The recipe is imported or shows an error

**Browser**
latest Firefox

**Comment by christianlupus** [comment]
I looked at your log output. It seems that your xml parser gets confused by the `[class]` attribute at the beginning of the recipe (look at the second line in the code). I found [this bug request](https://bugs.php.net/bug.php?id=63477) that might be your problem. You might want to look at the PHP version and the libxml extension version.

**Comment by maxammann** [comment]
I'm using the official snap from nextcloud which uses PHP 7.3. I'm not sure yet how I can find out which libxml version the snap uses.

I think the spamming of the log needs to get fixed nonetheless. It actually renders the whole nextcloud intance unusable. I'm not sure why it includes the whole html and writes a lot of errors.

**Comment by christianlupus** [comment]
As I said, this is probably not a bug in the cookbook app but a dated library in the snap.
I tried to import the named recipe in my dev environment. There no problem was found and the recipe was imported mostly instantly. No errors are logged.

We can (and will) not rewrite a complete XML/HTML parser. Additionally, I am not fluent with the snap ecosystem. So, I cannot help you much anymore at the moment. I found [this repo](https://github.com/nextcloud/nextcloud-snap) that might contain the relevant information and/or fluent people.

Just to rule this out: Yo are on a recent version of the snap, right?

**Comment by maxammann** [comment]
Yes, its the latest version. My current version of libxml2 is `2.9.4`. 

I created a small php script to reproduce this:

```php
<?php

$opts = [
"http" => [
"method" => "GET",
"header" => "User-Agent: Nextcloud Cookbook App"
]
];

$context = stream_context_create($opts);
$url = 'https://www.chefkoch.de/rezepte/18711004787789/Risotto-mit-gruenem-Spargel-und-Parmesan.html';
$html = file_get_contents($url, false, $context);

$document = new \DOMDocument();
if (!$document->loadHTML($html)) {
	throw new \Exception();
}
$xpath = new \DOMXPath($document);

echo count($xpath->query("//*"));
````

I get a lot of php warnings on arch and within the snap:
```
Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5875 in /tmp/test.php on line 15

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5875 in /tmp/test.php on line 15

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5875 in /tmp/test.php on line 15

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5875 in /tmp/test.php on line 15

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5875 in /tmp/test.php on line 15

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5875 in /tmp/test.php on line 15

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5875 in /tmp/test.php on line 15

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5890 in /tmp/test.php on line 15

Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 5890 in /tmp/test.php on line 15
```

Do you think something like this makes sense to implement? https://stackoverflow.com/a/14783843
I can also provide a PR :)

**Comment by christianlupus** [comment]
In my development environment I cannot confirm the issue. However, I can confirm your script causing issues on my arch installation. Having issues with the debugging in my dev environment, I would be pleased, if you could provide a PR. I can only check statically but if it look clean, I am okay with merging a well-written code enhancement. I cannot confirm resolution of the issue at the moment.

**Comment by maxammann** [comment]
I think I will try to provide a patch in the following driection:

```php
$libxml_previous_state = libxml_use_internal_errors(true);

$dom->loadHTML($html);
// log errors somehow
libxml_clear_errors();
libxml_use_internal_errors($libxml_previous_state);

```

**Comment by christianlupus** [comment]
You could use the default [nextcloud logging capabilities](https://docs.nextcloud.com/server/20/developer_manual/basics/logging.html). But keep in mind that this will fill the logs just the same as you had the issue in the first sight.
