### ISSUE TITLE
Import not possible due to escape characters in the urls of json

### ISSUE THREAD

**Issue by intbl** [nextcloud/cookbook#345]
**Description**
Hi, trying to import from lecker.de (for example: https://www.lecker.de/gegrillte-suesskartoffel-bohnen-frikadellen-75693.html) gives an error, that the page couldn't be parsed.

When looking at the sourcecode, it follows the correct format (I added spaces behind the @ to not mention anyone):
`<script type="application/ld+json">{"@ context":"http:\/\/schema.org","@ type":"Recipe","name":"Gegrillte S\u00fc\u00dfkartoffel-Bohnen-Frikadellen", (more text, but not important for this issue). `

When looking into https://github.com/nextcloud/cookbook/blob/master/lib/Service/RecipeService.php it expects  
`$json['@ context'] = 'http://schema.org';` (line 128) 
whereas on the specific site the url is having escape characters: `"@ context":"http:\/\/schema.org".`

Do you think that adding escape charcters in the expected context would be a possible idea?

Thanks a lot.

**Comment by christianlupus** [comment]
Short answer: no.
The escape chars are there for compatibility reasons. See e.g. [here](https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped). I will try to have a look soon.

**Comment by christianlupus** [comment]
I just tried parsing the named recipe using my development environemnt. I cannot confirm this issue currently.

@intbl is there a more verbose message possibly under `nextcloud/data/nextcloud.log` or in the system settings? At the moment I have no clue where the curlpit is located.

**Comment by intbl** [comment]
Hi Christian, and thanks for looking into it.
Totally weird, I was also able to import the recipe without issues, along a couple of others. But still having issues with one:
https://www.lecker.de/sommerlicher-flammkuchen-mit-ziegenfrischkaese-chorizo-peperoni-oliven-und-pesto-4107.html
nextcloud/data/nextcloud.log is quite verbose, having the whole request in this file.
But under systems settings, it looks a lot more readable.
Can see bunch of parsing errors, like this example (shortened):
`[PHP] Error: Error: DOMDocument::loadHTML(): Tag header invalid in Entity, line: 291 at /var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php#424 at <<closure>>`
Full error can be found [here.](https://github.com/nextcloud/cookbook/files/5410193/full_error.zip)


Having a look into the source of https://www.lecker.de/sommerlicher-flammkuchen-mit-ziegenfrischkaese-chorizo-peperoni-oliven-und-pesto-4107.html, it shows the following in line 291: `<header class="header">` 
But the very same is listed in the working examples, so shouldn't be related.

Have therefore attached the [log](https://github.com/nextcloud/cookbook/files/5410164/nextcloud.log.zip), you might be able to spot something in there?

**Comment by christianlupus** [comment]
Regarding to logging issue, there is another issue open at the moment: #344.

The problem at least for *Sommerlicher Flammkuchen* is a non-well-formed JSON file. I played around in the debugger to locate the exact issue. You might wnat to have a look at [my gist](https://gist.github.com/christianlupus/8f5b8edb0b0b5426b255646c3db3cc0a) and [a linter](https://jsonlint.com/).

In fact the reson for this special recipe is that there is a `"` in one of the ingredients. This would have to be escaped but is not in the JSON+LD script. As a result the JSON is parsed as defectivee and no JSON can be parsed.

So there are two things to do:

1. Inform lecker.de about the fact that their JSON generator is generating invalid JSON
1. Close this issue as it seems not solvable by this app.

If you find another issue, please feel free to report it.
