### ISSUE TITLE
Can't import recipts from https://irezept.com

### ISSUE THREAD

**Issue by KaeTuuN** [nextcloud/cookbook#356]
Hi,

I tried to understand the parseRecipeHtml, but I'm not that good with PHP-Code.
Link I tried to Import: https://irezept.com/hirschgulasch-in-steinpilzsose.html

Greetings

**Comment by christianlupus** [comment]
Hello. Long story short, that page does not provide JSON+LD schema.org metadata. We use this metadata to extract the relevant parts of the recipe. So unfortunately, we cannot parse the recipe.

You can do the following (ideally both):
- Insert the recipe by copy/paste into your instance
- Contact the owner of the page and ask if such metadata was possible. For reference: http://schema.org/Recipe.

For further questions, just ask me.

**Comment by KaeTuuN** [comment]
Bad News for me, but thanks, for the reply!
