### ISSUE TITLE
l10n: Not full text string in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/cookbook#357]
There is an incomplete string in Transifex:
https://github.com/nextcloud/cookbook/blob/fef9af9bdaf195375df47bc1b716a1b6ad7ba51c/src/components/AppNavi.vue#L203

The sentence ends with:

- Failed to load category 

Correct the code so that boot Transifex correctly scans the text string.

Help: https://github.com/nextcloud/server/blob/a2a3b87c19662f06cfb804b9fead7e939b1c3e6c/core/src/globals.js#L130-L137

**Comment by christianlupus** [comment]
@Valdnet Is the change in #358 what you are looking for?

**Comment by Valdnet** [comment]
@christianlupus Yes. Looks good. You can merge 😉.
