### ISSUE TITLE
Cookbook 0.7.6 on Nextcloud 20.0.1 blank page

### ISSUE THREAD

**Issue by baahver** [nextcloud/cookbook#361]
**Description**
I installed cookbook from git. Version 0.7.6. on Nextcloud 20.0.1. When I try to open Cookbook, I just get a blank page. Nothing on it. (just the blue banner from nextcloud, and under that nothing. So the app is not running?

**Reproduction**
install cookbook from github: git clone https://github.com/nextcloud/cookbook.git
In /var/www/nextcloud/apps/
The app is installed and I can activate it in NC apps.

**Expected behavior**
a recipes management app, not a blank page.

**Browser**
Firefox 81.0.2 (64-bits)
But no other problems at all.

log:
`Error: Undefined property: OCA\Cookbook\Service\DbCacheService::$user_id at /var/www/nextcloud/apps/cookbook/lib/Service/DbCacheService.php#347

    /var/www/nextcloud/apps/cookbook/lib/Service/DbCacheService.php - line 347:

    OC\Log\ErrorHandler::onError()

    /var/www/nextcloud/apps/cookbook/lib/Service/DbCacheService.php - line 376:

    OCA\Cookbook\Service\DbCacheService->getSearchIndexLastUpdateTime()

    /var/www/nextcloud/apps/cookbook/lib/Service/DbCacheService.php - line 368:

    OCA\Cookbook\Service\DbCacheService->checkSearchIndexUpdate()

    /var/www/nextcloud/apps/cookbook/lib/Controller/MainController.php - line 51:

    OCA\Cookbook\Service\DbCacheService->triggerCheck()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Cookbook\Controller\MainController->index()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1009:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()`

**Comment by baahver** [comment]
Oh, I'm sorry. I rmeoved the app. Then reinstalled from apps store in Nextcloud, and now suddenly it is working.

**Comment by christianlupus** [comment]
FYI: You would have to build the app in order to run from git.
To do so, you would have to run `npm install` and `make` in the app folder. Then you can enable it and use it as in the app store.

Here just for information in case anyone stumbles upon this issue during searching.

**Comment by baahver** [comment]
Thank you ChristiianLupus,
I did not know that. I will try that another time!
