### ISSUE TITLE
corrupt duplicates, “Loading recipe failed”

### ISSUE THREAD

**Issue by 4001982248998** [nextcloud/cookbook#363]
Hello,

I have several dublicate recipes with corrupted images. When trying to open them, it is saying: “Loading recipe failed” („Laden des Rezepts fehlgeschlagen“).

Bildschirmfoto:
![image](https://user-images.githubusercontent.com/2796469/97722265-be19a600-1aca-11eb-80bf-75a6a5ffc680.png)

**Comment by seyfeb** [comment]
Hi @4001982248998 Can you provide some more information? Did you create the duplicates? How did the images get corrupted? What is your setup?

Ideally, can you specify the exact steps how to reproduce the issue?

**Comment by christianlupus** [comment]
Hello @4001982248998. Could you please reindex the database? That can be done in the app left below where the settings are. 

Additionally, please check in the files app what recipes are in the folder of the cookbook app.

Do you have direct access to the database? Maybe you could create a dump of the database tables from the cookbook app. Only these three databases would suffice. There is no critical data in but you can of course check for your privacy. You can send the dump to my mail address if you do not want to publish it here.

**Comment by 4001982248998** [comment]
> Hi @4001982248998 Can you provide some more information? Did you create the duplicates? How did the images get corrupted? What is your setup?
> 
> Ideally, can you specify the exact steps how to reproduce the issue?

The duplicates just appeared. I don't know why. I am using the latest versions of both Nextcloud and the Cookbook app. I have noticed the corrupted entries somewhen while using NC19.

**Comment by 4001982248998** [comment]
> Hello @4001982248998. Could you please reindex the database? That can be done in the app left below where the settings are.

Well, this is embarrassing. I have not noticed this option before. It seems to have solved the issue for me. Thank you! Cheers!
