### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by Tuetenk0pp** [nextcloud/cookbook#367]
**Is your feature request related to a problem? Please describe.**
I have recipes I use quite often and it is convenient to add a short version of the required steps in the description field. E.g. when I am baking bread which has important timings that you could summarize in the description field

**Describe the solution you'd like**
So, what I would like to see is a possibility to use markdown in the description field. Maybe include the [Text](https://github.com/nextcloud/text) app for that?

**Describe alternatives you've considered**

**Comment by christianlupus** [comment]
Related to #47
