### ISSUE TITLE
Ingredient measurement system converter and ratio's

### ISSUE THREAD

**Issue by jessechahal** [nextcloud/cookbook#369]
**Is your feature request related to a problem? Please describe.**
When looking at recipe ingredients sometimes the measurements are:
- not very exact (i.e. use one whole turkey, a couple of carrots, etc..)
- different measuring system (i.e. 1/2 cup vs 125mL)
- are set for too large/small of a serving size (recipe to serve 50 servings)

**Describe the solution you'd like**
1. When creating/importing a new recipe:
  - split the ingredient name from its measurement
  - enter in ratio's between ingredients should viewer/user need to change desired serving size (defaults all ingredients 1:1:1:...)
    - this is important because sometimes in order to half the desired serving size you cannot just half all the ingredients and cook times
2. When viewing/using a recipe: 
  - ability to select measurement system (would be nice if there could be a user default)
  - A thesaurus + dictionary to view certain ingredients. i.e bicarbonate of soda vs baking soda (they are the same thing just different terms depending on country)
  - a way to easily change the measurements for an existing recipe to match my desired serving size. This would take the incorporate ingredient ratio's into consideration and automatically convert them
  - make changes to the recipe as I'm using i.  The tools and/or ingredients I have available may differ from actual recipe (i.e. my oven bakes faster the recipe authors oven, use fork instead of whisk, etc..)
    - commit these changes using https://github.com/nextcloud/cookbook/issues/364 into a new version/branch

**Describe alternatives you've considered**
An alternative to some of this would just be to clone the recipe and update the new version. The problem becomes if i want to keep these recipes in-sync. Sometimes the only difference will be measuring system (based on country or tools available) other times its the ingredient amounts due to serving size changes. At some point in the future the recipe may need more serious updates (add/remove ingredients)

**Comment by christianlupus** [comment]
This is merely a extension to #116. See the comments there why this is not easily reachable.

Also there is a duplicate with #135 (thesaurus). Issue #364 should be seen independent.

**Comment by jessechahal** [comment]
Closing as it's a duplicate
