### ISSUE TITLE
Recipe not found after changing the language

### ISSUE THREAD

**Issue by pbhgl** [nextcloud/cookbook#370]
**Description**
On Cookbook 0.7.6 after changing the language and then clicking on a recipe a message "Loading recipe failed" is shown. This is similar to #269 except that I didn't update anything. It is caused by adding a new recipe folder for the new language. The same happens for every new user when changing the language.

**Reproduction**
1. Go to Nextcloud > Cookbook
2. Import a few recipes
3. Go to Nextcloud > Settings and change the language
4. Go back to Nextcloud > Cookbook
5. Click on a recipe
6. Error message "Loading recipe failed" is shown.

**Note**
The error doesn't occur anymore after setting the Recipe folder in the Cookbook settings:
1. Go to Nextcloud > Cookbook
2. Click on Settings
3. The current recipe folder is shown in the input field
4. Click on the recipe folder and choose the same or another recipe folder
From now on the recipe folder isn't changed anymore when changing the language.

**Expected behavior**
After changing the language the recipes should still be found.

**Browser**
Firefox

**Comment by christianlupus** [comment]
The folder name should now be constant even if the user changes the language. WiIl merge the changes soon.
