### ISSUE TITLE
Update image in app store

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#391]
The image in the app store is no longer up to date. We should update that image.

**Comment by mrzapp** [comment]
The images will be updated when `master` is merged into `stable`

**Comment by christianlupus** [comment]
@mrzapp  Is there a CI-CD system in place that will publish the `stable` branch?

**Comment by mrzapp** [comment]
@christianlupus no, but before the repo was moved, I added the key to the "secrets" area, so anyone with collaborator access should be able to set up the flow. I stupidly forgot to accept my invitation a while ago, so I unfortunately don't have that access myself :sweat_smile:

**Comment by christianlupus** [comment]
@mrzapp Do you still know the name of the secrets involved? I would try to get a flow running then.

**Comment by mrzapp** [comment]
@christianlupus there is only one AFAIK, it should be [here](https://github.com/nextcloud/cookbook/settings/secrets/actions)

**Comment by christianlupus** [comment]
Yes, I do not get it but a 404. I can set up the floor of I know the name of the secret and what it contains exactly (the raw certificate or some base64 things out whatever.

**Comment by mrzapp** [comment]
@ChristophWurst do you have access to the secrets page, and if so, could you grant @christianlupus access too? Or at least let him know what the name of the key is?

**Comment by christianlupus** [comment]
I asked @tobiasKaminsky as well if he knew something about your temporary absence. He promised to ask around and try to help. Maybe he found something who is responsible to restore the access to the repo.

**Comment by tobiasKaminsky** [comment]
i forwarded your request internally, but seems that it slipped through somehow.
I will ping again.

**Comment by mrzapp** [comment]
@christianlupus sorry about my absence, I've been bogged down with other projects. But as I've mentioned before, I'm not using this app myself, although I'm glad and really excited that so many people are getting something valuable out of it. I have been looking to pass this repo on to anyone who's interested, but so far not getting anywhere, at least officially.
