### ISSUE TITLE
Codecov integration

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#400]
@ChristophWurst Is is possible to enable the Codecov integration plugin for the app as well? There is a basic setup prepared using the GH actions but it fails on their page to print e.g. branch names and the like. I suspect this is due to the missing integration bot.

**Comment by ChristophWurst** [comment]
From what I can tell by looking at https://codecov.io/gh/nextcloud/cookbook it looks enabled

**Comment by ChristophWurst** [comment]
You might need one CI run for master before codecov can track any diffs

**Comment by ChristophWurst** [comment]
I've enabled the integration now. Try again.

**Comment by christianlupus** [comment]
Thank you again. After a few commits it seems that the enabled integration solved the issues.
