### ISSUE TITLE
Just FYI for the maintainers

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/cookbook#405]
Hi @mrzapp @christianlupus, to follow up cause Christian contacted @tobiasKaminsky regarding maintainership of the app and also mentioned that @mrzapp’s invitation to be admin of this repo expired – should all be fixed now if you accept the invitations. ;)

You should also be able to add further active collaborators like e.g. @seyfeb to the repository. :) 

Let me know if you need anything else, and feel free to close this issue.

**Comment by mrzapp** [comment]
Thanks!

@christianlupus I can now see that the secret we were looking for is called "PEM"

**Comment by christianlupus** [comment]
Yes, sounds good. I can see it. Thank you @jancborchardt.
