### ISSUE TITLE
Slow loading Pages

### ISSUE THREAD

**Issue by TheMBeat** [nextcloud/cookbook#409]
**Is your feature request related to a problem? Please describe.**
Slow loading Pages.

**Describe the solution you'd like**
For larger recipe collections, lazy-loading (Blure) the images for the recipe overview could improve the performance.

**Comment by christianlupus** [comment]
@sam-19 Do you see a possibility to implement the lazy-loading of the images in a paging-like fashion?

**Comment by seyfeb** [comment]
I’m going to have a look at this. I try to combine it with #406, so we have very small thumbnails for a blurred preview and higher-resolved thumbnails that are dynamically loaded and can be used in other clients.
