### ISSUE TITLE
Replace icons by SVG(s)

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#414]
The image at https://github.com/nextcloud/cookbook/blob/master/img/recipe-thumb.jpg (and possibly others) might be better off as SVG files that can be optimized and arbitrarily scaled.

**Comment by TheMBeat** [comment]
Can't we just use app.svg on a grey background?

**Comment by christianlupus** [comment]
Maybe with another foreground color, yes. But 500 Bytes are less than a few kB in `recipe-fill.jpg` or `recipe-thumb.jpg`.

**Comment by TheMBeat** [comment]
@christianlupus
 What should the new SVGs look like? What background color and what color should the icon have?

**Comment by christianlupus** [comment]
I have not extracted the RGB values but the SVG should be usable as a replacement for e.g. https://github.com/nextcloud/cookbook/blob/master/img/recipe-full.jpg. So should be straight forward.

**Comment by TheMBeat** [comment]
Okay, i can do this next week.
