### ISSUE TITLE
Tag selection is persistent if navigating to other category

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#425]
**Description**
The filtering w.r.t keywords needs to be reset when moving to a new path.

**Reproduction**
1. Make at least two recipes 1 in category A and keyword a and 2 in category B with keyword b.
2. Navigate to category A.
3. Click to filter for keyword a.
4. Navigate to category B (on the left)
5. Recipe 2 is no longer shown

**Expected behavior**
The tag filtering is cleared or at least a visual option to do so is present.

**Browser**
Which browser are you using?
Firefox on Linux

**Comment by seyfeb** [comment]
What would we prefer? Clearing the keywords or keeping the selection and showing an option to clear them? I can see advantages for both approaches.
