### ISSUE TITLE
default categories view doesn't show categories

### ISSUE THREAD

**Issue by jhaar** [nextcloud/cookbook#444]
**Description**
When I view my nextcloud-20 Cookbook, I can see icons for each Category with the number of recipes in each - but there's no mention of the *category name*. I end up having to guess - clicking on each in order to find out what is inside it

This is the Android NextCloud Cookbook "Teifun2" version just installed today

BTW looking at the Cookbook app within the web browser shows images, etc - so the backend is working correctly. Interestingly the browser interface defaults to "All recipes" and doesn't really have a "show categories" option like this Android app is doing - which is a pity as that's a good idea :-)

**Reproduction**
1. start app
2. see bunch of icons with no details except for the number of recipes

**Expected behavior**
should at least see the Category name - perhaps with mixture of the recipe images?

**Comment by seyfeb** [comment]
This is the repository for the Nextcloud cookbook app ("plugin"). Teifun2’s Android app is a viewer of the stored data which is not developed here. I think [this](https://github.com/Teifun2/nextcloud-cookbook-flutter) is his repository - you might want to open an issue there.

As for the categories in the Webview of this app, you should be able to see the categories on the left side

<img width="292" alt="Screenshot 2020-12-20 at 10 57 29" src="https://user-images.githubusercontent.com/7623143/102710383-28bcb600-42b2-11eb-8a73-278d798c3d46.png">

**Comment by jhaar** [comment]
whoops! Sorry about that - I've re-posted to the actual repo ;-)
