### ISSUE TITLE
Wait for DOM to become ready needed?

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#453]
Having used jQuery in the past a bit I am a bit concerned about the following fact:

In jQuery, you have to wait for the browser to build up the complete DOM tree before you can start manipulating it. Especially registering listeners/handlers must not be done before the DOM tree is ready.

In Vue.js I have never seen such a requirement. I asked at the Vue discord server and there I was given different answers. One user suggested using a structure like 
```
window.addEventListener('DOMContentLoaded', () => {
  // Call your Vue mounting stuff here
})
```
and
```
const loadLoginApp = async () => {
  const elements = document.querySelectorAll('[data-app-login]')

  elements.forEach(async element => {
    const { default: Vue } = await import(/* webpackChunkName: 'vue' */ 'vue')

    new Vue({
      el: element,
      components: {
        'Login': () => import(/* webpackChunkName: "Login" */ '@vuedir/components/Login' as any),
      },
      render: (createElement) => {
        return createElement('Login')
      },
    })
  })
}
```
in order to load the Vue app. Another user claimed that Vue was working on a virtual DOM tree so waiting was not needed.

@sam-19 As I feel completely lost here, can you explain if we need to add such a waiting structure?

**Comment by christianlupus** [comment]
I just saw, this is realized using jquery at the moment. So this can maybe be seen as a suggestion to drop the jQuery dependency.

**Comment by sam-19** [comment]
Hey and sorry for my continued absence, my time is still pretty much completely taken up by another project. In case this is still relevant, in my standalone Vue apps I never employ any kind of listeners for the loader. In fact my index.html is pretty much just the app div and a script tag (after the body) where I call MyVueApp.run() where MyVueApp is an exported class and run() creates the Vue instance (like your loadLoginApp above). So it certainly is not a requirement of Vue itself.

**Comment by christianlupus** [comment]
After some testing (also with a new vue project) I suspect that the waiting is not needed anymore and is an old remnant from the jQuery times (where all pages were generated using PHP). In that case, I would suggest getting rid of it, don't you agree?

We might be able to clean it out with the next code cleaning step.

**Comment by MarcelRobitaille** [comment]
I know it's closed already, but I think it's not needed because the script is loaded with `defer`. Even without Vue, you could start manipulating the DOM as soon as the script loads in this case. I watched an interesting video about it just today: https://www.youtube.com/watch?v=_iq1fPjeqMQ
