### ISSUE TITLE
Error in the JS console in Firefox due to lazy loading of images

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#462]
**Description**
For some reason, the implementation in the [lazy loading](https://github.com/nextcloud/cookbook/blob/cce3864c79cf21a59a7b02fda34a5739ef2540da/src/components/LazyPicture.vue#L83-L109) seems to cause issues on Firefox.

**Reproduction**
1. Open Firefox
2. Open the web dev tools
3. (Optional) Remove any previous logs
4. Navigate to the start page of cookbook (like `/apps/cookbook`)

One gets messages as below:

![grafik](https://user-images.githubusercontent.com/8202922/103228102-4e8c2f80-4930-11eb-8a35-419aeea5c1aa.png)

**Expected behavior**
No errors are rosen.

**Browser**
Verified on Firefox 83.0 under Linux and Win10. Chrome seems to be unaffected by this bug.

**Further Information**
It seems that the functions `onThumbnailPreviewLoaded` and `onThumbnailFullyLoaded` are called twice in Firefox. I just added `console.log(*)` entries and found that in Chrome these were called only once (as intended) but twice per image on Firefox.

@seyfeb As this was contributed by you, could you check and verify it is working for you? Any good ideas on how to counteract?

**Comment by bluszcz** [comment]
I am not sure if this is a same bug, but when I try to add the image to recipe, I am hitting this error in dev tools (Chrome/Brave):

```
EditImageField.vue:27 Uncaught TypeError: Cannot set property 'image' of null
    at EditImageField.vue:27
    at y (main.js?v=42b3fb6b-15:1)
    at HTMLDivElement.click (main.js?v=42b3fb6b-15:1)
    at HTMLButtonElement.<anonymous> (main.js?v=42b3fb6b-15:1)
    at HTMLButtonElement.dispatch (main.js?v=42b3fb6b-15:1)
    at HTMLButtonElement.v.handle (main.js?v=42b3fb6b-15:1)
```

**Comment by christianlupus** [comment]
No, @bluszcz this seems to be a different issue. I think your issue is #438.

This one is only related to Firefox (and potentially other browsers) but not reproducible on Chrome.

**Comment by seyfeb** [comment]
I can reproduce the issue in FF 84.0 and Safari 14.0.1 and don’t have it in Chrome 87.0, Opera 73.0, or Vivaldi 3.5 (everything on macOS). I need to look into it to hopefully find the problem.

**Comment by christianlupus** [comment]
Thanks @seyfeb for the quick solution
