### ISSUE TITLE
Recipe Does Not Show  Under Its Category w/o Page Refresh

### ISSUE THREAD

**Issue by paulcalabro** [nextcloud/cookbook#465]
**Description**
When adding a new recipe, the user must refresh the page to see the recipe under its category.

**Reproduction**
1. Import a recipe from a website (e.g. https://www.culinaryhill.com/mojito-mocktail-recipe/).
2. The category for the above item is automatically set to "Drinks".
3. Notice the recipe is displayed in the list of recipes, however, it's not displayed under the category as expected even though it has one.
4. Refresh the page. Notice it is now displayed under the category as expected.

**Expected behavior**
The user does not need to refresh the page to view the recipe under its category. It's not obvious since the recipe is displayed correctly.

**Screenshots**
N/A

**Browser**
FF 84

**Comment by christianlupus** [comment]
The same holds true when adding a recipe to a category or changing the category of a recipe.
