### ISSUE TITLE
Search not visible

### ISSUE THREAD

**Issue by mayermart** [nextcloud/cookbook#474]
**Description**
I just found and installed this app an it looks very promising.
In #178 you say a seach should be availabe. This is not the case on my Nextcloud 20.0.4 with Cookbook 0.7.7

**Expected behavior**
A searchbar should appear somewhere.

**Screenshots**
![Screenshot_20210106-153730_Firefox](https://user-images.githubusercontent.com/2022598/103780682-99472f00-5035-11eb-85da-f539cb5f194a.jpg)

**Browser**
Tested on an Android Tablet with Chrome and Firefox

**Comment by seyfeb** [comment]
This is kind of hidden - admittedly it may not be the best solution. However in "All recipes" / "Alle Rezepte" there should be three dots in the breadcrumbs which would open a search field. I’m not sure though, if this is available in the current NC App store release or only on the current development branch.

<img width="585" alt="Screenshot 2021-01-06 at 15 49 39" src="https://user-images.githubusercontent.com/7623143/103781730-04453580-5037-11eb-8642-b3b4a9d50475.png">

**Comment by mayermart** [comment]
Wow, thanks for that super fast response. 👍 :)

As the three dots are not available i assume that feature didn't made it to the App Store release yet but will be available 'soon'. Do you have a shedule for the next relese?

**Comment by seyfeb** [comment]
A CD process is currently in development. As far as I know, there will be more regular releases in the foreseeable future. @christianlupus might have more infos on this topic! :)

**Comment by christianlupus** [comment]
As already written otherwise, due to the publication of v0.7.8 this should be done so far. Thus closing. If need is there, we can reopen.
