### ISSUE TITLE
Single pasted tool/instruction/ingredient is not saved

### ISSUE THREAD

**Issue by seyfeb** [nextcloud/cookbook#475]
**Description**
If a single line of tools/instruction/ingredient is pasted (ctrl+v) in the field and the recipe is saved, the value doesn’t get saved

**Reproduction**

1. Copy a string without a newline to the clipboard from somewhere
2. Go to 'Create recipe'
3. Click on '+Add' for either tool/instruction/ingredient
4. Paste the string into the field
5. Save recipe

**Expected behavior**
The pasted string should be saved

**Browser**
Opera, FF

**Comment by florian-hild** [comment]
Same problem.
I had to copy always two lines at the time.
