### ISSUE TITLE
Keywords are not deleted with recipe

### ISSUE THREAD

**Issue by seyfeb** [nextcloud/cookbook#476]
**Description**
When a recipe is deleted the associated keywords should be removed from the database. This doesn’t seem to be the case.

**Reproduction**
1. Create new recipe or edit existing recipe
2. Add a new tag to the recipe (e.g., "testtag")
3. Save recipe
4. Observe: This tag is now available in the multiselect element in the Recipe editor for any recipe and appears in the database (table `oc_cookbook_keywords`).
5. Delete the recipe.
6. Observe: The tag is still available in the multiselect of the recipe editor, even if no recipe with the keyword assigned exists anymore. Also the entry is still present in the database.

**Expected behavior**
Associated keywords should be removed from database when the recipe is deleted

**Comment by christianlupus** [comment]
I will have a look soon.
