### ISSUE TITLE
Search within the Cookbook app (keywords?)

### ISSUE THREAD

**Issue by CSchaefer70** [nextcloud/cookbook#479]
I would love to have a search of key words within the cookboob app.  Currently I can search if I include in the "title"; nextcloud finds the file in the "Cookbook Folder", but, now I need to remember the name and find it manually in the cookbook app.

**Comment by mayermart** [comment]
As i understood, there should be a search available with the next update. See #474

**Comment by CSchaefer70** [comment]
Excellent. Thank you for the quick response. Aside from the "Spinning Wheel on Create Recipe" issue the app is neat and effective.  Thank you!

**Comment by seyfeb** [comment]
Well, that’s partly true. There should be a search available - which, atm, searches for titles as far as I know. 

However, there will be some improvements in keyword handling, including the ability to filter recipe for keywords in a category. 

Searching for all recipes containing a specific keyword is not directly implemented in the UI, although there will be the possibility to list all recipes with a keyword by clicking on the keyword in the recipe view.

So, as far as I am concerned, this issue may remain open (unless there is already an issue on this, that I haven’t seen). If I remember correctly, improvement of the search function has been requested somewhere before with searching for ingredients in mind. 

I think there is a general need for "improving the search functionality in the app".

**Comment by christianlupus** [comment]
Not really. If you search (not filter!) it should work. The [search functionality](https://github.com/nextcloud/cookbook/blob/master/lib/Db/RecipeDb.php#L283) also takes keywords and categories into account.

So, I will close this as it is in general implemented. However, if the functionality is not working, please open a new bug that states exactly the problem and what happens etc.
