### ISSUE TITLE
input field for tools, ingredients and instructions does not appear

### ISSUE THREAD

**Issue by schumischumi** [nextcloud/cookbook#480]
**Description**
cant tools, ingredients or instructions to new recipe.
reinstalled the app and removed the recipe folder, but that didnt help

**Reproduction**
1. open cookbook app
2. Click on 'create recipe'
3. Click on 'add' (doesnt matter if tools, ingredients or instructions)
4. Input field does not appear 

**Expected behavior**
Normally the a input field should appear

**Browser**
chromium & firefox

**Logs**
Chromium console has a lot of vue.runtime.esm.js errors: 
[nextcloudpi.local-1610097439409.log](https://github.com/nextcloud/cookbook/files/5786297/nextcloudpi.local-1610097439409.log)

**Comment by seyfeb** [comment]
Duplicate of #430

**Comment by schumischumi** [comment]
@seyfeb sry for the dublicate and thanks for the link!
