### ISSUE TITLE
0.78 is soo slow

### ISSUE THREAD

**Issue by poltrian** [nextcloud/cookbook#489]
**Description**
My Browser sad, Website is so slow. wait or cancel. Firefox & Chromium. Nextcloud 20.04
0.77 has worked.

**Comment by christianlupus** [comment]
How many recipes do you have?

**Comment by poltrian** [comment]
847 :-)

**Comment by christianlupus** [comment]
@seyfeb could this be an issue with the watches that are now in place?

@poltrian just to make sure: If you open the web developer console (do it before opening the page), please check if there are any sort of errors logged or if there are a huge amount of network requests started. I doubt it, but just to make sure and narrow down the problem.

**Comment by poltrian** [comment]
its unusable, at the top i can see the "Schlagworte" thats new and i guess there is the problem

**Comment by poltrian** [comment]
The Cookbook Adroid app is also not working:

Fehler beim Laden der Kategorien: FormatExeption Unexpected Character (at character 1) <DOCTYPE html> ^

**Comment by seyfeb** [comment]
> There are no network connection problems

And also no errors logged, I guess?

Do you see the keywords appear at the top (a scrollable div), but no recipes appearing below? Are you able to interact with the keywords? 

What happens if you have a category selected which contains fewer recipes, say <100?

I must admit I never had that many recipes in my database for testing.

**Comment by poltrian** [comment]
No, no errors are logged. Yes i can see the Keyword and after a long time i can select them. But you have to wait 5 min. At 0.77 these was not fast but it works. i love these app so much, spend a lot of time to add recipes. Please bring back a working version

**Comment by poltrian** [comment]
![Bildschirmfoto vom 2021-01-09 23-30-25](https://user-images.githubusercontent.com/50879520/104110073-6373a600-52d4-11eb-9c31-6a3ecef8beb5.png)

**Comment by poltrian** [comment]
![Bildschirmfoto vom 2021-01-09 23-47-39](https://user-images.githubusercontent.com/50879520/104110167-25c34d00-52d5-11eb-91ed-15ba33f32ce7.png)

**Comment by seyfeb** [comment]
To get some more info: How many different keywords do you have, ca?
After the 5 minutes, if you select/deselect keywords for filtering is everything working smoothly or is anything lagging?
Do you see the same slow behavior if you select a category, e.g., "BBQ & Grillen" instead of "Alle Rezepte"?

**Comment by christianlupus** [comment]
@poltrian To have a bigger amount of recipes (real-world test data), would it be ok to share these recipes at least with the devs? You can contact me via mail as in the github account page.

**Comment by poltrian** [comment]
@christianlupus  Yes, you need the json files? How can i delete Keywords? A lot of the would be created before categories are implemented

**Comment by basvandenbrink** [comment]
I notice this behaviour once I open a category in the web interface. I have 48 recipes.

**Comment by christianlupus** [comment]
@poltrian Best would be a complete tarball from your recipes folder. That contains the images and the JSONs. I am unsure and we already discussed if this is related to the image loading (was newly introduced) or for some other reasons. As we have no exact clue, I suspect we should keep the eyes open in all directions.

@basvandenbrink you are facing issue #494 or #498 I assume. Please check.

**Comment by basvandenbrink** [comment]
@christianlupus Yeah, I think it's the same issue indeed. I think it will be solved with the next release then. :)

**Comment by poltrian** [comment]
I think I found the cause. I deleted all the keywords from the recipes. 
There were sometimes up to 20 keywords. Since many key words are repeated in the individual recipes, e.g. Totmate, tomatoes. Lowcarb, lowCarb, low-carb or even prescriptions, recipes make a lot of nonsense. The keywords come from the recipe websites. With the number of recipes, so many links are created in the Database. This is why the retrieval takes so long, so we need a better way of dealing with keywords or a better query from the database. Although I don't know if it makes sense to write oc_cookbock_keywords like this. Perhaps the keywords table should be emptied when reloading recipes? It is then built up again. Changes made to the keywords in the recipe would be adopted and the database would only contain the desired keywords. In the end, only your own keywords are interesting and not those from the imported recipe

**Comment by poltrian** [comment]
Its Mysql, MariaDB

**Comment by christianlupus** [comment]
> The Cookbook Adroid app is also not working:
> 
> Fehler beim Laden der Kategorien: FormatExeption Unexpected Character (at character 1) ^

This is a separate repository, see #508.

> its unusable, at the top i can see the "Schlagworte" thats new and i guess there is the problem
> There are no network connection problems

Back to the main issue at hand.

Here I am a bit surprised now. I cannot confirm huge lags in the app on my development setup and the current `master` code state. Well 8500 recipes take some time of course for the images, so 1~2 sec per visible image but that should be pretty fine I think.

To verify the problem is there I will go to the v0.7.8 version and see if there it is the same.

**Comment by poltrian** [comment]
Yes, 0.77 have worked, 0.78 has lags.

**Comment by christianlupus** [comment]
OK, I have to revert my statement. It seems I had a caching issue here. The `master` branch has the lagging feature as well. I was using a wrong frontend code as I forgot to compile.
I found another running version with [this version](https://github.com/seyfeb/cookbook/tree/ccd06958b6ac1f470b60335fa3c20e81e289ff0d). But the keywords are gone there as well. Will have a closer look now. Here just for reference.
