### ISSUE TITLE
Keyword Count does not filter for user in "All Recipes"

### ISSUE THREAD

**Issue by mayermart** [nextcloud/cookbook#491]
**Description**
The node {url}api/recipes returns all keywords without a filter for the current user or a distinct.
With shared recipes this leads to a count of n per recipe instead of 1 for each keyword showing in "All Recipes" 

Unfortunately I have not found the api files to verify in code.

**Reproduction**
In API:
1. Open API Node api/recipes
2. Note the keywords of some recipe
3. Duplicate a keyword entry for that recipe in the database table oc_cookbook_keywords with some fake user_id to simulate a shared recipe
4. Refresh api/recipes and see duplicated keyword

In UI:
1. Go to 'All Recipes'
2. Note the count of some Keyword
3. Duplicate a keyword entry in the database table oc_cookbook_keywords with some fake user_id to simulate a shared recipe
4. Refresh "All Recipes" and see the increased count

**Expected behavior**
Count displays the correct number of recipes / API returns distinct keywords

**Browser**
Firefox

Additional Question: How do those keywords get added for a shared recipe for the other users? For Example UserA adds a Keywod to a recipe, how and when does the keyword get duplicated for UserB? There are recipes in my database where the keywords are not in sync.

**Comment by seyfeb** [comment]
I’ll look into the issue. There is probably just a condition missing for fetching only keywords belonging to the current user - shouldn’t be too hard.
Regarding your second question I would also have to look into the code!

**Comment by christianlupus** [comment]
The second question, I can answer quickly:
The categories are saved in the JSON and cached in the database. You see the DB content when browsing the cookbook app. Once in a while (depending on the user setting) the cookbook app will do a rescan of the library. This can be triggered manually. After the update, the DB should be consistent with the JSON files (which you most probably have shared across user boundary).
