### ISSUE TITLE
Pictures are not downloaded

### ISSUE THREAD

**Issue by CSchlipp** [nextcloud/cookbook#492]
**Description**
When adding a new recipe manually and specifying the URL of the recipe image, the image is not downloaded and the field is not saved.

**Reproduction**
1. Add new recipe manually
2. specify URL for image
3. Save
4. See that the recipe does not have an image
5. Edit the recipe
6. See that the Image field is empty

**Expected behavior**
The image should be downloaded and saved along with the recipe.
Pretty sure this was the behavior of previous versions.

**Screenshots**
n/a

**Browser**
Chrome

**Comment by christianlupus** [comment]
The image should be loaded in [these lines](https://github.com/nextcloud/cookbook/blob/32c4a6536daa8f74ae7dec21c8e7e87b6f77c62a/lib/Service/RecipeService.php#L725-L727). The problem seems that the image data is not forwarded from the frontend, the value of `$json['image']` is empty.
