### ISSUE TITLE
Hangs while trying to expand category

### ISSUE THREAD

**Issue by hmoisand** [nextcloud/cookbook#494]
Next cloud 20.0.4 and updated cookbook 0.7.8 hangs after trying to expand (click right arrow triangle) the recipe category from left hand list. (I can now add new recipes that was not possible with previous cookbook version! So this great app is finally somehow usable as long as one do not accidentally mess up with categories)

**Reproduction**
1. Go to Cook book
2. Click on left triangle arrow of recipe category.
3. Cookbook and browser window hangs.

**Expected behavior**
3. Recipe category is expanded.

**Browser**
Ubuntu 20.10. [Google] Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by hmoisand** [comment]
Problem same with Firefox 84.0.2 (64-bit)

**Comment by hmoisand** [comment]
This also prevent the usage of Cookbook android app. Cannot open up anything. Error message: Category Load Failed: FormatException: Unexpected character (at character 1)  <!DOCTYPE html>

**Comment by mazen-mardini** [comment]
I can reproduce this on Brave.

**Comment by christianlupus** [comment]
This should be solved with the PR #500.
Issue #498 is separate and might need its own fix.
