### ISSUE TITLE
Issue creating new recipes

### ISSUE THREAD

**Issue by joeplus** [nextcloud/cookbook#496]
Hey there,

I am having issues creating new recipes. I cannot save any new recipe, because whenever I click on the save-button, the spinner starts, but nothing happens: ![grafik](https://user-images.githubusercontent.com/7793652/104136603-2a771800-534c-11eb-97d5-5e26b4feb2e3.png)

Creating recipes from URLs works though. Any ideas what that could be? Thank you in advance!

**Comment by CameronRP** [comment]
Had this same issue. Upgrading to the latest release fixed it for me.

**Comment by hmoisand** [comment]
This is well known bug. It seems to be fixed in 0.7.8.

**Comment by christianlupus** [comment]
@joeplus please specify which version you are running currently. Also please check if you are on the latest version (currently `0.7.8` as or writing). Thank you.

**Comment by christianlupus** [comment]
I am closing here as over a month no reaction was given.

**Comment by joeplus** [comment]
Thank you, the upgrade fixed it for me, too!
