### ISSUE TITLE
Breaking changes in Nextcloud 21

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/cookbook#504]
Hi there,

I found that your app uses some classes of Nextcloud's third party libraries. Since an upgrade of those for php8 compatibility, your app will have to be adjusted as well. See https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#doctrine-dbal for details. Your app uses `Doctrine\DBAL\Types\Type` which was dropped.

Cheers

**Comment by christianlupus** [comment]
Thanks @ChristophWurst for the heads-up. We will have a look.

BTW: Is there an announcement mailinglist or something when new releases of the server are published and similar important information?

**Comment by ChristophWurst** [comment]
Please note that we just merged a PR with our own constants for the types, so the app can be fully independent of any 3rdparty libraries: https://github.com/nextcloud/server/pull/25089.

The schedule is typically up on https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule. The important info eventually land on https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html, but before we finalize that section for each new release there is the github overview ticket that is also linked there. And I try to also drop a forum post, which I haven't for this topic but I will in a minute.

**Comment by christianlupus** [comment]
The new version 0.8.3 was just pushed out with support for NC 21. That should have fixed that issue.
