### ISSUE TITLE
V 0.7.8 breaks Android App

### ISSUE THREAD

**Issue by OleAlbers** [nextcloud/cookbook#508]
**Description**
Since updating to V 0.7.8 The Android App ("Nextcloud Cookbook/Teifun2") does not work anymore. I expect the Nextcloud app to be the issue and not the Android app because it specifically only happens with the most current version.

When trying to sync in the Android app an error is displayed instead of the categories:
```
Fehler beim laden der Kategorien: (*)
FormatException: Unexpected character (at character 1) 
<!DOCTYPE html>
^
```
*) Translates to "error when loading categories"

It might be worth noticing that at least one category contains Umlauts ("Geflügel")

Manually downgrading to 0.7.7 fixes the issue until updating again

**Reproduction**
- Open Android App
- Click the Sync - Button
- The error mentioned above is displayed

**Expected behavior**
A list of all categories should be shown 

**Browser**
App

**Versions**
Nextcloud server version: 20.0.4
Cookbook version: 0.7.8
Android App-Version: 0.3.6 (most current)

**Comment by christianlupus** [comment]
@OleAlbers unfortunately your request is in the wrong repository. You might want to have a look at Teifun2/nextcloud-cookbook-flutter. There should be work done soon here due to #487.

@Teifun2 FYI

**Comment by OleAlbers** [comment]
Oops. Sorry. Thanks for directing to the right one
