### ISSUE TITLE
Recalculate amount of ingredients invoked by changing the number of servings

### ISSUE THREAD

**Issue by achmetinternet** [nextcloud/cookbook#509]
It would be great if the amount of ingredients changed based on me adapting the number of servings. I know this is not exactly as straightforward because you cannot multiply the amount of e.g. cumin with the same number as potatoes due to the influence on taste & cooking behaviour. But it would be at least an improvement and wouldn't require me to recalculate everything.

**Comment by christianlupus** [comment]
Duplicate of #116 #384
