### ISSUE TITLE
Cookbook 0.7.9 on NC 19.0.6: Can not save recipe

### ISSUE THREAD

**Issue by Kieltux** [nextcloud/cookbook#523]
After update to 0.7.9 I can not save a recipe anymore.
Disabled the app, removed the app and installed again. Nothing changed.

**Reproduction**
1. Create a recipe
2. Add some things
3. Save the new recipe (click on "Save Changes")
4. Error Message: "Recipe could not be saved"

**Expected behavior**
A new recipe saved in Nextcloud

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6629537/104814497-8db2ef80-580f-11eb-9226-82d969e05f51.png)

**Browser**
Firefox 78.6.1 ESR
Opera 73.0.3856.344

**Versions**
Nextcloud server version: 19.0.6
Cookbook version: 0.7.9

I get this in the NC Logs:

```
Exception: Call to undefined function OCA\Cookbook\Helper\str_starts_with()

    /var/www/vhosts/nextcloud-server/httpdocs/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Cookbook ... {}, "create")

    /var/www/vhosts/nextcloud-server/httpdocs/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Cookbo ... r", "create", OC\AppFramew ... {}, { _route: "c ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "c ... "})

    /var/www/vhosts/nextcloud-server/httpdocs/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "c ... "})

    /var/www/vhosts/nextcloud-server/httpdocs/lib/base.php - line 1010:

    OC\Route\Router->match("/apps/cookbook/api/recipes")

    /var/www/vhosts/nextcloud-server/httpdocs/index.php - line 37:

    OC::handleRequest()

Verursacht durchError: Call to undefined function OCA\Cookbook\Helper\str_starts_with()

    /var/www/vhosts/nextcloud-server/httpdocs/apps/cookbook/lib/Helper/RestParameterParser.php - line 36:

    OCA\Cookbook\Helper\RestParameterParser->getEncoding("application ... 8")

    /var/www/vhosts/nextcloud-server/httpdocs/apps/cookbook/lib/Controller/RecipeController.php - line 119:

    OCA\Cookbook\Helper\RestParameterParser->getParameters()

    /var/www/vhosts/nextcloud-server/httpdocs/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\Cookbook\Controller\RecipeController->create()

    /var/www/vhosts/nextcloud-server/httpdocs/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Cookbook ... {}, "create")

    /var/www/vhosts/nextcloud-server/httpdocs/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Cookbook ... {}, "create")

    /var/www/vhosts/nextcloud-server/httpdocs/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Cookbo ... r", "create", OC\AppFramew ... {}, { _route: "c ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "c ... "})

    /var/www/vhosts/nextcloud-server/httpdocs/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "c ... "})

    /var/www/vhosts/nextcloud-server/httpdocs/lib/base.php - line 1010:

    OC\Route\Router->match("/apps/cookbook/api/recipes")

    /var/www/vhosts/nextcloud-server/httpdocs/index.php - line 37:

    OC::handleRequest()
```

**Comment by christianlupus** [comment]
I am sorry, the `str_starts_with` is PHP 8. I will prepare a quick fix as this affects all changes to the app.

**Comment by christianlupus** [comment]
@Kieltux would you be willing and able to test a version before I push it out?

**Comment by Kieltux** [comment]
@christianlupus Yes, of course.

**Comment by christianlupus** [comment]
OK, stay tuned. In a few minutes, I can provide you a link to download a fixed version. If it works I will throw out a version 0.7.10 as this affects all non-`GET` access to the app and is therefore critical.

**Comment by christianlupus** [comment]
@Kieltux Here is the link: https://github.com/nextcloud/cookbook/suites/1842260044/artifacts/35654958

Unpack it twice and use it as a replacement for the current app in the NC installation under `/apps/` or `/custom_apps`.

**Comment by Kieltux** [comment]
@christianlupus Replace the patched Cookbook 0.9.7 with the version from the link.
Everything works (creating new recipes, editing existing recipes).

Looks good, thank you.

**Comment by christianlupus** [comment]
You should update to 0.7.10. Ity contains these changes.

**Comment by Kieltux** [comment]
Updated my two NC 19.06 and 19.07 to cookbook 0.7.10 and everything fine.
Thank you for your support and of course for cookbook.

**Comment by poltrian** [comment]
I would say "thank you" all is fixed
