### ISSUE TITLE
Navigation cannot be disabled

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#533]
**Description**
The navigation on the left side cannot be hidden. This was introduced when switching to the Vue-based frontend and seems to be broken since then. no button is visible and no functionality is given as well.

**Expected behavior**
The navigation side menu can be shown/hidden as requested by the user.

**Comment by seyfeb** [comment]
This is only the case for wide-enough browser windows. For smaller ones, there is a button to show/hide the navigation pane

**Comment by christianlupus** [comment]
That is true. This one can be considered obsolete.
