### ISSUE TITLE
Bad alignment of images in mobile (narrow) version

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#534]
**Description**
When in mobile view, some distances are a bit off. See screenshot below.

**Reproduction**
1. Go to the app
2. Move down only very slightly to make it visible

**Expected behavior**
The symbols should be aligned correctly.

I assume, the mobile menu image in the screenshot in the background, shited above could be dropped altogether. It just seems strange that "part of the image" can be scrolled to the top while part of the image just keeps it location.

**Screenshots**

![Screenshot_2021-01-18 Kochbuch - Nextcloud](https://user-images.githubusercontent.com/8202922/104907560-8f9ebf00-5985-11eb-91c2-22eaaa69d135.png)

**Browser**
Firefox under Archlinux

**Comment by seyfeb** [comment]
Okay, let’s discuss what we want to have:

The hamburger icon is used to show/hide the navigation pane - we probably want to keep this.

When scrolling down, there is currently a button in a fixed position indicating that the pane can be shown. Do you want to get rid of this @christianlupus?

Currently there is an icon in the Breadcrumbs bar. we may either keep this and hide the fixed one while the breadcrumbs bar is visible. Or we might remove it, having a blank space where the fixed icon sits.

**Comment by christianlupus** [comment]
> Currently there is an icon in the Breadcrumbs bar. we may either keep this and hide the fixed one while the breadcrumbs bar is visible. Or we might remove it, having a blank space where the fixed icon sits.

Either is ok. I would go with the fixed one and simply make the other one (that is located statically within the page breadcrumbs) invisible. Just both is a bit too much and looks strange when scrolling.

**Comment by seyfeb** [comment]
I noticed this as well and didn’t like it either. Forgot to open an issue, though.
