### ISSUE TITLE
Vertical scrolling when menu is active in mobile version

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#535]
**Description**
When the menu is visible in the menu version, the overall width of the page is wider than the viewpoint. As a result, vertical scrolling is introduced which is not too good in terms of responsive UI design.

**Reproduction**
1. Go to the app on mobile browser or narrow the browser window
2. Open the (left side) menu

Depending on the browser in use the problem-solution for vertical overflow might be different. So your screenshot might be different.

**Expected behavior**
If not enough space is on the right, the menu is shown full-width above the main content.

**Screenshots**

![image](https://user-images.githubusercontent.com/8202922/104908332-9d087900-5986-11eb-8f20-298219bf80fd.png)

This is the view on the "whole page" (as depicted on firefox) looks like. As you see, the navigation on top is only to the correct length but the main content hangs over to the right.

![image](https://user-images.githubusercontent.com/8202922/104908728-2750dd00-5987-11eb-9604-e4f7bf9f0d39.png)

**Browser**
Firefox on Archlinux

**Comment by seyfeb** [comment]
For me, as soon as I try scrolling in the recipe on the right the left navigation pane is automatically hidden (Firefox Mobile)

**Comment by christianlupus** [comment]
You mean scrolling in horizontal or vertical direction, @seyfeb?

**Comment by seyfeb** [comment]
either. even tapping on the recipe hides the pane

**Comment by christianlupus** [comment]
OK, I see. I just used the normal desktop browser and narrowed the window (easier for testing) and there is of course the problem that you use the mouse. So the click action (or whatever it is) is not triggered.

I just wanted to keep track of any issues I found during the testing for #528.
