### ISSUE TITLE
Thumbnails are not shown

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#550]
**Description**
In the left side navigation, there are no thumbnails shown (see screenshot below).

While loading there is a small rotating circle that is hidden once the recipe has loaded. Unfortunately, that circle is not replaced with any image but with the white background.

**Reproduction**
1. Go to the app
2. Open some categories on the left

**Expected behavior**
Left of the recipes the thumbnails should be shown.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8202922/105485616-79f30780-5cad-11eb-8cd6-12c79b31a973.png)

**Browser**
Firefox using Archlinux

**Versions**
Nextcloud server version: 20
Cookbook version: `master`

**Comment by seyfeb** [comment]
Looking at the code, I don’t think there should be any thumbnails, or? 🤔 

We could think of showing a "recipe-icon" there but I guess there’s too little space for the recipe’s thumbnail being useful

**Comment by christianlupus** [comment]
I think a small thumbnail could be shown in the place where the turning circle is shown during loading. Why is the circle there at all? I mean: what is loading while the animation is shown?

**Comment by seyfeb** [comment]
actually I’m not sure what the point of the circle is. Somewhere (haven’t yet checked where) the recipe is set to loading in the global state. I wonder if from a UI point the thumbnails would help or simply clutter the interface. one might need to test this.

**Comment by christianlupus** [comment]
Ok, I can see the point here that images of the recipes might be too small. From my personal UI experience, I feel the white space left of the recipe name strange like it is missing something there. So, I think we should put something there (be it an icon or a tree-like graphic) or get rid of it (including the circling circle) if there is no point in having it.

**Comment by seyfeb** [comment]
Ideas:

**1. with document icon**

<img width="290" alt="Screenshot 2021-01-26 at 17 13 35" src="https://user-images.githubusercontent.com/7623143/105872541-d1b9a780-5ffa-11eb-9e42-27dd283b8d4e.png">

**2. with right arrow** (the blue bar is highlighting the currently open recipe and is simply cut off in the first screenshot, but is actually there)

<img width="292" alt="Screenshot 2021-01-26 at 17 19 33" src="https://user-images.githubusercontent.com/7623143/105872563-d8481f00-5ffa-11eb-812e-5b206a4df642.png">

**Comment by christianlupus** [comment]
I would go with 1 as the second one (triangles, right arrows) indicate a hierarchical structure with subentries. The first one I find good.
