### ISSUE TITLE
NC21 Internal Server Error (500) on open cookbook

### ISSUE THREAD

**Issue by SafetyIng** [nextcloud/cookbook#551]
**Description**
On opening cookbook-App on NC21 getting an Error 500 - Internal Server Error

**Reproduction**
1. Use nextcloud 21 (from beta 1 to beta 7)
2. Open nexcloud.dir/index.php/apps/cookbook/

**Expected behavior**
Open the cookbook Main-Page

**Log-Trace**
The detailed Error-Log is found in [nextcloud.log](https://github.com/nextcloud/cookbook/files/5859536/nextcloud.log)

**Versions**
Nextcloud server version: 21.0.0 (beta 1 to beta 7)
Cookbook version: 0.7.10

**Comment by christianlupus** [comment]
Duplicate of #504 

Did you enable the app as an untested app or was it just activated by default, @SafetyIng?

**Comment by SafetyIng** [comment]
It was activated by default

**Comment by christianlupus** [comment]
The new version 0.8.3 was just pushed out with support for NC 21.
