### ISSUE TITLE
Links to recipes where download does not work

### ISSUE THREAD

**Issue by mscheferhoff** [nextcloud/cookbook#552]
Hello,
I read in the cookbook chat at nextcloud that rather links should be posted where the download of a recipe does not work. The function is truly awesome when it works.

Here are two links:
https://www.spiegel.de/stil/rezept-fuer-linsen-dal-a-f0dc50e3-9edf-4577-9841-1ae6d4c709af
https://www.rewe.de/rezepte/butternut-kuerbis-suppe/

I get an empty popup and looking at the log file I get the following:

For the first link:
```
[cookbook] Warning: libxml: Error 76 occurred 11 times while parsing https://www.spiegel.de/stil/rezept-fuer-linsen-dal-a-f0dc50e3-9edf-4577-9841-1ae6d4c709af. Last time in line 2859 and column 18404: Unexpected end tag : div


POST /apps/cookbook/import
from 192.168.178.20 by XXX at 2021-01-23T15:48:01+00:00
```

For the second link:
```
[PHP] Error: Error: file_get_contents(https://www.rewe.de/rezepte/butternut-kuerbis-suppe/): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
 at /config/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php#822 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError(2, "file_get_conten ... n", "/config/www/nex ... p", 822, {url: "https://w ... ]})
1. /config/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php line 822
   file_get_contents("https://www.rew ... /", false, null)
2. /config/www/nextcloud/apps/cookbook/lib/Controller/MainController.php line 317
   OCA\Cookbook\Service\RecipeService->downloadRecipe("https://www.rew ... /")
3. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Cookbook\Controller\MainController->import()
4. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Cookbook\Controller\MainController {}, "import")
5. /config/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Cookbook\Controller\MainController {}, "import")
6. /config/www/nextcloud/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Cookbook\\ ... r", "import", OC\AppFramework\ ... {}, {action: null,_r ... "})
7. /config/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/cookbook/import")
8. /config/www/nextcloud/index.php line 37
   OC::handleRequest()

POST /apps/cookbook/import
from 192.168.178.20 by XXX at 2021-01-23T15:41:31+00:00
```

I am using the latest version of the cookbook app on nextcloud 20.0.3.

Thx,
Michael

**Comment by christianlupus** [comment]
Regarding the second link, the provider rewe seems to have a filter available. They detect that it is no human being that tries to access their site. Therefore we get a 403 Forbidden HTTP request. I tried it with curl on my machine and the same happens. If anyone has a clue what the page requires in order to return the correct data, we can think about how we can implement that.

Regarding the first URL (spiegel): They, unfortunately, do not offer JSON+LD data embedded as far as I can tell. So I this page will most likely not be supported in the cookbook app.

**Comment by The-Assassin-Panda** [comment]
I have a similar problem with seriouseats.com, used to be able to import recipes from their site but no longer can. I'm running 0.7.10

Here's an example of a recipe that I already have but when I try to import it I get the empty popup.
[https://www.seriouseats.com/recipes/2010/07/no-waste-tacos-de-carnitas-with-salsa-verde-recipe.html]

**Comment by christianlupus** [comment]
@The-Assassin-Panda your problem is something different, see #569.

AS we cannot do much about the original two pages, I will close this issue here. If the need to discuss further arises, we can reopen.
