### ISSUE TITLE
cockbook not running after update to 0.7.10

### ISSUE THREAD

**Issue by mccius03** [nextcloud/cookbook#557]
The version 0.7.10 is not running on Nextcloud 18.0.14. I get a internal server error:

Der Server konnte die Anfrage nicht fertig stellen.
Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.
Weitere Details können im Server-Protokoll gefunden werden.

**Comment by seyfeb** [comment]
Hey! This might be the same problem as in #527 Could you try updating to NC 19 / 20?

**Comment by christianlupus** [comment]
No reaction within a month. I am closing here.
