### ISSUE TITLE
Import failure from toykitchenchef.com

### ISSUE THREAD

**Issue by ronaaron** [nextcloud/cookbook#566]
Attempt to import: https://toykitchenchef.com/2012/06/19/eggplant-and-lentil-stew/

Get an empty Javascript pop up.

**Comment by rgoulet13** [comment]
Same thing for me trying a handful of other websites as well. Popup just says: "<my server name> says"

**Comment by christianlupus** [comment]
@rgoulet13 Please provide the links or even better open a new issue. Then things can be handled separately.

**Comment by christianlupus** [comment]
I just checked the page toykitchenchef.com as provided by @ronaaron and the page simply is not compatible with schema.org. So no automatic import via schema.org metadata is possible.
