### ISSUE TITLE
[FR] Drag&Drop Ingredient List

### ISSUE THREAD

**Issue by made2140** [nextcloud/cookbook#571]
**Is your feature request related to a problem? Please describe.**
While editing a recipe, the ingredient list now could be rearranged only with arrows:
![image](https://user-images.githubusercontent.com/32461144/107263170-1c4f1100-6a4a-11eb-8d7e-d09bf8611e1d.png)

Current solution does not feel natural, e.g. if you miss entering one ingredient by order or group, one needs to add ingredient as a last one, then click those arrows to move upwards and try to follow the ingredient to click the correct arrow.

**Describe the solution you'd like**
I would suggest adding drag&drop-like functionality, so that it would be easier to rearrange ingredients as user wishes.
(This solution as was dropped after WAT (wife acceptance test) :grin: as it seemed to her that manual recipe input could be more intuitive)

**Describe alternatives you've considered**
No alternatives really, despite adding ingredients without misses, or still follow arrows to order the list correctly.

**Comment by seyfeb** [comment]
What about an "add ingredient above" option for each ingredient field?

**Comment by made2140** [comment]
@seyfeb I'd say that this would also be a perfect solution. :)
