### ISSUE TITLE
Recipe count does not update after adding first recipe by URL

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/cookbook#578]
**Description**

When downloading a new recipe from a URL for the first time, the recipe count does not update unless the page is reloaded.

**Reproduction**

1. Create new user
2. Attempt to add recipe from <https://www.allrecipes.com/recipe/22953/dark-chocolate-cake-ii/>
3. Observe recipe count

**Expected behavior**

Recipe count increases from 0 to 1.

**Actual behavior**

Recipe count does not increase.

**Workaround**

Reload the page.

**Screenshots**

![recipe](https://user-images.githubusercontent.com/50639/107794971-f73df500-6d0c-11eb-94c0-6618656defee.jpg)

**Browser**

Tested on both:

* Firefox on Ubuntu 20.04 LTS 64-bit Desktop
* Safari on iOS 14.3

**Versions**

Nextcloud server version: 20.0.7
Cookbook version:  0.7.10

**Comment by meonkeys** [comment]
FYI, I noticed that the Nextcloud "Users" config (`/settings/users`) seems to have the same thing going on with counts in the sidebar, so this may be an upstream issue. I deleted an inactive user and the count in the sidebar did not update until the page was reloaded. Maybe Nextcloud isn't tooled for these types of instant updates.

**Comment by christianlupus** [comment]
@seyfeb You did some work on the centralized Vuex state. Do you remember if the import should update the state correctly?

**Comment by seyfeb** [comment]
Yes, after the import the categories in the navigation should be updated. I need to have closer look to see what’s going wrong there.

**Comment by seyfeb** [comment]
I just tested this on the master branch and it is working for me. I close this for now. We can reopen if necessary.
