### ISSUE TITLE
Cookbook 0.8 dark Theme Description field not dark but white 

### ISSUE THREAD

**Issue by poltrian** [nextcloud/cookbook#587]
![Bildschirmfoto vom 2021-02-14 17-40-45](https://user-images.githubusercontent.com/50879520/107882942-43935b80-6eec-11eb-87d5-5b2982496e18.png)

**Comment by christianlupus** [comment]
This seems to be a problem with the Markdown component. We have to check if this can be styled accordingly.

**Comment by christianlupus** [comment]
Fixed in #1050

Now, I do no longer see the white background. The offending component was dropped completely.
