### ISSUE TITLE
Sort recipes by timestamp (created, edited)

### ISSUE THREAD

**Issue by seyfeb** [nextcloud/cookbook#594]
**Is your feature request related to a problem? Please describe.**

Sometimes I want so see the last edited or created recipes first in the list; especially in the index but probably also in the categories (once there are lots of recipes assigned to a single category). 

**Describe the solution you'd like**

Return timestamps with recipes and implement sorting recipes by date (created, modified) in index, categories, search (keyword & general). This would also allow showing the information on the recipe card. Add menu to select the order of the displayed recipes 

- alphabetically ascending
- alphabetically descending
- created ascending
- created descending
- edited ascending
- edited descending

**Describe alternatives you've considered**

Add ordering criteria to the server request, sort the list on the server and return sorted list.

**Comment by christianlupus** [comment]
Depending on the time of implementation, you could add asc/desc ordering in terms of rating.

I think it might be well suited for a set of computed properties to have all variants of sorting at hand. Then you can very quickly switch between the sorting algorithm, as I think. You avoid having to query the server each time you change the sorting.

**Comment by seyfeb** [comment]
> Depending on the time of implementation, you could add asc/desc ordering in terms of rating.

Good idea. If this one here is implemented first, it should be easily extendable to ratings.
