### ISSUE TITLE
Also accept https://schema.org/recipe => ichkoche.at not recognized + suggested fix

### ISSUE THREAD

**Issue by newton730ia** [nextcloud/cookbook#595]
**Description**
https://www.ichkoche.at/kartoffelknoedel-aus-dem-dampfgarer-rezept-179187 is not recogniced, 

seems itemtype="https://schema.org/Recipe" instead of itemtype="http://schema.org/Recipe" is the culprit. If I mirror this page and replace https with http here, it works. schema.org suggests to use https in general, so it should be supported here.
https://schema.org/docs/faq.html#19
"Q: Should we write 'https://schema.org' or 'http://schema.org' in our markup? There is a general trend towards using 'https' more widely, and you can already write 'https://schema.org' in your structured data. ... This is a lengthy way of saying that both 'https://schema.org' and 'http://schema.org' are fine.

**Reproduction**
1. Go to nextcloud backend/cookbook plugin.
2. Fetch recipe from 'https://www.ichkoche.at/kartoffelknoedel-aus-dem-dampfgarer-rezept-179187'
4. See error - User view: empty Javascript alert-box
Server: Server response of "Could not find recipe element", status code 500 on POST

**Expected behavior**
Import of recipe or at least non-empty error-message.

**Browser**
Chrome, current. Also happening with iOS-App

**Versions**
Nextcloud server version: 20.0.7
Cookbook version: 0.8.1

**Comment by christianlupus** [comment]
This should be solvable in #553.

**Comment by newton730ia** [comment]
Thanks, pull reqeust #553  contains fix. 
---
$selectorHttp = "*[@itemtype='http://schema.org/Recipe']";
$selectorHttps = "*[@itemtype='https://schema.org/Recipe']";
$xpathSelector = "$selectorHttp | $selectorHttps";
