### ISSUE TITLE
Blank Screen, vue.js doesnt load

### ISSUE THREAD

**Issue by Tom-Finke** [nextcloud/cookbook#597]
**Description**
I'm following the steps at https://github.com/christianlupus/nextcloud-docker-debug. But when I open the app, no content loads. Just a white screen. 
Console says:

- "Content security Policy" error 
- cant load the script `http://localhost:8000/custom_apps/cookbook/js/vue.js?v=01b5e611-0`

I cant find a the js folder under custom_apps/cookbook/js where the vue script is supposed to be.

I cloned the repository, did `npm install && make` and activated the app via occ.
What am i missing?

**Reproduction**
1. set up development environment
2. Open the App
3. See that theres nothin to see
**Browser**
Firefox 85.0.1 (64-Bit)

**Versions**
Nextcloud server version: 20.0.7
Cookbook version: 0.8.1 (according to info.xml)

**Comment by christianlupus** [comment]
In general, this seems like the correct way to get things going. I am assuming, that you cloned my [nextcloud-docker-debug repository](https://github.com/christianlupus/nextcloud-docker-debug) in `$PREFIX/nextcloud-docker-debug` (just for sake of easier writing here).

The cookbook repository needs to be installed in `$PREFIX/volumes/custom_apps/cookbook`. So, the file [package.json](https://github.com/nextcloud/cookbook/blob/master/package.json) should be in `$PREFIX/volumes/custom_apps/cookbook/package.json`.

I assume you can access the main nextcloud using http://localhost:8000/, right? Also, I assume you see the app in the navigation menu in the nextcloud instance. So the app is enabled in general.

Next the app needs to be installed. Go to `$PREFIX/volumes/custom_apps/cookbook/` and have a look at the `node_modules`, `vendor` and `js` folders. In `node_modules` and `vendor` are the JS and PHP dependencies installed by `npm install` and `make composer` (part of `make`). The content of `js` should have a `vue.js.gz` (possibly without the `.gz` postfix) and a `guest.js.gz` plus eventually a folder `chunks` with further JS files. Please post the output of `ls vendor node_modules js && du -sh node_modules vendor js` (in `$PREFIX/volumes/custom_apps/cookbook`) here if in doubt.

The *Content security Policy* error you mention is not necessarily part of the cookbook app. This can be triggered by the other apps as well. You have to check what triggered the request exactly. I have a similar message here locally but it is working nevertheless.

**Comment by Tom-Finke** [comment]
First of all, thanks for the quick response.

If cloned your nextcloud-docker-debug repository in $PREFIX/nextcloud-docker-debug, correct.
I can access the nextcloud an also open the cookbook app via the icon in the navigation bar. So the app is enabled, but doesn't display any content

package.json is at the Correct place.
My Directory Structure under $PREFIX/volumes/custom_apps/cookbook is as follows:

├── appinfo
├── docs
│   ├── admin
│   ├── dev
│   └── user
├── img
├── l10n
├── lib
│   ├── Controller
│   ├── Db
│   ├── Exception
│   ├── Helper
│   ├── Migration
│   └── Service
├── node_modules
│   ├── abab
│   ├── abbrev
│   ├── acorn
│   ├──  ...
├── src
│   ├── components
│   ├── router
│   └── store
├── templates
├── tests
│   ├── Integration
│   └── Unit
└── translationfiles

As you can see, neither the js nor the vendor folder are in there. 
`ls js vendor` just tells me the directory was not found and `ls nodemodules` shows all the modules as expected.
Same with `du -sh`. Because they just don't exist.
Are they supposed to be part of the github repository? Because they dont show up in the source code on [github](https://github.com/nextcloud/cookbook). 
Or should they be created when calling make?

**Comment by christianlupus** [comment]
They should be generated both by the `make` call. Make will both ensure `composer` is installed (otherwise install a local copy in working dir), then install the PHP dependencies in `vendor` and run `npm run build` to create the `js` folder with the vue generated files.

Are you sure, the `npm install` is terminating successfully? Otherwise, the `&&` will skip the `make` command... You can as well run `npm install` and `make` separately (but the `npm` is required for `make` to succeed).
