### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by MrColumbo** [nextcloud/cookbook#602]
**Description**
Opening cookbook in nextcloud show an internal server error

**Reproduction**
1. Go to nextcloud
2. Click on cookbook
3. See error

**Expected behavior**
See Cookbook Recipes

**Screenshots**

**Browser**
Which browser are you using?

**Versions**
Nextcloud version: 21.0.0 - 21.0.0.18
Cookbook version: 0.8.1

One thing I should note: I use groupfolders to have recipes shared between users and I already stepped into an error after nextcloud got updated since groupfolders first got autommatically deactcivated. I actcivated it and my group folders generally seem to work and I am not sure if the cookbook internal server has anything to do with that.

I also removed cookbook and "installed" it again

**Comment by seyfeb** [comment]
The app is not yet supporting NC 21, as discussed in #567 #341 #504. Closing this issue for now
