### ISSUE TITLE
error: [There is no table with name 'nextcloud.oc_cookbook_recipes' in the schema] 

### ISSUE THREAD

**Issue by pguraedy** [nextcloud/cookbook#609]
I receive the error: [There is no table with name 'nextcloud.oc_cookbook_recipes' in the schema] When I am attempting to install the cookbook on my nextcloud instance. I have a mariadb set up with a user that has all privileges. This user is what I filled in when setting up nextcloud, and Nextcloud is fully functional.

Would it be possible to get the scripts for the table creation to see if I can get past this message?

**Comment by christianlupus** [comment]
Hello.

**Literal solution to your request**:
You have to run the [migration steps](https://github.com/nextcloud/cookbook/tree/master/lib/Migration) in alphabetical order.

**Useful answer:**
Do not do it. This means that your version of NC is not compatible with cookbook ATM. See #341 #504 #602.
