### ISSUE TITLE
Error in NC21: Undefined class constant 'STRING'

### ISSUE THREAD

**Issue by t0mcat1337** [nextcloud/cookbook#616]
**Description**
When cookbook is started NC shows "Internal Server Error" Page. In NC Log this error occurs:
```
[index] Error: Exception: Undefined class constant 'STRING' at <<closure>>

0. /srv/www/my.domain/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Cookbook\Controller\MainController {}, "index")
1. /srv/www/my.domain/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Cookbook\\ ... r", "index", OC\AppFramework\ ... {}, {_route: "cookbook.main.index"})
2. /srv/www/my.domain/lib/base.php line 993
   OC\Route\Router->match("/apps/cookbook/")
3. /srv/www/my.domain/index.php line 37
   OC::handleRequest()

GET /apps/cookbook/
```

**Reproduction**
1. Open cookbook in NC 21

**Expected behavior**
Cookbook should be opened

**Browser**
Latest Chrome / Firefox

**Versions**
Nextcloud server version: 21
Cookbook version: 0.8.1

**Comment by seyfeb** [comment]
Thank you for opening this issue. The Cookbook app does not yet support NC21 (#567, #551, #341). This issue should be solved by PR #605 once it’s finished.

**Comment by t0mcat1337** [comment]
I thought so that NC 21 is not yet supported but wanted to give a try and report such errors for making it compatible ;)

**Comment by christianlupus** [comment]
The new version 0.8.3 was just pushed out with support for NC 21.
