### ISSUE TITLE
Can't load categories 

### ISSUE THREAD

**Issue by boreana** [nextcloud/cookbook#631]
**Description**
When I try to open a category, the app shows "Failed to load category $categoryname recipes" and is not able to show the recipes in that category.
_The thing is,_ that the error is not always reproducible for me. Loading a category has not worked for me for over a week. Yesterday it functioned again. Today it does not work.

I share my folder with other people on the nextcloud instance, but they only have reading permissions. They also have their own recipe folders (differently named), and to view the others' recipes we sometimes switch our cookbook folder in the app.
Maybe you could tell me if we are doing something we are not supposed to do that breaks the app?
I'd appreciate your help. I could not find an existing bug report that mentions my problem so I suppose that the problem somehow lies with us...

**Reproduction**
1. Open App
2. Click on any category
4. See error (not _always_, but most of the time on my machine)

**Expected behavior**
It should open the category page.

**Browser**
Mozilla Firefox 86

**Versions**
Nextcloud server version: 19.04
Cookbook version: 0.8.1

**Comment by christianlupus** [comment]
It would be important to know in which version you are running and if the current version (which will be 0.8.3 in a few minutes) is running.

Further, please try the following: Before opening the nextcloud app, please open the webconsole of firefox (press F12 to opan a docked window). There is a tab called network traffic (or similar). Open it.
Now, move to the cookbook app. If the categories load normally, all right. In the upper left corner of the network tab is a small trash to clean up things (if it gets really much). Continue surfing until the problem arises.
Once the issue happens again, stop surfing. Look through the requests made by firefox. Look for a status (first column) larger or equal to 400 (these are all error codes). If you click on a packet you get more information on what is sent and what is received.

If you are willing, you can send a HAR file to me. This might contain sensitive information, so it is your decision if you are willing. Anyways do **not** post it here. To create this, you can click on the small gear on the right top and click on *save everything as HAR file*. This will allow me to have a look on your network traffic.

**Comment by boreana** [comment]
Thanks @christianlupus for the detailed instructions, I managed to get the file and have send an email to you.
I have also updated the original post, we use Nextcloud server version 19.04 and (currently) Cookbook version 0.8.1

**Comment by christianlupus** [comment]
I just received and looked at the issue. For the sake of completeness, fetching of a category `Drink` caused the following log to emerge (I replaced the user name):

```
An exception occurred while executing 
'SELECT `r`.`recipe_id`, `r`.`name`, `k`.`name` as `keywords`
FROM `oc_cookbook_categories` `c` 
	INNER JOIN `oc_cookbook_names` `r` ON c.recipe_id = r.recipe_id 
	LEFT JOIN `oc_cookbook_keywords` `k` ON c.recipe_id = k.recipe_id
WHERE (c.name = ?) AND (c.user_id = ?)
GROUP BY `r`.`name`, `r`.`recipe_id`, `k`.`name`
ORDER BY `r`.`name` ASC'
with params ["Drink", "user_name"]:

SQLSTATE[42000]: Syntax error or access violation: 1104 The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay
```

I suspect your NC installation is a larger one or has at least a higher number of recipes stored (across all users), right?

**Comment by boreana** [comment]
I have 173 recipes stored. Two other users access my folder.
Another user has 6 recipes in a seperate folder. There are a few other users but I don't think they use the Cookbook app.
My category `Drink` has 2 recipes.

I can't really say if you would consider our NC installation is large. We have about 4 active users with <10GB each, which I would say sounds quite usual. By 'large', do you mean that we might have a lot of individual files stored in our Nexcloud which could cause those issues?

**Comment by christianlupus** [comment]
I have seen installations with 700 recipes. Recently there was a question about a timeout at a few thousand files if I remember correctly. So, this is small, I'd say. Mainly the recipes are of interest as the named SQL query is only using the cookbook app's tables. No other tables are involved.

Do you have access to the server/the database?

**Comment by boreana** [comment]
Sorry for getting back so late. Yes I have access.

**Comment by christianlupus** [comment]
No problem, was busy myself.

Could you just check if the cookbook tables have some leftovers in them? The tables are `oc_cookbook_names`, `oc_cookbook_categories` and `oc_cookbook_keywords`. You can check this by invoking e.g.
```
SELECT COUNT(1) FROM oc_cookbook_keywords;
```
The number in the `oc_cookbook_names` should be equal to the number of recipes cached (roughly the number of recipes stored, sharing doubles the number). If any table has a significant number of entries, this would be interesting to check.

**Comment by boreana** [comment]
`SELECT COUNT(*) FROM oc_cookbook_names;` returns 360.

Grouped by users, it matches the recipe count per user (users 2 and 3 have their cookbook app pointed at the same shared directory):

```
SELECT COUNT(*) FROM oc_cookbook_names GROUP BY user_id

COUNT(*)
6
177
177
```
`
SELECT COUNT(1) FROM oc_cookbook_keywords;` returns 464 entries.

`SELECT COUNT(*) FROM oc_cookbook_categories;` returns 510 entries.

Categories grouped by user:
```
SELECT COUNT(*) FROM oc_cookbook_categories GROUP BY user_id

COUNT(*)	
156	
177	
177	
```

**Comment by christianlupus** [comment]
Honestly, I am more than a bit surprised about the numbers. These seem quite *normal*. I have suspected to see some zombies in the database that need taking care of. Not the case.

What database are you using (MySQL, MariaDB, Postgres, Sqlite), and eventually which version?

I cannot do much ATM as the SQL seems neither wrong nor seems the DB uncommonly large. We could try some manual SQL invocations to see if these are running and if we can debug "manually" without the nextcloud overhead involved.

This one should break and cause the same error when invoked manually (note you must replace the user name):
```sql
SELECT `r`.`recipe_id`, `r`.`name`, `k`.`name` as `keywords`
FROM `oc_cookbook_categories` `c` 
INNER JOIN `oc_cookbook_names` `r` ON c.recipe_id = r.recipe_id 
LEFT JOIN `oc_cookbook_keywords` `k` ON c.recipe_id = k.recipe_id
WHERE (c.name = 'Drink') AND (c.user_id = 'user_name')
GROUP BY `r`.`name`, `r`.`recipe_id`, `k`.`name`
ORDER BY `r`.`name` ASC';
```

We could simplify a bit 
```sql
SELECT `r`.`recipe_id`, `r`.`name`, `k`.`name` as `keywords`
FROM `oc_cookbook_categories` `c` 
INNER JOIN `oc_cookbook_names` `r` ON c.recipe_id = r.recipe_id 
LEFT JOIN `oc_cookbook_keywords` `k` ON c.recipe_id = k.recipe_id
WHERE (c.name = 'Drink') AND (c.user_id = 'user_name');
```

And even more reduced:
```sql
SELECT `r`.`recipe_id`, `r`.`name`
FROM `oc_cookbook_categories` `c` 
INNER JOIN `oc_cookbook_names` `r` ON c.recipe_id = r.recipe_id 
WHERE (c.name = 'Drink') AND (c.user_id = 'user_name');
```

Please check in a first attempt if any of these SQL commands are able to be executed successfully and eventually how many rows are produced.

You cuould invoke 
```sql
SET SESSION SQL_BIG_SELECTS=1;
```
and try again. This will disable the protection of your database system and might cause slow queries (for debugging this is no big deal). Let's see how many rows are generated then.

**Comment by boreana** [comment]
Thanks for your ideas and your input, as well as your hint to `SQL_BIG_SELECTS`.

### MAX_JOIN_SIZE
I think I found our problem and it seems to lie with our host provider as well as how the prepared statement is used to retrieve rows:

`SHOW VARIABLES LIKE 'MAX_JOIN_SIZE'` returns 67,108,864, which apparently is just too low for these tables:

`oc_cookbook_names`  has 356, `keywords` has 481 and `categories` 504 rows, whose product 86,302,944 just barely exceeds our host's limit.

So it seems like the error message told me exactly what was wrong. And it explaines why the error was not consistent: After I worked on the recipe collection and deleted a few recipes and keywords I was below the limit again, but adding a new recipe the next day brought me over again.

I used a prepared statement replicating what the app does:
```sql
PREPARE category_stmt FROM 'SELECT
    `r`.`recipe_id`,
    `r`.`name`,
    `k`.`name` AS `keywords`
FROM
    `oc_cookbook_categories` `c`
INNER JOIN `oc_cookbook_names` `r` ON
    c.recipe_id = r.recipe_id
LEFT JOIN `oc_cookbook_keywords` `k` ON
    c.recipe_id = k.recipe_id
WHERE
    (c.name = ?) AND (c.user_id = ?)
GROUP BY
    `r`.`name`,
    `r`.`recipe_id`,
    `k`.`name`
ORDER BY
    `r`.`name` ASC';
    
SET @category_name = 'Drink';
SET @user_id = 'user1';
SET SQL_BIG_SELECTS = 1;
EXECUTE category_stmt USING @category_name, @user_id;
```
This works, but throws the error if run without the `SQL_BIG_SELECTS`. Manually inserting the variable values into the statement makes it work even without BIG_SELECTS.


For completeness, the response to your questions, before I had a look at `MAX_JOIN_SIZE`:

### Database
Database type configured in config.php is mysql, backed by MariaDB:

```sql
> SELECT VERSION()
10.3.25-MariaDB-1:10.3.25+maria~focal
```

All run on your typical shared PHP hosting provider.

### Invoking suggested queries

As you instructed, copy-pasting this exact query and just replacing both ?  with 'Drink' and  'user_name' (or with doublequotes) works fine in the database.

1. Query: works fine, returns 3 rows (2 recipes, one without keywords (NULL) and one with 2 keywords). Here is the result:

```sql
recipe_id	name   	keywords	
194366	Manhattan	NULL	
92125	Traditional British Pimm's	cocktail	
92125	Traditional British Pimm's	summer	
```

2. Query: also works, but returns 14 rows (same recipe-keyword tuples, but apparently 2 copies for each user_id (if I add that to the `SELECT` part); here an exact query (just obfuscated usernames):

```sql
SELECT `r`.`recipe_id`, `r`.`name`, `k`.`name` as `keywords`, `r`.`user_id`
FROM `oc_cookbook_categories` `c` 
INNER JOIN `oc_cookbook_names` `r` ON c.recipe_id = r.recipe_id 
LEFT JOIN `oc_cookbook_keywords` `k` ON c.recipe_id = k.recipe_id
WHERE (c.name = 'Drink') AND (c.user_id = 'user1')
ORDER BY r.name, `keywords`, c.user_id
```

And the result:

```sql
recipe_id	name   	keywords   	user_id	
194366	Manhattan	NULL	user2	
194366	Manhattan	NULL	user1	
92125	Traditional British Pimm's	cocktail	user2	
92125	Traditional British Pimm's	cocktail	user1	
92125	Traditional British Pimm's	cocktail	user2	
92125	Traditional British Pimm's	cocktail	user1	
92125	Traditional British Pimm's	cocktail	user2	
92125	Traditional British Pimm's	cocktail	user1	
92125	Traditional British Pimm's	summer	user1	
92125	Traditional British Pimm's	summer	user2	
92125	Traditional British Pimm's	summer	user1	
92125	Traditional British Pimm's	summer	user2	
92125	Traditional British Pimm's	summer	user1	
92125	Traditional British Pimm's	summer	user2	
```

3. Query: again 2 recipes, but 4 rows:

```sql
recipe_id	name	
92125	Traditional British Pimm's	
92125	Traditional British Pimm's	
194366	Manhattan	
194366	Manhattan	
```

All query durations are in the small millisecond range (1.1 to 5.9). After enabling SQL_BIG_SELECTS and repeating all three queries, identical results are returned.

### Invoking the API directly
Trying to get a better understand of what other /api/.. routes there were, I started trying out other routes that are defined within [appinfo/routes.php](https://github.com/nextcloud/cookbook/blob/b994f961ece09be403d032db679a47d988e5adce/appinfo/routes.php#L27).

No API link seem to work for us. I had a look through the code and when I enter the following in the browser (replacing baseUrl with the actual baseUrl)

`$window.baseUrl/api/category/foobar`
or
`$window.baseUrl/api/tags/foobar`
or
`$window.baseUrl/api/search/foobar`

with any existing **OR** non-existing category or tag name, I receive the original error (see [comment](https://github.com/nextcloud/cookbook/issues/631#issuecomment-790448230)).
I then tested the search function in the frontend and it also throws an error per [SearchResults.vue](https://github.com/nextcloud/cookbook/blob/master/src/components/SearchResults.vue#L121), which I hadn't noticed before. Selecting keywords in the frontend works.

...and this lead me to look for `MAX_JOIN_SIZE` (see above).

**Comment by christianlupus** [comment]
It would be interesting to see the execution plan for your installation. Just prepend `EXPLAIN` before the `SELECT` commands above. It will output the execution plan (a few lines). Please provide them here if possible. You can also put it in the prepared statement command and execute it later.

Additionally, I will give you a few commands to run in the database. Please be aware that these must be reversed before the database schema gets updated by a newly installed version of the cookbook app. To create the indexes (make a **database backup** before, in case anything goes wrong!):
```sql
ALTER TABLE oc_cookbook_names ADD PRIMARY KEY (recipe_id);
ALTER TABLE oc_cookbook_categories ADD INDEX username (user_name, name);
ALTER TABLE oc_cookbook_keywords ADD INDEX recipe(recipe_id);
```
This should make the queries run directly from the indexes and thus reduce the impact of large WHERE clauses. Again, the execution plan might be interesting now after the change.

To revert this, you have to
```sql
ALTER TABLE oc_cookbook_names DROP PRIMARY KEY;
ALTER TABLE oc_cookbook_categories DROP INDEX username;
ALTER TABLE oc_cookbook_keywords DROP INDEX recipe;
```

Can you check if this renders your instance stable again? Ideally, you do this once you run into the problem in the first place.

**For all users stumbling upon this check: This is *no* workaround. Do not do this without knowing what you are doing here. It might break any further updates of the app when not properly reversed!**

**Comment by boreana** [comment]
## Before ALTER TABLE

### Prepared statement explained

```sql
PREPARE category_stmt FROM 'EXPLAIN SELECT
    `r`.`recipe_id`,
    `r`.`name`,
    `k`.`name` AS `keywords`
FROM
    `oc_cookbook_categories` `c`
INNER JOIN `oc_cookbook_names` `r` ON
    c.recipe_id = r.recipe_id
LEFT JOIN `oc_cookbook_keywords` `k` ON
    c.recipe_id = k.recipe_id
WHERE
    (c.name = ?) AND (c.user_id = ?)
GROUP BY
    `r`.`name`,
    `r`.`recipe_id`,
    `k`.`name`
ORDER BY
    `r`.`name` ASC';

SET @category_name = 'Drink';
SET @user_id = 'user1';
SET SQL_BIG_SELECTS = 1;
EXECUTE category_stmt USING @category_name, @user_id;
```
yields
```sql
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra	
1	SIMPLE	r	ALL	NULL	NULL	NULL	NULL	397	Using temporary; Using filesort	
1	SIMPLE	c	ALL	NULL	NULL	NULL	NULL	458	Using where; Using join buffer (flat, BNL join)	
1	SIMPLE	k	ALL	NULL	NULL	NULL	NULL	470	Using where	
```
### Manually expanded statement explained
```sql
EXPLAIN SELECT
    `r`.`recipe_id`,
    `r`.`name`,
    `k`.`name` AS `keywords`
FROM
    `oc_cookbook_categories` `c`
INNER JOIN `oc_cookbook_names` `r` ON
    c.recipe_id = r.recipe_id
LEFT JOIN `oc_cookbook_keywords` `k` ON
    c.recipe_id = k.recipe_id
WHERE
    (c.name = "Drink") AND (c.user_id = "user1")
GROUP BY
    `r`.`name`,
    `r`.`recipe_id`,
    `k`.`name`
ORDER BY
    `r`.`name` ASC;
```
yields
```sql
id 	select_type 	table 	type 	possible_keys 	key 	key_len 	ref 	rows 	Extra 	
1 	SIMPLE 	r 	ALL 	NULL 	NULL 	NULL 	NULL 	397 	Using temporary; Using filesort
1 	SIMPLE 	c 	ALL 	NULL 	NULL 	NULL 	NULL 	458 	Using where; Using join buffer (flat, BNL join)
1 	SIMPLE 	k 	ALL 	NULL 	NULL 	NULL 	NULL 	470 	Using where
```

At this level, the manual parameter insertion does not seem to have any effect.
Just to be sure, here are the `EXPLAIN`ed versions of your other suggested queries from two posts above:
```sql
EXPLAIN SELECT `r`.`recipe_id`, `r`.`name`, `k`.`name` as `keywords`
FROM `oc_cookbook_categories` `c` 
INNER JOIN `oc_cookbook_names` `r` ON c.recipe_id = r.recipe_id 
LEFT JOIN `oc_cookbook_keywords` `k` ON c.recipe_id = k.recipe_id
WHERE (c.name = 'Drink') AND (c.user_id = 'user1')
GROUP BY `r`.`name`, `r`.`recipe_id`, `k`.`name`
ORDER BY `r`.`name` ASC;
```
yields the exact same execution plan.

Variant no. 2 differs in table `r` slightly, namely in the omission of a `temporary + filesort`:
```sql
EXPLAIN SELECT `r`.`recipe_id`, `r`.`name`, `k`.`name` as `keywords`
FROM `oc_cookbook_categories` `c` 
INNER JOIN `oc_cookbook_names` `r` ON c.recipe_id = r.recipe_id 
LEFT JOIN `oc_cookbook_keywords` `k` ON c.recipe_id = k.recipe_id
WHERE (c.name = 'Drink') AND (c.user_id = 'user1')
```
yields
```sql
id 	select_type 	table 	type 	possible_keys 	key 	key_len 	ref 	rows 	Extra 	
1 	SIMPLE 	r 	ALL 	NULL 	NULL 	NULL 	NULL 	397 	
1 	SIMPLE 	c 	ALL 	NULL 	NULL 	NULL 	NULL 	458 	Using where; Using join buffer (flat, BNL join)
1 	SIMPLE 	k 	ALL 	NULL 	NULL 	NULL 	NULL 	470 	Using where
```

Variant no. 3's execution plan finally looks just truncated, so for completeness:
```sql
EXPLAIN SELECT `r`.`recipe_id`, `r`.`name`
FROM `oc_cookbook_categories` `c` 
INNER JOIN `oc_cookbook_names` `r` ON c.recipe_id = r.recipe_id 
WHERE (c.name = 'Drink') AND (c.user_id = 'user1')
```
yields
```sql
id 	select_type 	table 	type 	possible_keys 	key 	key_len 	ref 	rows 	Extra 	
1 	SIMPLE 	r 	ALL 	NULL 	NULL 	NULL 	NULL 	397 	
1 	SIMPLE 	c 	ALL 	NULL 	NULL 	NULL 	NULL 	458 	Using where; Using join buffer (flat, BNL join)
```

## After `ALTER TABLE`
The executed commands were:
```sql
ALTER TABLE oc_cookbook_names ADD PRIMARY KEY (recipe_id, user_id);
ALTER TABLE oc_cookbook_categories ADD INDEX username (user_id, name);
ALTER TABLE oc_cookbook_keywords ADD INDEX recipe(recipe_id);
```
Remark: `recipe_id` alone is not unique if multiple users share a recipe folder. Only `(recipe_id, user_id)` seems to guarantee uniqueness.

The result: category browsing works, instantaneously.

After reverting the changes I confirmed that the issue returned. I applied the commands one by one and found that the first `ADD PRIMARY KEY` was enough to "fix" the symptom (category page worked again), but the other two commands did not hurt either.

And the execution plan for `category_stmt` (both unexpanded and manually expanded) looks promising as well:

```sql
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra 	
1 	SIMPLE 	c 	ALL 	recipe_id 	NULL 	NULL 	NULL 	661 	Using where; Using temporary; Using filesort
1 	SIMPLE 	r 	ref 	PRIMARY 	PRIMARY 	4 	db_nextcloud.c.recipe_id 	1 	
1 	SIMPLE 	k 	ref 	recipe 	recipe 	4 	db_nextcloud.c.recipe_id 	1 	
```
And fulltext search works again as well.

**Comment by christianlupus** [comment]
> The result: category browsing works, instantaneously.
> 
> After reverting the changes I confirmed that the issue returned. I applied the commands one by one and found that the first ADD PRIMARY KEY was enough to "fix" the symptom (category page worked again), but the other two commands did not hurt either.

Yes, the problem vanishes with one index as you seem to be close to the boundary with your database. So as you calculated you are passing the limit just by a small bit so one simplification should help to get you running but the other index might be needed as well for other instances (and will for sure boost all instances).

> And the execution plan for category_stmt (both unexpanded and manually expanded) looks promising as well:
> ```
> id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra 	
> 1 	SIMPLE 	c 	ALL 	recipe_id 	NULL 	NULL 	NULL 	661 	Using where; Using temporary; Using filesort
> 1 	SIMPLE 	r 	ref 	PRIMARY 	PRIMARY 	4 	db_nextcloud.c.recipe_id 	1 	
> 1 	SIMPLE 	k 	ref 	recipe 	recipe 	4 	db_nextcloud.c.recipe_id 	1 	
> ```
> 
> And fulltext search works again as well.

That looks all good and I think we can consider the root of the issue to be found. I will try to get a PR running in the next few days (on this week I have a pressing issue in my day job at hand so it might get the end of the week or next weekend till I can implement this fix permanently.

> Remark: recipe_id alone is not unique if multiple users share a recipe folder. Only (recipe_id, user_id) seems to guarantee uniqueness.

You are right, the uniqueness requires both in the current DB schema. There are however two things to consider: First, see #658 where we have a bug that the `user_id` is not considered at all (one reason for the `GROUP BY`). Second, the `recipe_id` is the ID from the folder of the recipe which is constant for all users. So this information is stored redundantly. I was going to update the complete schema but did not yet find the time to get all things going (especially as our codebase needs manual testing currently).
So, all in all: Good catch, a bug of a bug of a bad design. :smile:

**Comment by christianlupus** [comment]
@boreana may I ask you how long it took to build the indices (computational time)?

I am asking as I fear problems during the installation steps and I need to make sure the installation can build the index without a timeout by the web server.

**Comment by boreana** [comment]
@christianlupus The indices built almost instantly on our server, not really noticable. I can't provide a number, sorry, but I don't believe that the operation will cause timeout problems.

**Comment by christianlupus** [comment]
ok, the change is committed as I guessed that the impact would not be too much. I will keep it that way. Thank you for confirmation.
