### ISSUE TITLE
Running PHP unittests Locally

### ISSUE THREAD

**Issue by Tom-Finke** [nextcloud/cookbook#637]
I have trouble Running the phpunit Unittests locally.
I opened an [issue](https://github.com/nextcloud/app-tutorial/issues/274) on the Nextcloud App Tutorial Repository, but they dont seem to be actively answering to issues, so I thought I'd try my luck here.

It doesnt only affect the App Tutrorial, its the same when running unittests for the cookbook app.

When I Clone the Repository and run the Unittests, i get the following error:
```
PHP Warning:  require_once(installdir/app-tutorial/tests/../../../tests/bootstrap.php): failed to open stream: No such file or directory in installdir/app-tutorial/tests/bootstrap.php on line 3
PHP Fatal error:  require_once(): Failed opening required 'installdir/app-tutorial/tests/../../../tests/bootstrap.php' (include_path='.:/usr/share/php') ininstalldir/app-tutorial/tests/bootstrap.php on line 3
```
Are there any prerequisites for running the Unittests?
What is going on with the Bosstrap.php? Why does it require itself but from 3 Directories up?
How Can I get the Unittests to run?

Im trying to develop a Nextcloud App and I can only run the unnitests via Github Actions, which makes debugging very tedious because I have to push every time.

Thank you in advance

**Comment by christianlupus** [comment]
The thing is that the unittests might need parts of the nextcloud core. So the relative path to `../../../tests/bootstrap.php` includes these NC files. It is assumed, your app is installed in an NC instance (not necessarily setup correctly but the files are there).

This request is not cookbook related, so I will close it here. I might however point you to [my repository for development](https://github.com/christianlupus/nextcloud-docker-debug). It is written based on the cookbook app's experience but generally useable.

**Comment by Tom-Finke** [comment]
Thank you for the quick response.
I'll try to figure it out.
