### ISSUE TITLE
cookbook, no picture after printing recipe

### ISSUE THREAD

**Issue by peterkrist** [nextcloud/cookbook#638]
with each recipe is included a picture of the dish. If a printout is created via the printer or pdf, the recipe picture is missing

**Reproduction**
1. Go to 'Rezept drucken'
2. in the print preview is only the recipe without the picture

**Expected behavior**
The recipe image should appear on the print

**Screenshots**
screenshot in NC
![NC20_Cookbook0-8-3_orginal](https://user-images.githubusercontent.com/80039986/109957295-06e5a380-7ce5-11eb-986b-87d8c9e0c7ad.PNG)
no image on print preview
![NC20_Cookbook0-8-3_no_image](https://user-images.githubusercontent.com/80039986/109957314-0d741b00-7ce5-11eb-8f05-f02b5a31053d.PNG)

**Browser**
Firefox, Opera, IE

**Versions**
Nextcloud server version: 20.0.8
Cookbook version: 0.8.3

**Comment by christianlupus** [comment]
There is a switch to enable/disable printing of images in the settings. Please check if this is set correctly.

**Comment by peterkrist** [comment]
Thank you very much, now it works fine. 
![grafik](https://user-images.githubusercontent.com/80039986/109965551-634dc080-7cef-11eb-9700-a3f9fd1bcbbb.png)

Over 5 weeks ago i posted a tread on help.nextcloud about this topic. No one could help me there
Thanks again for your great work to create this beautiful cookbook
Peter
