### ISSUE TITLE
Apostrophe bug since latest version

### ISSUE THREAD

**Issue by Thovi98** [nextcloud/cookbook#640]
**Description**
Since one of the latest versions, there is a viewer bug for some characters... When I write a recipe by myself, there isn’t the problem, but well when I import a recipe from marmiton.org.

Here a screenshot of an imported recipe : 

When entering editing mode of an imported recipe (no problem):
![2021-03-04 14_17_48-Livre de recettes - Nextcloud](https://user-images.githubusercontent.com/51749973/109970002-da398800-7cf4-11eb-80fe-ebef83c0816a.jpg)

When viewing only an imported recipe  (problem with` ’`):
![2021_03_04_14_15_32_Livre_de_recettes_Nextcloud](https://user-images.githubusercontent.com/51749973/109969916-c0984080-7cf4-11eb-87cb-b3b389bd08a5.jpg)

If I edit the recipe and rewrite the apostrophe, the bug is gone. I suspect Nextcloud Cookbook to not be able anymore to andle all sorts of apostrophes.

Good to know, when viewing in @Teifun2’s Android app, the apostrophes appaers without problem.

Here’s a recipe example : https://www.marmiton.org/recettes/recette_soupe-aux-lentilles-corail_27918.aspx#d92019-p3

If I can tell more to help you, I would be happy to do it.

Thanks.

**Browser**
Firefox, latest version.

**Versions**
Nextcloud server version: 20.0.7
Cookbook version: 0.8.3

**Comment by seyfeb** [comment]
Thanks for reporting, I’ll fix this one!
