### ISSUE TITLE
Slash in fraction displays as undefined

### ISSUE THREAD

**Issue by j1s2** [nextcloud/cookbook#641]
New install of version 0.8.3 on NextCloud 21 using Chrome.  Import a recipe via url.  The edit screen shows the ingredient's fraction as 1 1/2 tablespoons or 1/4 cup, but the main view screen displays 1 1undefined2 tablespoons and 1undefined4 cup under the Ingredients list.
![NCCookbook1](https://user-images.githubusercontent.com/80059998/110002051-ffbd9600-7ce2-11eb-978e-3118e3ef2d82.PNG)

**Comment by seyfeb** [comment]
Thanks for reporting, I’ll fix this one!
