### ISSUE TITLE
Ability to hide tag cloud

### ISSUE THREAD

**Issue by davidrutland** [nextcloud/cookbook#643]
**Is your feature request related to a problem? Please describe.**
The tag cloud at the top of the main page takes up screen real estate and cannot be hidden. At the same time, the space isn't large enough to be actually useful. At the moment, it's just in the way.

**Describe the solution you'd like**
A toggle, checkbox, or radio button which would allow users to display or hide recipe tags

**Describe alternatives you've considered**
Moan about it in the issues section

**Comment by seyfeb** [comment]
Could you elaborate a bit on why it is not useful? 
Are you not able to filter recipes using the tags? Or is it only because you are not able to see all existing tags at the same time?

Which device are you using to access the app? What is your Screen/browser size?

**Comment by davidrutland** [comment]
I have 46 recipes stored, this has generated ~ 120 tags. On my my laptop screen (1400 x 900), I can see a maximum of 30 at one time. On my mobile (Ubuntu Touch webapp), I can see ten tags. Because of this, the tag cloud isn't useful as a way of browsing recipes.

Tags definitely have utility, just not the way they're displayed right now.



![image](https://user-images.githubusercontent.com/78873800/110015448-c6ede300-7d1b-11eb-9d86-1f47283d3108.png)

**Comment by christianlupus** [comment]
Maybe a setting like the printing of the recipe images?

**Comment by davidrutland** [comment]
That would do it

**Comment by seyfeb** [comment]
not sure if hiding it in the settings is the best way to go. although with 'visible' as a default, it might work. a toggle between 'hidden' and 'full screen' directly in the recipe list could also be possible
