### ISSUE TITLE
Edit nutrition info of existing recipes 

### ISSUE THREAD

**Issue by Thomas-Lupo** [nextcloud/cookbook#652]
I cannot add  nutrition info of recipes if there are none

If I edit an existing recipes created automatically with an former version of cookbook i cannot add any nutrition details, the selected option is not accepted. There is no issue when a recipe is just created or if I edit an existing recipe that already has any nutrition info.

Firefox 86.0
Nextcloud Server 20.0.8
Cookbook 0.8.4

**Comment by seyfeb** [comment]
Hi @Thomas-Lupo, could you please provide a json file of a recipe which you cannot edit?

**Comment by Thomas-Lupo** [comment]
Hi seyfeb,

here is a jason file of an affected recipe
[recipe.zip](https://github.com/nextcloud/cookbook/files/6121274/recipe.zip)

**Comment by seyfeb** [comment]
> Hi seyfeb,
> 
> here is a jason file of an affected recipe
> [recipe.zip](https://github.com/nextcloud/cookbook/files/6121274/recipe.zip)

Thanks, that helped!
