### ISSUE TITLE
Sort keywords alphabetic

### ISSUE THREAD

**Issue by Zocker1999NET** [nextcloud/cookbook#660]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to search a specific recipe and the tags/keywords of a recipe or for all recipes are sorted by creation date, not alphabetic.

**Describe the solution you'd like**
Sort keywords in RecipeList, RecipeView and RecipeEdit always alphabetic, which makes it faster to search for specific or probably similar keywords and allows user to sort them their selves by e.g. using "1.", "2.", …

**Describe alternatives you've considered**
Probably sort by anything else, but it should be consistent, ~but also not depend on creation date like an incrementing database id, as this does not allow users to determine the order other than by deleting and re-creating all keywords.~ (after realizing they are currently sorted by number), but please do not sort them by count of recipies or let the user decide about the order, because IMO sorting them by count makes the sorting not really helpful, but painful because after adding/editing a recipe, you might need search again for a special tag because it changed its place.

**Comment by seyfeb** [comment]
In the search view the tags should currently be ordered by the decreasing number of recipes with the keyword assigned. We could think of adding a setting for switching between different criteria for the ordering either in the general settings (such as for the "print image" switch or next to the keywords.

**Comment by christianlupus** [comment]
For the reference, this might be related with #643
