### ISSUE TITLE
Add share recipe

### ISSUE THREAD

**Issue by tim-krehan** [nextcloud/cookbook#665]
**Is your feature request related to a problem? Please describe.**
No issues / Problem

**Describe the solution you'd like**
Add sharing functionality to single recipes. Maybe the NC sharing could be used to just share the files to another user. If this works nice, maybe add category sharing as well.
I was thinking that you could add the button in the view of the single recipe.
Maybe one could always have a dropdown there, as (badly) sketched here:
![IMG_20210326_172155](https://user-images.githubusercontent.com/39102356/112662387-ecbc6280-8e57-11eb-821c-b64c59d92c0e.jpg)

Maybe that would be a solution to #291 as well.

**Comment by tim-krehan** [comment]
Also: is it possible to add a public sharing of a recipe?
Leveraging the "share by Link" functionality of nextdoor. Where you can sent the link and so on.

**Comment by seyfeb** [comment]
Duplicate.

Sharing with NC users, see #120 
Public sharing see #392 
related to #340
