### ISSUE TITLE
When typing a "3" the reference menu opens

### ISSUE THREAD

**Issue by MarieSaphira** [nextcloud/cookbook#670]
**Description**
When typing a "3" into Tools, Ingredients or Instructions fields, a menu to select a reference to another recipe is opened (see screenshot in the middle.

**Reproduction**
1. Go to the cookbook app in your nextcloud webapp
2. Click on 'Create new recipe'
3. Type a "3" into a Tools, Ingredients or Instruction field
4. See reference menu

**Expected behavior**
I expect nothing additional to happen when typing a "3".

**Screenshots**
![references](https://user-images.githubusercontent.com/39989230/113478366-b484d780-9488-11eb-8741-93985083ff70.png)

**Browser**
Firefox  87.0 for Manjaro

**Versions**
Nextcloud server version: 20.0.8
Cookbook version: 0.8.4

**Comment by christianlupus** [comment]
This should be solved in #648, which is already in 0.8.4. So, the fix in #648 was not 100% successful.

I check and can confirm the behavior. It seems that the patch forgot this occurrence: https://github.com/nextcloud/cookbook/blob/f698ee152cb6505a53ff8b02040dc48e546d20ae/src/components/EditInputGroup.vue#L230
