### ISSUE TITLE
 Categories don’t work

### ISSUE THREAD

**Issue by spiderrider** [nextcloud/cookbook#675]
**Description**
It’s not possible to add a categorie. If I have an existing recipe I can not change the categorie. I have to go into the database to make any changes. I think this is not the idea.

**Expected behavior**
I would like to click on the pen icon and get something like "add categorie".

**Browser**
Chrome, Firefox, Opera

**Versions**
Nextcloud server version: 21.0.0
Cookbook version: 0.8.4

**Comment by seyfeb** [comment]
Categories themselves are no objects in the cookbook that can be added. They are only extracted from the data of the recipes. A new category will be shown, once you have added a recipe with a new category. No need to edit the database ;)

The edit/pen icon is only a convenience function that allows batch-editing the category field of all recipes that currently have the category assigned!
