### ISSUE TITLE
White page on loading the app in NC 21.0.1

### ISSUE THREAD

**Issue by vincegre** [nextcloud/cookbook#691]
**Description**
I have installed cookbook in my NC 21.0.1 and when I try to access all I get is a white page with a black line at top !

**Reproduction**
1. install coockbook app in NC 21.0.1
2. Access the app
3. All you get is a white page with a black line at top

**Expected behavior**
App to display so I can use it

**Screenshots**
![Screenshot_20210424_144433](https://user-images.githubusercontent.com/3164888/115959468-a288d880-a50c-11eb-8fc9-2da2e55498cb.png)

**Browser**
Firefox 87.0 64bits on Ubuntu 20.04

**Versions**
Nextcloud server version: 21.0.1
Cookbook version: 0.8.4

I have checked Nextcloud log but found nothing related with coockbook in it :(

**Comment by christianlupus** [comment]
Hello @vincegre, I have a few questions:

1. Have you installed NC21 during the beta release phase and tried the cookbook app then as well?
2. I assume, you installed it from the app store, right?
3. What does the browser log tell you? Which requests are failing?
4. Anything in the browser console?

If the last two points are unclear, just ask. I will try to answer in detail.

**Comment by vincegre** [comment]
>     1. Have you installed NC21 during the beta release phase and tried the cookbook app then as well?

Nope it's a long time setup NC and I do only stable updates of it, no beta or alpha !
 
>     2. I assume, you installed it from the app store, right?

I'm not so sure, I think I installed it by hand..
 
>     3. What does the browser log tell you? Which requests are failing?

![Screenshot_20210425_105436](https://user-images.githubusercontent.com/3164888/115987273-b1c36100-a5b4-11eb-8777-89e7a489ff94.png)
Is it what you need ?
 
>     4. Anything in the browser console?

![Screenshot_20210425_105628](https://user-images.githubusercontent.com/3164888/115987375-1383cb00-a5b5-11eb-86d0-c7220f723aff.png)
![Screenshot_20210425_105706](https://user-images.githubusercontent.com/3164888/115987383-1979ac00-a5b5-11eb-95b6-ee9c990f5d63.png)

That's all I could find in the browser, hope it's enough ;) If not let me know what you need else or if I have to test something ?

Thanks

**Comment by vincegre** [comment]
>     1. Have you installed NC21 during the beta release phase and tried the cookbook app then as well?

As I was not sure how I installed it, I removed it from my NC and reinstalled it from the app store and now it loads fine ;) Sorry for that, I should have tried that first...

**Comment by christianlupus** [comment]
No problem. Most probably you had only the raw code without the dependencies installed. You are welcome.
