### ISSUE TITLE
Recipe website user experience

### ISSUE THREAD

**Issue by shaneonabike** [nextcloud/cookbook#704]
**Is your feature request related to a problem? Please describe.**
I came across this article, which I found it really interesting to engage for more (long term) changes that could be considered for cookbook. Seriously though I really love this extension it is amazing!

Ref: https://www.simeongriggs.dev/designing-a-more-complete-recipe-website

**Describe the solution you'd like**

- [ ] Checkbox on ingredients (this one is already there on the steps but I would love that for ingredients)
- [ ] Conversion tool (from grams to ounce)

**Comment by seyfeb** [comment]
Hi Shane, what version of the app are you using? There should already be the possibility to add checkmarks to the ingredients.

**Comment by shaneonabike** [comment]
I have the latest but the ingredients only appear as a list of dashes not items I could check off (on Android). Essentially, what I am doing is importing recipes from other sites to reuse, and perhaps that's an element missing from my description. Could a checklist be setup automagically.. .or maybe the import is already complicated...

AGAIN thanks for your awesome work!

**Comment by seyfeb** [comment]
In the current version it is possible to tap the ingredients to add a checkmark - also in a mobile browser. I admit that there might be a way to make this more intuitive. 

If this is really not possible for you, could you share some more information on the exact version number of the Cookbook app and NC instance and the mobile browser you are using and maybe your screen resolution?

**Comment by shaneonabike** [comment]
AH I see you implemented in the mobile version that's so awesome! I was actually thinking more the mobile app since I don't always have a laptop in front of me. Is that also implemented in the mobile app cause I'm on the latest.

**Comment by seyfeb** [comment]
There are multiple Android clients that I know of (see [e.g. in the Readme](https://github.com/nextcloud/cookbook/blob/master/README.md#clients)) which are developed in other repositories (also referenced in the Readme). Please ask in the corresponding repo for this feature since we are only working on the Nextcloud (browser) app and the backend here!

I’m closing this since this issue is not related to the NC App!

**Comment by shaneonabike** [comment]
Although on second reflection my point about conversion isn't a terrible idea for the future

**Comment by seyfeb** [comment]
That is true, but already discussed in #116 ;)
