### ISSUE TITLE
Multiple whitespaces should be trimmed when pasting

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#713]
**Description**
When copy&pasting a recipe, sometimes there are additional whitespaces added. These should be trimmed.

**Reproduction**
1. Go to e.g. [this page](https://www.gutekueche.at/schweinemedaillons-aus-dem-sous-vide-rezept-28593)
2. Copy the list of ingredients
3. Go to the cookbook app, create a new recipe
4. Add a ingredient and paste the clipboard there

**Expected behavior**
The ingredients are added one-by-one as ingredients. The (original) table structure should be broken apart.

**Actual behavior**
The table is transformed into a tab sequence. The tabs (or any adjacent spaces in general) should be trimmed. 

The same effect holds true for the instructions (and potentially the tools).

**Browser**
Firefox 88.0 under Firefox

**Versions**
Nextcloud server version: 21.0.1
Cookbook version: 0.8.4 (appstore)
Database system: MariaDB

**Comment by MarcelRobitaille** [comment]
I'm closing this because I think it was fixed with #887? I'm sorry, I did not notice this issue. Please re-open if it's a different issue.

Here is what I get when pasting the ingredients from that website on the master branch. It looks right to me.
![image](https://user-images.githubusercontent.com/8503756/159132574-9a813761-5295-4146-af72-2dd3b997624e.png)

**Comment by seyfeb** [comment]
actually... @MarcelRobitaille  in your image there are definitely multiple spaces between the number and unit or the unit and ingredient name, no? so I wouldn't think that it's fixed ;)

**Comment by MarcelRobitaille** [comment]
Oh, I see. The middle spaces. This should be an easy fix. We can just replace `/\s+/` with ` `  (single space). What do you think? I can make a PR.

**Comment by seyfeb** [comment]
Absolutely, that would be great. But only when pasting. I’d say if somebody insists on having multiple spaces and saves the recipe this way we shouldn’t interfere

**Comment by MarcelRobitaille** [comment]
Yes, I agree. Only when pasting. We don't want to forbid someone from putting a double space if they really want to.

**Comment by christianlupus** [comment]
Also, add the tab char to your regex.

Should we correct the JSON files as well? If yes, we could do this in the backend maybe easier. Just a suggestion/questrion for discussion.

**Comment by MarcelRobitaille** [comment]
> Also, add the tab char to your regex.

`\s` matches all whitespace including tab, so that should be covered.

> Should we correct the JSON files as well? If yes, we could do this in the backend maybe easier. Just a suggestion/questrion for discussion.

I'm sorry, I do not understand this part. Is there an option to paste JSON?

**Comment by christianlupus** [comment]
What do you mean by paste? The JSON is stored in the backend. So, we can either store the newly created recipes correctly (old recipes will not be affected) or do some filtering in the backend (some sort of repair step). Additionally (or alternatively), we can filter in the frontend the content as well to have a well-suited presentation for the user.

Personally, I'd like to have clear JSON files. But solving in the frontend might be a first step here. Adding the backend part can be done later when a filter is present in the frontend.

**Comment by christianlupus** [comment]
PS: If we want to have it in the Backend as well, please do not close the issue or open another one for the backend to keep track of tasks.

**Comment by seyfeb** [comment]
I cite myself here:

>  I’d say if somebody insists on having multiple spaces and saves the recipe this way we shouldn’t interfere

which is a contra for the "repair step" idea

**Comment by MarcelRobitaille** [comment]
Oh, I see. So the options are (A) store the data as pasted, and transform it before displaying it or (B) clean the data and then save it to the backend.

I think A is better. We should fix it immediately on paste only. Otherwise, we have to track what was pasted and what was edited manually to fix it in the backend. I don't think it's worth the complexity.
