### ISSUE TITLE
[question] Migrating from gnome-recipes to nextcloud cookbook

### ISSUE THREAD

**Issue by cslux** [nextcloud/cookbook#714]
Hello and thank you for developing this app!

I want to migrate my gnome-recips to nextcloud cookbook. However, I saw that the *recip.json* file has a key *id*. Can I just generate a unique ID? I'm also not sure how it will behave when I don't use the UI to point to the image. I have synced all images used previously to nextcloud, and would set the key image to the location in nextcloud. Will this work? Is there anything else which might make troubles?

Thank you!

**Comment by christianlupus** [comment]
Hello @cslux, the id is not required to be set. In fact, it must not be set arbitrarily but must reflect the id of the parent folder. So, better do not worry about it and put the JSON file into a matching folder with the storage folder. The trigger a library rescan.

Regarding the images: Each recipe has one image attached. Within the storage folder, I have a recipe *Karamellisierte Jakobsmuscheln*. The folder structure is as below.
```
Karamellisierte Jakobsmuscheln/
├── full.jpg
├── recipe.json
├── thumb16.jpg
└── thumb.jpg
```
The `full.jpg` is the image to be shown while the `thumb*.jpg` are smaller images to have quicker laoding times.

If you have the images in your NC already, you can iterate over all recipes (manually) and set the image to the corresponding image files. This will save a copy into the recipe folder and generate the thumbnails as well.

It should work straightforward but as always with bigger migrations: Better safe than sorry. So make a backup (the recipe folder and the recipe images should be sufficient) before.

**Comment by cslux** [comment]
Hello @christianlupus! Thank you, that sounds good.

**Comment by cslux** [comment]
Worked, thanks! Copying the image to RECIPE/full.jpg seems to be enough. Thumbnails will than be generated. Just tested, but did it manually yesterday EDIT -> SAVE recipe.
