### ISSUE TITLE
Android App missing recipes

### ISSUE THREAD

**Issue by r1ckdu** [nextcloud/cookbook#715]
**Description**
3 of 23 recipes are not listed in the android app, despite being synced to the device.

**Reproduction**
Unclear. Not sure why some do not get shown as available recipes

**Expected behavior**
All recipes are listed

**Actual behavior**
Some are missing.

**Screenshots**
![Screenshot_20210508-155017](https://user-images.githubusercontent.com/74661886/117541658-2070d780-b015-11eb-87ec-6e2c7ffa6a2a.png)
![Screenshot_20210508-155006](https://user-images.githubusercontent.com/74661886/117541661-236bc800-b015-11eb-936d-32c1d3f0c47a.png)

**Browser**
Firefox for Android

**Versions**
Nextcloud server version: 20.0.8
Cookbook version: 0.8.4
Database system: mysql

**Comment by christianlupus** [comment]
@r1ckdu Just to make things clear: Where are the recipes missing? When you access the cookbook app using your android firefox (as a web app) or when using one of the native android apps?
If the problem is the web app, can you check with a "normal" PC/laptop to check the DB is up to date?

**Comment by r1ckdu** [comment]
See the screenshots. On the browser everything is there. The android cookbook app has the problems.




08.05.2021 20:33:39 Christian ***@***.***>:

**Comment by christianlupus** [comment]
Unfortunately, I do not get the problem in the screenshots but this is not a big problem here. The thing is that the android app is not developed by this repo but separately. In fact, there are two apps (see [the README](https://github.com/nextcloud/cookbook#android)). You might need to check which app you have and contact the corresponding developer for support.

Sorry, here we cannot help you much if it is the app that is malfunctioning. If the website works, the rest is up to the 3rd parts apps.
