### ISSUE TITLE
SeriousEats.com not supported: Type as array

### ISSUE THREAD

**Issue by cgudea** [nextcloud/cookbook#724]
**Description**
Cookbook is unable to parse recipes from SeriousEats. An example recipe: https://www.seriouseats.com/best-vegetarian-bean-chile-recipe

It appears serious eats supports the schema.org recipe schema when validated using this tool: https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=message&id=RdUWXfeh2rNtVXvkNj9fVg

It seems like the json is valid. Is this a bug on cookbook's side or an issue on SeriousEats' side? I'm not super familiar with the recipe schema but it seems like cookbook shouldn't have an issue parsing this.

**Expected behavior**
A successful import of the recipe

**Actual behavior**
500 code, failure to parse recipe

**Browser**
Safari/Firefox

**Versions**
Nextcloud server version: 20.0.7
Cookbook version: 0.8.4
Database system: MySQL

**Comment by christianlupus** [comment]
I can confirm that the import fails.

However, I cannot confirm that the page provides generally any schema.org meta data. The google rich text result can extract meta data but when manually searching in the HTML source code. It might well be the case that the page SeriousEats.com added some protection to avoid their recipes from been parsed, extracted and thereby stolen by other pages. In this case, we are affected by this block as well.

Unless we find a way to extract the metadata from the sourcecode, we can not do much about this issue. I tried in a quick manner and did not succeed. So, if anyone is able to come up with a solution, step forward, we might be able to implement a solution. Until then, I will consider this a closed issue and activate stale bot on it.

**Comment by bfritscher** [comment]
The content is loaded via javascript in a deferred manner so it might be impossible without using a headless browser or a proxy with headless-browser which then renders the complete source  :-( "<script id="schema-lifestyle_1-0" class="comp  schema-lifestyle mntl-schema-unified" type="application/ld+json" data-defer="load" data-defer-params></script>" triggers a post request via javascript to get the data.

**Comment by christianlupus** [comment]
Yes, you might be correct. Another (very rough) idea was to use a bookmarklet (see #431). Then we could use the client's browser instead of a headless one. However, honestly, I have not thought it through completely.

**Comment by christianlupus** [comment]
> The content is loaded via javascript in a deferred manner so it might be impossible without using a headless browser or a proxy with headless-browser which then renders the complete source :-( `<script id="schema-lifestyle_1-0" class="comp schema-lifestyle mntl-schema-unified" type="application/ld+json" data-defer="load" data-defer-params></script>` triggers a post request via javascript to get the data.

I honestly do not see the URL in this snippet. Can you @bfritscher  elaborate a bit more? Also, I can reproduce the loading in neither the following requests nor in the DOM tree of my browser.

**Comment by bfritscher** [comment]
@christianlupus Sure. if you look at the source of the page you see the empty script tag `<script id="schema-lifestyle_1-0" class="comp  schema-lifestyle mntl-schema-unified" type="application/ld+json" data-defer="load" data-defer-params></script>`
The same tag gets populated after page load. In DOM: 
![image](https://user-images.githubusercontent.com/338973/125766880-02fe149d-a728-4139-9dcf-817b731de23e.png)
The request done by the data-defer script is a post request with a lot of form data: 
![image](https://user-images.githubusercontent.com/338973/125767217-5025f982-53b2-4355-9efd-6cb93bf37733.png)
![image](https://user-images.githubusercontent.com/338973/125767264-fd983e18-5b4c-463d-899f-94aa1725eea7.png)

The code which parses the page:
![image](https://user-images.githubusercontent.com/338973/125767552-34856c83-55d0-4213-8a76-885b68a4b368.png)
