### ISSUE TITLE
Print icon

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/cookbook#728]
The print icon should be changed. Currently misleading the user. It should be associated with the printer.

![obraz](https://user-images.githubusercontent.com/47037905/119453766-0e42a900-bd38-11eb-9e7c-3b032b907cf9.png)

**Versions**
Nextcloud server version: 21.0.2
Cookbook version: 0.8.4

**Comment by seyfeb** [comment]
I agree with you here. Somebody would need to create an appropriate icon designed consistently with the existing ones. Currently we are only using icons from the [Nextcloud icon set](https://docs.nextcloud.com/server/latest/developer_manual/design/icons.html) which has no printer icon as far as I know.

**Comment by Valdnet** [comment]
There is no printer icon, because I have not encountered the possibility of printing in Nextcloud applications yet. This is the first that surprised me pleasantly with the ability to print directly from the application 🥇.

> Somebody would need to create an appropriate icon designed consistently with the existing ones.

This should be reported to the design team 😉.

**Comment by xf-** [comment]
I don't think the print icon is needed at all. Everybody has a print icon in the browser menu or ctrl+p. This is at the moment more confusing than helping. Looks more like a focus mode.
Clean display of recipe.

**Comment by iconocles** [comment]
> I don't think the print icon is needed at all. Everybody has a print icon in the browser menu or ctrl+p.

My seventy-year-old mother who doesn't understand how to use kebab menus let alone keyboard shortcuts would disagree.
