### ISSUE TITLE
Number of keywords not correct

### ISSUE THREAD

**Issue by Thomas-Lupo** [nextcloud/cookbook#737]
The number of recipes for a keyword is not counted correctly.
Easy to see when clicking a keyword the number counted is not.
In the example, twice as many caches are counted as there are, but this is not always the case.
![Number of keywords not correct Nexcloud Cookbook](https://user-images.githubusercontent.com/80398688/120639356-895f3a00-c471-11eb-8478-6866ec8e9ce4.png)

I thought rescanning the library might help, but unfortunately it does nothing.

Firefox 89.0
Nextcloud Server 21.0.2
Cookbook 0.8.4
Database system: MariaDB

Regards Thomas

**Comment by seyfeb** [comment]
Thanks for reporting! Are you able to provide exact steps on how to reproduce this? E.g., starting from a clean installation?

**Comment by christianlupus** [comment]
Just out of curiosity: Are you sharing the recipes with another user? You have 6 recipes shown and 12 is 2*6...

**Comment by Thomas-Lupo** [comment]
@christianlupus: No I'm not sharing the recipes. It's a small self hosted Nextcloud installation I use for storing data and there are not always twice as many recipes as shown.

**Comment by Thomas-Lupo** [comment]
@seyfeb: Since I use the cookbook rather more then less productive and I collected already a whole bunch of recipes over the time, I think there will be no problem if I start from scratch. But I will try it at the weekend. 
Btw. two other questions concerning this.
1. Is it save to use another recipe folder for this try so I can switch back to my library afterwards?
2. Is in the rescan library function some kind of consistency check implemented.

**Comment by christianlupus** [comment]
Let me try to give you an answer to your questions. 

You can switch back and forth the recipe folder. In the current app state this change will take a short period (to iterate all recipes) of time but that is all.

The rescanning will rebuild the complete database cache. It will drop the cache and irate over the files. While doing so a few checks are run. But these are mainly checking the recipe for consistency and minor bugs. The same checks should have run when initially adding the recipe.

When in doing this, you can of course make a complete backup of your installation. Never a bad idea, if you try something out.

**Comment by christianlupus** [comment]
Ahh, one more question: how m recipes do you have in total (approximately)?

**Comment by Thomas-Lupo** [comment]
Hi @christianlupus,

thanks a lot for your comments on my questions. First of all, I collected quite a lot recipes over time, there are about 500 :-)
Sometimes the cookbook it is a bit slow, but that is mainly due to my server equipment.

I changed the recipes folder to an empty folder. Than I had to click an rescan so the changes have been applied. 
After that I switched back to my original folder and rescan just to check that everything was still ok.
And now all numbers of keywords are ok. @seyfeb So I'm not trying to build up a library test, I think there were some inconsistencies in my library, which have been solved withe the rescan.

Thank you for your support, for me this issue is solved and could be closed.

**Comment by christianlupus** [comment]
Nice to hear this is done successfully. I will close now.

PS: Regarding the app speed, there seem to be some drawbacks/issues but as far as I know no explicit bottlenecks have been identified. Some minor bad design decisions (in retro perspective) have been made during the initial develoment. If you find a clear indication where such a bottleneck lies, you can of couse make a new issue und inform us of the problems/intentions.
