### ISSUE TITLE
Import-failed message without content.

### ISSUE THREAD

**Issue by Scaenicus** [nextcloud/cookbook#738]
**Description**
The error-message on import fail has no conent.

**Reproduction**
1. Try to import https://www.ichkoche.at/tiroler-knoedel-rezept-1639 
   + (Separate issue #739)

**Expected behavior**
Import working. If not working, an error message which explains the problem to me.

**Actual behavior**
Import not working. An empty error message.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1033699/120788954-3d73ca00-c531-11eb-99c6-3430174c7670.png)

**Browser**
Firefox 89.0

**Versions**
Nextcloud server version: Nextcloud 21.0.2
Cookbook version: 0.8.4
Database system:  MariaDB

**Comment by Scaenicus** [comment]
From testing around for #740 it could be that [this exeption](https://github.com/nextcloud/cookbook/blob/master/lib/Service/RecipeService.php#L509) is not resulting in an error message to be shown.

```php
$recipes = $xpath->query("//*[@itemtype='http://schema.org/Recipe']");
if (!isset($recipes[0])) {
    throw new \Exception('Could not find recipe element');
}
```

**Comment by christianlupus** [comment]
If you have a look at the latest branch, you will see that this is already solved. See #702.
