### ISSUE TITLE
Calculating for a different number servings

### ISSUE THREAD

**Issue by hexemag** [nextcloud/cookbook#742]
### Calculating by hand would take a lot of time
We use this app to collect recipes that we'd like to cook during summer camp. That means that the recipes are submitted in "normal" serving portions like 4 servings. But in use we'd have to calculate it up to about 150 servings. Doing that with every meal every day takes a lot of time and it would be a great feature when the app could do that automatically

### Maybe splitting amount, measurement and ingredient?
Though I don't know how to program it maybe one could split up the ingredients and the amount you need of it. When you choose a servingnumber it would only calculate the number. I know some websites like allrecipes.com that do that. Maybe there's also a way of adding a measermant request, that would transfer into higher scales? Like one recipe need 200g for 4 servings so it would automatically make it 1kg for 20 servings?

is that doable? thanks a lot though
xoxo

**Comment by seyfeb** [comment]
Duplicate, see #116 for discussion!
