### ISSUE TITLE
Empty error window

### ISSUE THREAD

**Issue by ramon-kramer** [nextcloud/cookbook#743]
**Description**
Empty error window with some sites following schema.org

**Reproduction**
1. Insert url 'https://schrotundkorn.de/rezepte/indisches-spinat-curry'
2. Click on 'Download'
3. See error

**Expected behavior**
See helpful error message.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/45063149/121316474-ab413c80-c909-11eb-850d-24d62e9324db.png)

**Error log**
{"reqId":"2kRsw3Sh353HLVV3XHuF","level":2,"time":"2021-06-09T08:01:17+00:00","remoteAddr":"x.x.x.x","user":"xxx","app":"cookbook","method":"POST","url":"/nextcloud/apps/cookbook/import","message":"libxml: Error 23 occurred 383 times while parsing https://schrotundkorn.de/rezepte/indisches-spinat-curry. Last time in line 3 and column 315954: htmlParseEntityRef: expecting ';'\n","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"20.0.8.1"}
{"reqId":"2kRsw3Sh353HLVV3XHuF","level":2,"time":"2021-06-09T08:01:17+00:00","remoteAddr":"x.x.x.x","user":"xxx","app":"cookbook","method":"POST","url":"/nextcloud/apps/cookbook/import","message":"libxml: Error 801 occurred 32 times while parsing https://schrotundkorn.de/rezepte/indisches-spinat-curry. Last time in line 3 and column 315760: Tag footer invalid\n","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"20.0.8.1"}

**Browser**
Firefox 86.0 (64-Bit)

**Versions**
Nextcloud server version: 20.0.8
Cookbook version: 0.8.4
Database system: PostgreSQL

**Comment by christianlupus** [comment]
OK, there are two issues involved here:

First, the message should not be empty. See #702, this is already solved on the `master` branch.

Second, the website does not correctly import. This is due to the fact, that no schema.org metadata is provided by schrotundkorn.de.
