### ISSUE TITLE
Update nextlcoud-app cookbook to the newest version killed my whole installation

### ISSUE THREAD

**Issue by Spoonler** [nextcloud/cookbook#754]
I wanted to update the cookbook plugin to the newest version (Update to 20.0.10). The Nextcloud went into an error and when I now want to access my nextcloud instance the following error occurs:

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'ALTER TABLE oc_cookbook_names ADD PRIMARY KEY (recipe_id)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '30095' for key 'PRIMARY'

Detaillierte Protokollmeldungen 

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'ALTER TABLE oc_cookbook_names ADD PRIMARY KEY (recipe_id)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '30095' for key 'PRIMARY'

**Comment by sankayop** [comment]
Hi,
First of all, thanks to the dev for the pretty app, I was looking for something like this years ago and I do appreciate this app.
This being said, I just had the exact same issue as @Spoonler .
To bypass it, I disabled the app via the terminal and deactivate the maintenance mode.
Obviously, cookbook is no more working for the moment.
the update message:
"""
Update to 21.0.2
Exception: Database error when running migration latest for app cookbook
Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Exception: Database error when running migration latest for app cookbook
The update was unsuccessful. Please report this issue to the Nextcloud community.
https://github.com/nextcloud/server/issues
"""
and after the disabling:
"""
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2247942' for key 'PRIMARY'
"""

Thanks in advance for taking the time to debug it :) (no worries, I still have the paper version lying on the shelf :) )

**Comment by Co0p3r21** [comment]
Like @sankayop says disableing the app helps temporaly. This way you can use nextcloud again 
`occ app:disable cookbook`

**Comment by willhelm-mueller** [comment]
After disabling the app via console i was able to log into nextcloud again. 

Upgrade of the cookbook app fails with the following error message:

An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1529' for key 'PRIMARY'

**Comment by seyfeb** [comment]
Sorry guys and thanks for the immediate feedback! This allows us to withdraw the release to prevent others from running into this until it’s fixed. We’re looking into what might be the issue here.

**Comment by christianlupus** [comment]
A quick guess for @Spoonler @sankayop @Co0p3r21 @willhelm-mueller: I assume, you have one user in the NC installation that shared the recipes with another user. Am I right?

**Comment by Spoonler** [comment]
@christianlupus no i didn't shared the recipes with another user.

**Comment by sankayop** [comment]
> > A quick guess for @Spoonler @sankayop @Co0p3r21 @willhelm-mueller: I assume, you have one user in the NC installation that shared the recipes with another user. Am I right?
> 
> yes that is true for me, i shared the cookbook folder with several other users

indeed, with 2 other local users.

**Comment by christianlupus** [comment]
I suspect the problem lies with the sharing. I do not know why @Spoonler has this problem as well when no sharing was done. Maybe an old entry in the database that was not correctly garbage collected. No clue here :confused:.

The problem with the sharing is that the same recipe is inserted for each user. As the (primary) key is the id of the folder in the NC, the key is no longer unique in the table causing exactly the named error.

First, the app needs another update, as this special case was not considered/tested during development. My bad, sorry. After that we need your installations to be reactivated. As the installation will most probably not be able to be carried out, we will have to clean out the database entries that cause the trouble. To repair that issue you can do the following:
- Make a backup of your database (in case you mistype or break something else). Eventually, a full backup is a good idea.
- `TRUNCATE` the tables in the database related to the cookbook app (starting table names with `oc_cookbook`). Do **not** change the other tables of the core or any other app.
- Now, you should be able to install the partly installed app. Do not yet reactivate as this will cause the error at another location to arise during usage.

I would create a hot-fix and ask some of you to check if the installation is still working after adding the fix. Further explanations will follow eventually.

**Comment by willhelm-mueller** [comment]
Cookbook works after a manually downgrade* to cookbook 8.4.



* Deinstall broken cookbook
* Download cookbook 8.4 via commandline
* Untar the app into app folder 
* enable the app via occ

a more detailed howto is described here:
https://github.com/nextcloud/server/issues/1599#issuecomment-304375592

**Comment by christianlupus** [comment]
OK, I was able to reproduce the problem partially. In fact, I triggered it by other means but got the same message. I also created a hotfix in #755. If you want to have a try, you can use [these instructions](https://nextcloud.github.io/cookbook/dev/use-autobuild) to try it out.

The best is if you remove the app from your NC installation and reinstall the latest (0.8.6) from the app store. This should work in general again. Please check with multiple users that have sharted recipes that they see these recipes (trigger rescan if needed).

After having a running cookbook app again, you can try the steps in the link above. Possibly NC will inform you that an upgrade needs to be performed, once you replaced the files of the app. Do it and look out for error messages. You will then be shown to run on cookbook version 0.9.0 but it is a modified pre-0.9.1 version in reality.

Please report back if this fixed the issue for you. Then I can make a 0.9.1 version ready without the problem.

**Comment by sankayop** [comment]
Hi @christianlupus,
I removed cookbook and reinstalled the default version (in my case 0.8.4) and it works.
Currently, I don't want to do any manual modification to nextcloud since I have a deadline at work.
I keep your instructions in my head.
Thanks for your help anyway,

**Comment by poltrian** [comment]
`
    Make a backup of your database (in case you mistype or break something else). Eventually, a full backup is a good idea.
    TRUNCATE the tables in the database related to the cookbook app (starting table names with oc_cookbook). Do not change the other tables of the core or any other app.
    Now, you should be able to install the partly installed app. Do not yet reactivate as this will cause the error at another location to arise during usage.`

Means these Drop all oc_cookbook entries (in my Case 3) in the database? And reinstall cookbook?

**Comment by poltrian** [comment]
unfortunately i don't know what truncate means. I have 8.4 again and it works

**Comment by christianlupus** [comment]
Truncate means to delete all rows from a table but keep the table in place. See [truncate](https://dev.mysql.com/doc/refman/8.0/en/truncate-table.html) vs [drop](https://dev.mysql.com/doc/refman/8.0/en/drop-table.html) for MySQL for example.

**Comment by maltejahn** [comment]
Hi,

I probably have the exact same error:
`UniqueConstraintViolationException An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7725-user2' for key 'names_recipe_idx'`

This, in the mean time, occur about 100 times for different recipes So.. now how to handle this. 

I took a look into the database using phpmyadmin ("SELECT * FROM `oc_cookbook_xxx` where `recipe_id` = 7725"  and i see every recipe_id atleast two times 
..._categories 3x  user1, 2x user2
..._names -1x user1, 1x user2
..._keywords - no entry

can i manually remove every entry in .._names + ..._categories where user2 is mentioned. Or is it necessary to:
![Image](https://github.com/user-attachments/assets/0d7e7f2f-767c-4cea-a85e-a7f5e2d2dba1)
for these 3 tables? Does this affect the recipes? 

How can I avoid this in the future. Isnt it possible to share a cookbook? ReadOnly access for user2?

Sorry for asking that, but playing around with the database isnt the fun i am looking for.

Thx
Malte
