### ISSUE TITLE
Could not create folder

### ISSUE THREAD

**Issue by terencedesu** [nextcloud/cookbook#765]
**Description**
Both in importing recipes and creating new recipe app throws error "could not create folder"

**Reproduction**
1. enter valid URL in "import recipe" box and click arrow or...
2. create a new recipe and enter information and click checkmark
3. app gives error "could not create folder" 

**Expected behavior**
New recipe would be written to Recipe folder

**Actual behavior**
App fails to create the desired recipe. Folder and files do not appear in Recipe folder.

**Screenshots**
none

**Browser**
Tested using latest versions of Firefox and Brave browsers

**Versions**
Nextcloud 21.0.2
Cookbook version: 0.9.1
Database system: MariaDB

**Comment by christianlupus** [comment]
What folder is configured as recipe folder?
Can you manually create a folder within (using the files app)? Remove it again afterwards. 
Are there yet any recipes stored in that folder? Did the earlier versions work for your setup?

**Comment by terencedesu** [comment]
Thanks for the quick reply. I have used the app for a long time now and it
was working before. It is the regular Recipes folder created by the app. I
actually tried the folder creation in the Recipe folder using the files app
shortly after filing the issue and can’t do it, but can in other folders.
My guess is the permissions on that folder changed, but I don’t know how.
It has been a while since I added recipes, so it may have been like that
for a while. I am the admin on the Nextcloud, so I can go and change
permissions if needed

**Comment by christianlupus** [comment]
OK, then the problem is most probably not within the cookbook app. The created folder is just a plain NC folder, nothing special/fancy about it. Unless you have writable access to the folder, testing with the cookbook app does not make much sense.

Is the folder somehow special like a shared mount point or externally mounted? Was there a quota reached? Did you tweak on the underlying file system (permission issue on the server)?

**Comment by terencedesu** [comment]
No it is the regular folder and no quota has been reached. I am traveling
now without my computer but when I can access the nextcloud I’ll look at
the permissions.

**Comment by terencedesu** [comment]
Got to my regular computer. Somehow the ownership of that one folder got
changed. I changed it back to the www-data and it works fine.now. Sorry for
the confusion and thanks for such a quick response. This still is one of my
favorite Nextcloud apps.

**Comment by christianlupus** [comment]
OK, I will close the topic for now.
