### ISSUE TITLE
[Feature request] Import image from URL

### ISSUE THREAD

**Issue by teemue** [nextcloud/cookbook#771]
Currently, when creating a recipe, an image can be picked only from the nextcloud user storage. I'd suggest adding an option to fetch images straight from URL's.

**Comment by christianlupus** [comment]
This is already implemented. Just put an URL there in the field and the app will download the URL and save it on the NC instance.

If this is not working as describe, please add a comment, then we have to check further.

**Comment by teemue** [comment]
Oh I had missed that, it wasn't that obvious.
Well, as a suggestion: add an short description (like grayed text on the empty image path field) stating that both URL and file browser are valid options. Also, indicator of valid url (or completed url fetch unless it's done after saving the recipe) could be a nice to see :)
