### ISSUE TITLE
Official Nextcloud 22 Support.

### ISSUE THREAD

**Issue by skyrid3r698** [nextcloud/cookbook#793]
**Is your feature request related to a problem? Please describe.**
This is one of the only apps holding me on Nextcloud 21. 

**Describe the solution you'd like**
Official nc 22 support.

**Comment by cohenchris** [comment]
Agreed. There was a commit a while back that officially introduced Nextcloud 22 support, but no new release for it has been made yet. Not sure why... this is the last app holding me back as well. Would really appreciate a new release!

**Comment by thrdroom** [comment]
Hi devs of cookbook. Please update this app to support Nextcloud 22, as im in the same situation of this beeing the only roadblock for my Nextcloud Update. Thanks in advance.

**Comment by poltrian** [comment]
Have Simeone tried  to Run the App with nc 22?

**Comment by christianlupus** [comment]
I prepared the NC 22 support already. In fact, it was merely a flag in the XML.

The question is if there are any issues still open. I have not tested thoroughly on NC22. So, if anyone can enable the app on NC22, I can quickly fire up a patch release. There are no significant changes since the last release, so you can enable an untested app and report back.

**Comment by KRiedmiller** [comment]
Just updated to NC 22 and activated the app. Old recipes are still there, new ones can be added as usual. 
I just tested for a few minutes but there don't seem to be any issues.

**Comment by DavidKoot** [comment]
Confirmed: Old recipes are there, adding and editing recipes works as expected, so far after trying for some time working in the editor.

**Comment by cohenchris** [comment]
I also briefly tried the app. Didn't test for very long, but all basic functionality works as far as I tried.

**Comment by RJ-Make** [comment]
I've been using it for a while now in 22, all seems to be working.

**Comment by carnager** [comment]
The app works fine, but the android client that exists for it gives an error:

```
Categories could not be loaded Make sure that the cookbook plugin is installed on your system!
Unexpected Character (at character 1)
<!DOCTYPE html>
^
```

**Comment by christianlupus** [comment]
I pushed a new release to the app store. This makes the app formally compatible to NC22.

For all those that have added an exception, you can remove that now.
