### ISSUE TITLE
Adding the "Nook" client to the android app list.

### ISSUE THREAD

**Issue by RJ-Make** [nextcloud/cookbook#796]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Add the "Nook" client to the android app list.

I've been using this app for a few months now and like it a lot and think it should be listed. 

Thank You for all your hard work on the Cookbook program, it is VERY much appreciated.

**Comment by christianlupus** [comment]
@RJ-Make Could you provide more information like an url?

The alternative would be to open a pull request and type the appropriate information directly.

**Comment by RJ-Make** [comment]
> 
> 
> @RJ-Make Could you provide more information like an url?
> 
> The alternative would be to open a pull request and type the appropriate information directly.

Opps, Sorry about that. Here is the app on the google play store. 

https://play.google.com/store/apps/details?id=org.capacitor.cookbook.app
