### ISSUE TITLE
On overview page food thumbnails not rotated by EXIF info

### ISSUE THREAD

**Issue by gthrepwood** [nextcloud/cookbook#803]
**Description**
On overview page, when image rotation only marked in exif info, the image is not showing in correct angle

**Reproduction**
1. Upload a recipe with Image
![IMG_20211008_080050](https://user-images.githubusercontent.com/6817306/136565179-89cff385-c391-4d9f-b3b6-de83494b9492.jpg)
2. Go to mail recipe list page (https://...../apps/cookbook/#/)
3. Thumbnail wont show in correct angle (rotated 90)

**Expected behavior**
Image rotated correctly and show in correct angle

**Screenshots**
Added
![image](https://user-images.githubusercontent.com/6817306/136565463-dc1aa17c-1bf7-4ce2-b1d2-e6d3e11a1cc5.png)

**Browser**
Chrome

**Versions**
Nextcloud server version: 21.0.4
Cookbook version: 3.6.1(?)

**Comment by christianlupus** [comment]
I just checked this out and I think, I found the issue. It seems to be a bug in the NC server code. I am just preparing a PR there. Additionally, I am trying to find a workaround in the meantime.

Just for verification: The image is correctly oriented when the recipe is regularly opened, right @gthrepwood?

**Comment by gthrepwood** [comment]
yes, it's showing correctly in the recipe view.

>
