### ISSUE TITLE
Add linter githooks

### ISSUE THREAD

**Issue by seyfeb** [nextcloud/cookbook#836]
This aims for a more comfortable development.

There is already a githook for linting the php code defined. Add hooks for eslint, stylelint, and prettier as well.

See https://github.com/nextcloud/cookbook/tree/master/.hooks

**Comment by christianlupus** [comment]
I added some coffee for the hooks, however this is no ideal solution. On my machine a single commit takes around 10 seconds. This is reducing productivity especially when commits are rejected by the tests. 

My suggestion is to split up the checks. Code styling could be reduced to be checked only before pushing. That way no code style is enforced during hacking.
The liner could still run (takes still 4 seconds). Maybe there can be some caching enabled. 

What do you think @seyfeb?

**Comment by seyfeb** [comment]
☕️ 10secs is definitely annoying for each commit. Before pushing would be great, though! 4 seconds sound okayish to me
