### ISSUE TITLE
Second page is printed without last items for cooking

### ISSUE THREAD

**Issue by sapiency** [nextcloud/cookbook#843]
**Description**
Only items of cooking which fit on page 1 are printed, second page contains only header and footer.

**Reproduction**
1. create recipe with more cooking items than fit on one page, e.g. [recipe](https://www.chefkoch.de/rezepte/3716051562425483/Gebratener-Reis-mit-Huehnerbrust-Ei-und-Gemuese.html).
a)2. Use print icon and print to printer or file
b)2. Use print preview of browser
.. 3. Look at page 2

**Expected behavior**
All items for cooking will be printed, even if they have to be printed on page 2.

**Actual behavior**
Only Items who fits on page 1 are printed.

**Browser**
Mozilla Firefox, 78.15.0esr

**Versions**
Nextcloud server version: 22.2.0
Cookbook version: 0.9.6
Database system: MariaDB

**Comment by christianlupus** [comment]
This is most probably a problem with the browser. We are not handling the page breaking but rely on the browser here.

On my machine (Archlinux with Firefox 93.0) I cannot confirm the problem:
![grafik](https://user-images.githubusercontent.com/8202922/141344401-8e7fd1e2-7333-4d30-be3d-54f5c6ec9ab5.png)

Can you check with a newer browser or another browser?

**Comment by sapiency** [comment]
Hi Christian,
thanks, it seems to be an old bug in Firefox ...
after I've found the rule for media print, I've looked around. This sounds similar:
[flexbox elements won't wrap](https://michaelborn.me/entry/firefox-bug-flexbox-elements-won-t-wrap-to-next-page-in-print)
I've verified with chromium and Firefox Developer and it is working there.
Thanks for your time and stay healthy!
... closed ...
