### ISSUE TITLE
categories can not be loaded. unexpected character 

### ISSUE THREAD

**Issue by Aaaamu** [nextcloud/cookbook#866]
**Description**
when i open the app i see my receipies for a second then the error message in the screenshot appears and no functionality is left. Recinnecting to the account does not help. 

**Reproduction**
i use the latest lineage os on a one+5 phone

**Expected behavior**

**Actual behavior**
Please describe in clear statements what is happening in reality.

**Screenshots**

![Screenshot_20211205-184501_Nextcloud_Cookbook](https://user-images.githubusercontent.com/23037248/144757616-3dde5ae9-501f-4d7c-ba7b-c3791e844680.png)

**Browser**
Which browser are you using?

**Versions**

Cookbook 0.7.0
nextclod server v 21.0.2

**Comment by christianlupus** [comment]
Hello @Aaaamu.

I am not 100% sure if you are correct here. Is the problem really related to the cookbook app on Nextcloud or one of the (Android?) apps? We are only working on the server app in this repo. Not on any app for a mobile phone.

**If you are referring to the core app:**
Is there a reason why you are running a quite outdated version of the app? We are currently at version 0.9.8 (released today).

**If you are referring to some 3rd party mobile app:**
What app are you referring to exactly? There are a few out there. See in [the README](https://github.com/nextcloud/cookbook#android).

**Comment by Aaaamu** [comment]
Hi you are totally right, sorry. I closed it and reopened it here: https://github.com/Teifun2/nextcloud-cookbook-flutter/issues/92

Thanks for the great app. Server app works like a charm. I customized the recipe folder and share it (writable) with friends. 

Am 5. Dezember 2021 21:41:43 MEZ schrieb Christian ***@***.***>:
>Hello @Aaaamu.
>
>I am not 100% sure if you are correct here. Is the problem really related to the cookbook app on Nextcloud or one of the (Android?) apps? We are only working on the server app in this repo. Not on any app for a mobile phone.
>
>**If you are referring to the core app:**
>Is there a reason why you are running a quite outdated version of the app? We are currently at version 0.9.8 (released today).
>
>**If you are referring to some 3rd party mobile app:**
>What app are you referring to exactly? There are a few out there. See in [the README](https://github.com/nextcloud/cookbook#android).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/cookbook/issues/866#issuecomment-986296503
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
