### ISSUE TITLE
Import from monsieur-cuisine.com

### ISSUE THREAD

**Issue by SaimenSays** [nextcloud/cookbook#872]
Is it possible to get import for recipes from [https://www.monsieur-cuisine.com/de/rezepte/](https://www.monsieur-cuisine.com/de/rezepte/)

**Comment by SaimenSays** [comment]
Came back and read the hints in README.md about shema.org.
I checked if there is a json with `"@type": "Recipe"` in some of the recipes. This site does not seem to follow the needed schema, so I think there is no simple way of importing from this website.
Can someone confirm to close this issue?

**Comment by christianlupus** [comment]
I just checked the link and I can confirm, that the website does not provide schema.org Recipe information. Some other information are provided but not the relevant ones.

So, sorry, you seem to be out of luck with this website.
