### ISSUE TITLE
Allow recipie calculation

### ISSUE THREAD

**Issue by tpawork** [nextcloud/cookbook#874]
**Is your feature request related to a problem? Please describe.**
It's not possible to scale the recipie for different portions.

**Describe the solution you'd like**
Inrgedient should be split into amount, unit and name. currently its only a string.
Then it would be possible to make calculations for different portions.

(Also a ingredient database that can be filled manually and select in the recipie creator would be nice :)

**Comment by seyfeb** [comment]
Duplicate of #116
