### ISSUE TITLE
Missing appinfo/info.xml breaks translations

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/cookbook#875]
Since https://github.com/nextcloud/cookbook/commit/ef2537ca41a36345fc92447ca22edcc91f25ab4c there was no update of translations anymore.
The translation script fails with the following error:
> tx INFO: Pushing source file (translationfiles/templates/cookbook.pot)
tx ERROR: Could not upload source file. You can use --skip to ignore this error and continue the execution.
tx ERROR: [Errno 2] No such file or directory: '/app/translationfiles/templates/cookbook.pot'

The problem is because you removed the appinfo/info.xml, the appid can not be read, so it falls back to directory name (best guess) and that does not work with the translation script as all apps are checked out into `/app`

However we also can not add a section for each app to run a command before doing translations. can you bring the file back?

**Comment by nickvergessen** [comment]
And sorry, in my attempt to debug this I seem to have pushed a commit to stable which triggered a 0.9.9

**Comment by christianlupus** [comment]
> Since [ef2537c](https://github.com/nextcloud/cookbook/commit/ef2537ca41a36345fc92447ca22edcc91f25ab4c) there was no update of translations anymore. The translation script fails with the following error:
> 
> > tx INFO: Pushing source file (translationfiles/templates/cookbook.pot)
> > tx ERROR: Could not upload source file. You can use --skip to ignore this error and continue the execution.
> > tx ERROR: [Errno 2] No such file or directory: '/app/translationfiles/templates/cookbook.pot'
> 
> The problem is because you removed the appinfo/info.xml, the appid can not be read, so it falls back to directory name (best guess) and that does not work with the translation script as all apps are checked out into `/app`
> 
> However we also can not add a section for each app to run a command before doing translations. can you bring the file back?

Yep, I removed the file intentionally. We had problems in the past with releasing new versions: When the app info files generated, it overwrote any setting regarding NC core compatibility accidentally only made in the _cached_ version `appinfo/info.xml` and not the template that is used for the generation (`.github/actions/deploy/appinfo/info.xml.dist`).

For now, there is a new release worth quite some translations out. I will have to look at this in a bit more detail and set up some sort of protection mechanism to avoid these nasty issues we had have. It might take a day or two. Hopefully, I can have a look on this at the weekend.

> And sorry, in my attempt to debug this I seem to have pushed a commit to stable which triggered a 0.9.9

Yes, I just saw. We will keep this 0.9.9 version as it contains dozens of translations.

**Comment by christianlupus** [comment]
I do not know, if you **are** relying on a valid `Makefile` to be present. If yes, you might safely call a `make appinfo/app.xml`. Unless the file needs rebuilding, make will just skip that step if the file is present.

**Comment by nickvergessen** [comment]
We can not run `make` on the translation sync machine.

**Comment by nickvergessen** [comment]
> When the app info files generated, it overwrote any setting regarding NC core compatibility accidentally only made in the cached version appinfo/info.xml and not the template that is used for the generation (.github/actions/deploy/appinfo/info.xml.dist).

Maybe you can set up a github action which cuts out the version line and then compares the 2 files to have an empty diff?
