### ISSUE TITLE
Newlines are not prevented when switching input fields

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#881]
**Description**
Currently, the [prevention of keyevents](https://github.com/nextcloud/cookbook/blob/d5d41a31d4e7defe6d6f1b6d003749747f59c69b/src/components/EditInputGroup.vue#L232) should avoid inserting a newline symbol if using enter to add a new entry. Unfortunately, the `keyup` event [does not allow this](https://stackoverflow.com/a/14055191/882756). As a result, the newline is added nontheless.

**Reproduction**
1. Edit a recipe
2. Add a new instruction row and/or go to the very last instruction text area
3. Press Enter

**Expected behavior**
A new area/step is added. The new step is empty. The old one is unaffected by the enter pressing.

**Actual behavior**
The newline is in the text area and later in the recipe visible.

**Screenshots**

**Browser**
Which browser are you using? Firefox

**Comment by MarcelRobitaille** [comment]
Is the only reason for listening to `keyup` insted of `keydown` so that there are no repeated events? Could a solution to this be to use `keydown` and to filter out any events with `event.repeat === True`?

**Comment by christianlupus** [comment]
Honestly, i do not know why it was implemented as it is. I am not very forever in js and thus just hacking around.
I understand that only during key down the event can be prevented. So we will have to go in this direction. I consider the current code a bit clumsy there (personal feeling) as new additions are hard to add.

If you see a simple solution you are free to correct things. If as a byproduct you can tidy up that piece of code to separate concerns that would be even better.

**Comment by christianlupus** [comment]
@MarcelRobitaille just out of curiosity, are you intending to offer your help on this issue?

I am asking as this might round up the issues around the pressing enter topic for the ingredient/tools/instructions fields. I would push out a release with the recent changes but I'd wait until you are done if this was soon on the agenda. Please report back.

**Comment by MarcelRobitaille** [comment]
Hi @christianlupus. Yes, that is why I commented to ask for more information. 

Sorry for not getting to it. I thought I still had to wait for some decision, but reading your previous comment again I think I can manage it now. How quickly do you want to make the release?

**Comment by MarcelRobitaille** [comment]
May I ask why we are checking for `e.keyCode === 10`? I have seen other people doing this online, but I cannot find this 10 in any table of JavaScript keycodes. Is there some legacy browser that requires this?

I propose to use `e.key === 'Enter'` instead. It is more readable, and `e.keyCode` is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode. Do you see any reason not to do this?

**Comment by seyfeb** [comment]
I think it is pretty safe to replace the keycode with key.
