### ISSUE TITLE
Switching to next instruction row impossible

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#882]
**Description**
It should be possible to switch to the next instruction row by pressing enter (see [this snippet](https://github.com/nextcloud/cookbook/blob/d5d41a31d4e7defe6d6f1b6d003749747f59c69b/src/components/EditInputGroup.vue#L247-L249)). However, an error is printed to the console.

**Reproduction**
1. Edit a recipe
2. Make sure it has multiple instruction rows.
3. Select any instruction row but the last one
4. Hit enter

**Expected behavior**
The next row is put to focus.

**Actual behavior**
Nothing happens visually. An error is logged to the console.

The reason is the fact that the instructions are `textarea` elements and not `input` elements. The search in [this line](https://github.com/nextcloud/cookbook/blob/d5d41a31d4e7defe6d6f1b6d003749747f59c69b/src/components/EditInputGroup.vue#L248) will cause no matching DOM element to be found.

**Comment by MarcelRobitaille** [comment]
I am able to reproduce this. I would like to work on this issue.
