### ISSUE TITLE
Error message only on Android devices: Exception: type '_smi' is not a subtype of type 'string' in type cast

### ISSUE THREAD

**Issue by ruckb** [nextcloud/cookbook#884]
**Description**
Getting an error message
Exception: type '_smi' is not a subtype of type 'string' in type cast
but only on Android devices, PC based I can open / modify the recipe 

**Reproduction**
Import: https://www.essen-und-trinken.de/rezepte/89843-rzpt-spinat-broccoli-nudelauflauf
try to open the recipe with cookbook on an android device  

**Versions**
Nextcloud server version: 22.2.03
Cookbook version: 0.9.8
Database system:  Sqlite

any idea ?

**Comment by ruckb** [comment]
just tried to import this one on my android device .. same error message during import, so I guess this is due to the source ? 
I have deleted the link to the source for one version .. no change.. so it seems this is still in the cookbook locylly...

**Comment by ruckb** [comment]
potentially there is a diameter sign in this one ... somehow I got it working, but have still issues with sync between PC and cellphone...

**Comment by seyfeb** [comment]
Just to avoid confusion: @ruckb, you are not using an Android app, but accessing the Cookbook via a browser on your mobile device? If so, which mobile browser are you using?

**Comment by ruckb** [comment]
I used the android app ... where do I find the app version ?

Hermann

**Comment by seyfeb** [comment]
Some links to a few apps are collected in the Readme (https://github.com/nextcloud/cookbook/blob/master/README.md). The apps are developed independently from this repository, so you would have to report your issue with the developer(s) of the specific app you're using!

I'm going to close this issue because there's nothing we can do here :)

**Comment by shaneonabike** [comment]
@ruckb I'm using Teifun2's version so I reported an issue here https://github.com/Teifun2/nextcloud-cookbook-flutter/issues/114

@seyfeb Sorry for the noise and reporting it in the wrong queue.
