### ISSUE TITLE
Fix the linking of recipes in tools/ingredients/instructions

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#905]
**Description**
There is a bug in the implementation of the `EditInputGroup` that causes a missing `#` symbol during adding a link to another recipe.

See also [this comment](https://github.com/nextcloud/cookbook/pull/900#issuecomment-1059367049).

**Reproduction**
1. Edit/create a recipe
2. Add a tool, ingredient, or instruction
3. Type a sharp symbol
4. Select one recipe

**Expected behavior**
The text contains a correct link like `#r/1234`.

**Actual behavior**
The initial `#` is not printed.

**Versions**
Cookbook version: 0.9.10

**Comment by MarcelRobitaille** [comment]
I think we only need to delete [this line: `e.preventDefault()`](https://github.com/nextcloud/cookbook/blob/db9986b853f0e1202fce69f9e4e795a3bf30e3cd/src/components/EditInputGroup.vue#L316). I can open a PR if you would like.

**Comment by christianlupus** [comment]
That would be good. Also keep an eye if any indices might be set wrong such that the paste is somehow disturbed.

**Comment by MarcelRobitaille** [comment]
I can't reproduce this. I checked out the master branch, and when I follow the steps, I get `#r/123` with the sharp. I am using Firefox 97.0.1. I can make a PR without that `e.preventDefault()` anyway, there is no reason for it to be there.

**Comment by christianlupus** [comment]
I made a screencast to show my problems. This is different for you?

https://user-images.githubusercontent.com/8202922/158067642-79adfe34-5aab-4e88-8a77-1d5581c5089d.mp4

**Comment by christianlupus** [comment]
I tested it with firefox + chrome on Win 10 using Browserstack. The same effect happens as in the video.
