### ISSUE TITLE
Make info blocks configurable, whether displayed or not displayed

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/cookbook#906]
It would be nice to be able to configure which info blocks should be displayed on the recipe and which should not. 
E. g. the info blocks Preparation time (hours:minutes); Cooking time (hours:minutes); Total time (hours:minutes); Nutrition Information; Tools are not interesting for me and distract from important (for me) part. 

The configuration should be global and not depending on the recipe

---

Depends on #1067

**Comment by christianlupus** [comment]
Depends on #1067

**Comment by christianlupus** [comment]
If you need help with the backend part, just ping me.

**Comment by christianlupus** [comment]
PS: Without a link to a branch, we cannot help you much...

**Comment by MarcelRobitaille** [comment]
@christianlupus Sorry, I've been very busy. Here is my branch: https://github.com/MarcelRobitaille/cookbook/tree/906-hide-info-blocks. I opened a draft pull request to track the progress: #1404.
