### ISSUE TITLE
Blur/unfocus the background upon popup showing

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#907]
When a popup is shown like when user should select a recipe by typing the `#`, this popup has too l little contrast to the rest of the page. It is hard for the eye (at least for mine) to see that I need to do something in a dialog and should not use the rest of the page instead.

I would suggest to either blur the background (aka main app canvas), make it semi-transparent, put a semi-transparent black/gray filter over it or put a more prominent frame around the popup to get more prominent.

**Comment by ananyak19** [comment]
Hey, is this available? 
Can I work on this?

**Comment by MarcelRobitaille** [comment]
I think this issue should be reconsidered, at least for the sharp popup. The point of #1098 was to make that popup less obtrusive, so it should definitely not have a blurred background. Maybe for other popups this still makes sense, but if we use the proper Nextcloud Vue components, I think it handles that for us.

As far as being available, nobody is working on this at the moment as far as I know.

**Comment by christianlupus** [comment]
We have only a handful of popups present ATM. The selection of recipes during the linking phase as described by @MarcelRobitaille I consider no longer a real popup.

For the other popups the Vue components of `@nextcloud/vue` have that already handled by the library. So, I would close this issue now as it is no longer a valid request.
