### ISSUE TITLE
Small input fields in recipe creation on mobile device

### ISSUE THREAD

**Issue by seyfeb** [nextcloud/cookbook#908]
**Description**
On my mobile device the input fields, especially the description is far too small 

**Expected behavior**
It should fill the width of the window. for other fields like name probably as well 

**Screenshots**
![Screenshot_20220305-213233_Firefox_1](https://user-images.githubusercontent.com/7623143/156899242-17554748-7baa-4046-bb58-4af441709a91.png)

**Browser**
FF 97.2.0 on android

**Versions**
Nextcloud server version: 21
Cookbook version: 0.9.10

**Comment by MarcelRobitaille** [comment]
I can reproduce the small name field in desktop Firefox by narrowing the browser, but I cannot reproduce the description in that way. May I ask you screen size?

**Comment by seyfeb** [comment]
I have a galaxy S9 with reported screen width of 408px. I have the same issue in Vivaldi on mobile. 

I can't reproduce it in the FF or Vivaldi dev tools on my desktop either. I guess that's why I didn't notice this when I implemented it in the first place.. :S

**Comment by MarcelRobitaille** [comment]
I found the problem and the reason it only happens on mobile.

On mobile, the markdown editor used ([v-markdown-editor](https://www.npmjs.com/package/v-markdown-editor) which depends on [CodeMirror](https://github.com/codemirror/codemirror)) [adds the HTML attribute `contenteditable="true"`](https://github.com/codemirror/CodeMirror/blob/master/src%2Fedit%2Foptions.js#L77). This triggers styling in Nextcloud core: [here](https://github.com/nextcloud/server/blob/master/core%2Fcss%2Finputs.scss#L31) and [here](https://github.com/nextcloud/server/blob/master/core%2Fcss%2Finputs.scss#L49).

I can reproduce @seyfeb's screenshot on desktop Firefox by setting `contenteditable="true"` on the CodeMirror `div` (`.CodeMirror-code`, parent of `pre.CodeMirror-line`):

https://user-images.githubusercontent.com/8503756/157312702-3b3a0857-0dbd-4344-bad5-b613c94c2378.mp4

It is a shame that Nextcloud core is setting such unscoped styles that even affect the dependency of a dependency of an app. I think our only option is to overwrite these styles.
