### ISSUE TITLE
Android nextcloud account support for Android App

### ISSUE THREAD

**Issue by jimbolaya** [nextcloud/cookbook#921]
**Is your feature request related to a problem? Please describe.**
Currently, it's required to use an App password to connect to my server. I'd like to be able to use the Nextcloud account already on the phone.

**Describe the solution you'd like**
Is it possible to use the Android account option for the  App to use the Nextcloud account already set up in the Nextcloud App on the phone?

**Comment by seyfeb** [comment]
Hi jimbolaya, this repository contains the code for the nextcloud cookbook app, which runs in the web browser. for any questions related to different apps, e. g., mobile apps I'd like to refer you to the respective developers. Some are linked in the initial Readme of this repository!
