### ISSUE TITLE
Update Swagger API

### ISSUE THREAD

**Issue by newhinton** [nextcloud/cookbook#929]
**Description**

POST [​/api​/recipes](https://nextcloud.github.io/cookbook/dev/api/0.0.2/index.html#/Recipes/post_api_recipes) Create a new recipe

does not have an example for the request body. It seems the json of a recipe as per standard is valid and working, but it should be documented. 

Also, it seems the return values are wrong. When i upload a recipe twice, it does not return 409 but the id of the original recipe. Also the example where the error is thrown seems to be outdated.

**Reproduction**
1. call `/index.php/apps/cookbook/api/recipes` with POST and a recipe as body twice.
2. get id twice

**Expected behavior**

The api should throw an error.

**Comment by christianlupus** [comment]
I added some hints in the documentation as suggested by you.

The bug itself I was not able to reproduce. I tried both with my current dev environment and with my production machine. Both returned 409 errors when a recipe exists already.

Are you on the latest release of the cookbook app?
