### ISSUE TITLE
Display links with recipe's title instead of id 

### ISSUE THREAD

**Issue by zorglubu** [nextcloud/cookbook#935]
Currently, an internal link toward another recipe is displayed with the id like `#r/12345`

It would be useful to display this link by replacing the id with the title of the recipe  __My other recipe__, looking like standard url links.
And it might be just in the display mode while keeping  `#r/12345` in the edit mode.

**Comment by christianlupus** [comment]
There is the basic question in #858 of all recipes should be extracted and cached in the frontend or not. Depending on that we can decide where this feature request must be located: in the frontend or the backend.

So, the decision in #858 should be finished first.
