### ISSUE TITLE
Please add compatibility with NC24

### ISSUE THREAD

**Issue by elpraga** [nextcloud/cookbook#975]
Thank you for your great work! It world bed lovely to see the app work with NC24!

**Comment by christianlupus** [comment]
Did you by chance add the cookbook to your NC24 instance and check if it works? It should work and I will gladfully mark it compatible with NC24. It should be compatible but I have not tested myself.

**Comment by elpraga** [comment]
Thank you for your reply @christianlupus !

I have not upgraded to NC24 yet, There are still some apps that I do use, but are not yet compatible with NC24.

I'm sorry, I cannot test the Cookbook app against NC24 ATM.

**Comment by takaoni** [comment]
Just upgraded and everything seems working :+1:

**Comment by leex279** [comment]
Tested it too, works well.

**Comment by Flying--Dutchman** [comment]
Can confirm, everything seems to be working
