### ISSUE TITLE
Consider using cURL instead of file_get_contents for recipe import

### ISSUE THREAD

**Issue by landfish2102** [nextcloud/cookbook#979]
When php.ini contains the setting `allow_url_fopen=0`, recipe import by URL will fail with the error `file_get_contents() https:// wrapper is disabled in the server configuration by allow_url_fopen=0`. Changing the setting in the server's php.ini will obviously fix this, however, some hosting environments still disable allow_url_fopen as a security measure.

Since the php curl module is already a requirement for Nextcloud, please consider using cURL instead of `file_get_contents` to import recipes from remote urls in order to improve compatibility with restrictive web hosts.

**Comment by MarcelRobitaille** [comment]
May be related to this thread: https://github.com/nextcloud/cookbook/issues/284#issuecomment-1073121437

**Comment by christianlupus** [comment]
This might be easier to be implemented with #553. I just rebased it hoping to get this merged soon.
