### ISSUE TITLE
Websites which require authenticaton

### ISSUE THREAD

**Issue by lgrawet** [nextcloud/cookbook#981]
**Is your feature request related to a problem? Please describe.**
The website hosting recipes I want to import requires authentication.

**Describe the solution you'd like**
Possibility to pass the session cookie or token

**Describe alternatives you've considered**
None

**Comment by christianlupus** [comment]
This is not so easy. You need to extract the corresponding session token manually as we cannot extract it from another page. This is the most basic security setting in all JS browsers to prevent the simplest XSS attacks. So, we would rely on user experience to identify and copy the auth token/cookie.

This might be feasible for some power users, it is too much for an average _pure_ user of our app.

As a side note: If the page uses additionally some way of (invisible) captcha, we are out as well.

I think the better way to go might be to use the client-side browser for such cases. The user can log in as normal, and pass any captcha/auth as normal. Then, a JS bookmarklet is started by the user to extract the HTML and pass everything to the server for evaluation. See #431.
I want to point out that additional resources (like e.g. images) might still be problematic even with a bookmarklet.

I am closing this here. If the community thinks differently, we can reopen.
