### ISSUE TITLE
Header: Refresh-icon overlays name of recipe

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/cookbook#987]
**Description**
Header: Icon overlays name of recipe

**Reproduction**
1. Open a recipe
2. See header

**Expected behavior**
The refresh-icon ![cb_2](https://user-images.githubusercontent.com/34692335/168068618-ff6d2cfe-0cf0-4747-8964-47947fcc8f04.svg)  is left of the name of the recipe

**Actual behavior**
The refresh-icon overlays the name of the recipe

**Browser**
Firefox 100.0
Chrome 101.0.4951.64
Edge 101.0.1210.39 

**Versions**
Nextcloud server version: 23.0.4)
Cookbook version:  	0.9.12	

**Screenshots**

![cb_1](https://user-images.githubusercontent.com/34692335/168068590-1077ca2b-5c7c-49c6-bdad-e8904c632288.png)

**Comment by MarcelRobitaille** [comment]
I started working on this a while ago as part of #896. The decision there was that the recipe name and reload button should not be siblings like this. The reload button should be moved with the other buttons (edit, print, delete).

Maybe for now we should simply make the reload button like edit, print, delete and worry about replacing the breadcrumbs with something better later.

**Comment by christianlupus** [comment]
> Maybe for now we should simply make the reload button like edit, print, delete and worry about replacing the breadcrumbs with something better later.

If this is a quick fix, I'd go for it. The updated structure as you wrote is still on the agenda, so it should be an easy fix. If you have a good idea, go for it.

**Comment by MarcelRobitaille** [comment]
Ok, I will try to add that part this weekend.

**Comment by christianlupus** [comment]
@MarcelRobitaille please report back if you need something.

**Comment by MarcelRobitaille** [comment]
Sorry for the delay in getting to this. I got very busy with my thesis. The temporary solution is implemented in #1033. It works in recipe edit and recipe view.

![image](https://user-images.githubusercontent.com/8503756/172527328-039d4574-b94e-474a-ae15-8d68aa45167c.png)

![image](https://user-images.githubusercontent.com/8503756/172527360-83a31b84-f49d-4d89-927e-ed20a6c4228c.png)
